/* Option lists — [value, தமிழ், English] */
window.MAT_DATA = (function () {
  var o = function (a) { return a.map(function (x) { return { v: x[0], ta: x[1], en: x[2] || x[1] }; }); };
  return {
    created_for: o([['self', 'எனக்காக', 'Myself'], ['son', 'என் மகனுக்காக', 'My son'], ['daughter', 'என் மகளுக்காக', 'My daughter'], ['brother', 'சகோதரருக்காக', 'My brother'], ['sister', 'சகோதரிக்காக', 'My sister'], ['relative', 'உறவினருக்காக', 'A relative'], ['friend', 'நண்பருக்காக', 'A friend']]),
    gender: o([['M', 'மணமகன்', 'Groom (Male)'], ['F', 'மணமகள்', 'Bride (Female)']]),
    marital: o([['never', 'திருமணமாகாதவர்', 'Never married'], ['divorced', 'விவாகரத்து', 'Divorced'], ['widowed', 'துணை இழந்தவர்', 'Widowed'], ['separated', 'பிரிந்து வாழ்பவர்', 'Separated']]),
    religion: o([['hindu', 'இந்து', 'Hindu'], ['christian', 'கிறிஸ்தவர்', 'Christian'], ['muslim', 'முஸ்லிம்', 'Muslim'], ['jain', 'ஜைனர்', 'Jain'], ['sikh', 'சீக்கியர்', 'Sikh'], ['other', 'பிற', 'Other']]),
    community: o([
      ['kannada_devanga', 'கன்னட தேவாங்கர்', 'Kannada Devanga'],
      ['devanga_other', 'தேவாங்கர் – பிற பிரிவு', 'Devanga – other group'],
      ['saurashtra', 'சௌராஷ்டிரர்', 'Saurashtra'], ['vishwakarma', 'விஸ்வகர்மா', 'Vishwakarma'], ['mudaliar', 'முதலியார்', 'Mudaliar'], ['chettiar', 'செட்டியார்', 'Chettiar'],
      ['gounder', 'கவுண்டர்', 'Gounder'], ['naidu', 'நாயுடு', 'Naidu'], ['nadar', 'நாடார்', 'Nadar'], ['pillai', 'பிள்ளை', 'Pillai'], ['thevar', 'தேவர்', 'Thevar'],
      ['vanniyar', 'வன்னியர்', 'Vanniyar'], ['yadav', 'யாதவர்', 'Yadav'], ['reddy', 'ரெட்டி', 'Reddy'], ['brahmin', 'பிராமணர்', 'Brahmin'], ['lingayat', 'லிங்காயத்', 'Lingayat'],
      ['adi_dravidar', 'ஆதிதிராவிடர்', 'Adi Dravidar'], ['other', 'பிற (குறிப்பிடவும்)', 'Other (please specify)']
    ]),
    star: o([['ashwini', 'அசுவினி', 'Ashwini'], ['bharani', 'பரணி', 'Bharani'], ['krittika', 'கார்த்திகை', 'Krittika'], ['rohini', 'ரோகிணி', 'Rohini'], ['mrigashira', 'மிருகசீரிடம்', 'Mrigashira'], ['thiruvathirai', 'திருவாதிரை', 'Thiruvathirai'], ['punarpusam', 'புனர்பூசம்', 'Punarpusam'], ['pusam', 'பூசம்', 'Pusam'], ['ayilyam', 'ஆயில்யம்', 'Ayilyam'], ['magam', 'மகம்', 'Magam'], ['pooram', 'பூரம்', 'Pooram'], ['uthiram', 'உத்திரம்', 'Uthiram'], ['hastham', 'அஸ்தம்', 'Hastham'], ['chithirai', 'சித்திரை', 'Chithirai'], ['swathi', 'சுவாதி', 'Swathi'], ['visakam', 'விசாகம்', 'Visakam'], ['anusham', 'அனுஷம்', 'Anusham'], ['kettai', 'கேட்டை', 'Kettai'], ['moolam', 'மூலம்', 'Moolam'], ['pooradam', 'பூராடம்', 'Pooradam'], ['uthiradam', 'உத்திராடம்', 'Uthiradam'], ['thiruvonam', 'திருவோணம்', 'Thiruvonam'], ['avittam', 'அவிட்டம்', 'Avittam'], ['sathayam', 'சதயம்', 'Sathayam'], ['poorattathi', 'பூரட்டாதி', 'Poorattathi'], ['uthirattathi', 'உத்திரட்டாதி', 'Uthirattathi'], ['revathi', 'ரேவதி', 'Revathi']]),
    raasi: o([['mesham', 'மேஷம்', 'Mesham (Aries)'], ['rishabam', 'ரிஷபம்', 'Rishabam (Taurus)'], ['mithunam', 'மிதுனம்', 'Mithunam (Gemini)'], ['kadagam', 'கடகம்', 'Kadagam (Cancer)'], ['simmam', 'சிம்மம்', 'Simmam (Leo)'], ['kanni', 'கன்னி', 'Kanni (Virgo)'], ['thulam', 'துலாம்', 'Thulam (Libra)'], ['viruchigam', 'விருச்சிகம்', 'Viruchigam (Scorpio)'], ['dhanusu', 'தனுசு', 'Dhanusu (Sagittarius)'], ['magaram', 'மகரம்', 'Magaram (Capricorn)'], ['kumbam', 'கும்பம்', 'Kumbam (Aquarius)'], ['meenam', 'மீனம்', 'Meenam (Pisces)']]),
    dosham: o([['no', 'இல்லை', 'No'], ['sevvai', 'செவ்வாய் தோஷம்', 'Chevvai (Mars) dosham'], ['raghu_kethu', 'ராகு-கேது தோஷம்', 'Raghu–Kethu dosham'], ['other', 'பிற தோஷம்', 'Other dosham'], ['dontknow', 'தெரியாது', "Don't know"]]),
    mother_tongue: o([['kannada', 'கன்னடம்', 'Kannada'], ['tamil', 'தமிழ்', 'Tamil'], ['telugu', 'தெலுங்கு', 'Telugu'], ['malayalam', 'மலையாளம்', 'Malayalam'], ['hindi', 'இந்தி', 'Hindi'], ['marathi', 'மராத்தி', 'Marathi'], ['gujarati', 'குஜராத்தி', 'Gujarati'], ['saurashtra', 'சௌராஷ்டிரம்', 'Saurashtra'], ['english', 'ஆங்கிலம்', 'English'], ['other', 'பிற', 'Other']]),
    education: o([['school', 'பள்ளிப் படிப்பு', 'School'], ['diploma', 'டிப்ளமோ / ITI', 'Diploma / ITI'], ['ug', 'இளங்கலை (B.A/B.Sc/B.Com…)', "Bachelor's (Arts/Science/Commerce)"], ['be', 'B.E / B.Tech', 'B.E / B.Tech'], ['medical', 'மருத்துவம் / நர்சிங்', 'Medical / Nursing'], ['pg', 'முதுகலை (M.A/M.Sc/M.Com…)', "Master's (Arts/Science/Commerce)"], ['me', 'M.E / M.Tech', 'M.E / M.Tech'], ['mba', 'MBA / MCA', 'MBA / MCA'], ['ca', 'CA / ICWA / CS', 'CA / ICWA / CS'], ['law', 'சட்டம்', 'Law'], ['phd', 'முனைவர் (PhD)', 'Doctorate (PhD)'], ['other', 'பிற', 'Other']]),
    employer_type: o([['govt', 'அரசுப் பணி', 'Government'], ['private', 'தனியார் நிறுவனம்', 'Private'], ['business', 'சொந்தத் தொழில்', 'Business / Self-employed'], ['agri', 'விவசாயம்', 'Agriculture'], ['abroad', 'வெளிநாட்டுப் பணி', 'Working abroad'], ['student', 'படிக்கிறார்', 'Studying'], ['notworking', 'பணியில் இல்லை', 'Not working']]),
    income_band: o([['lt2', '₹2 லட்சத்திற்கும் குறைவு', 'Below ₹2 lakh'], ['2to5', '₹2 – 5 லட்சம்', '₹2–5 lakh'], ['5to10', '₹5 – 10 லட்சம்', '₹5–10 lakh'], ['10to20', '₹10 – 20 லட்சம்', '₹10–20 lakh'], ['gt20', '₹20 லட்சத்திற்கு மேல்', 'Above ₹20 lakh'], ['na', 'குறிப்பிட விரும்பவில்லை', 'Prefer not to say']]),
    diet: o([['veg', 'சைவம்', 'Vegetarian'], ['nonveg', 'அசைவம்', 'Non-vegetarian'], ['egg', 'முட்டை மட்டும்', 'Eggetarian']]),
    family_type: o([['joint', 'கூட்டுக் குடும்பம்', 'Joint family'], ['nuclear', 'தனிக் குடும்பம்', 'Nuclear family']]),
    family_status: o([['middle', 'நடுத்தரம்', 'Middle class'], ['upper_middle', 'உயர் நடுத்தரம்', 'Upper middle class'], ['rich', 'வசதியான', 'Affluent']]),
    state: o([['Tamil Nadu', 'தமிழ்நாடு', 'Tamil Nadu'], ['Karnataka', 'கர்நாடகம்', 'Karnataka'], ['Andhra Pradesh', 'ஆந்திரா', 'Andhra Pradesh'], ['Telangana', 'தெலங்கானா', 'Telangana'], ['Kerala', 'கேரளா', 'Kerala'], ['Maharashtra', 'மகாராஷ்டிரா', 'Maharashtra'], ['Delhi', 'டெல்லி', 'Delhi'], ['Other India', 'இந்தியாவின் பிற மாநிலம்', 'Other Indian state'], ['Outside India', 'வெளிநாடு', 'Outside India']]),
    report_reason: o([['fake', 'போலி சுயவிவரம்', 'Fake profile'], ['contact', 'தொடர்பு எண்/முகவரி கேட்கிறார்', 'Asking for contact details'], ['abuse', 'தவறான / மிரட்டும் செய்தி', 'Abusive messages'], ['money', 'பணம் கேட்கிறார்', 'Asking for money'], ['married', 'ஏற்கனவே திருமணம் ஆனவர்', 'Already married'], ['other', 'பிற', 'Other']])
  };
})();
