/* Kalvi Kalanjiyam — "Understand it" science & real-life games (Classes 6–10).
   Same question format as games-mid.js. Every number in an answer is COMPUTED from the numbers shown;
   tests/games.test.cjs re-solves each one from the question text with independent code.
   Written from scratch: story scenarios, our own numbers, our own explanations (g = 10 m/s² in school-style problems). */
(function(G){
'use strict';
const {S, ri, pick, shuffle, fmt} = G.KALVI_UTIL;
const {opts} = G.KALVI_MID_UTIL;
const X = {};
const n2 = x => String(+(Math.round(x * 100) / 100));
const NAMES = [['அருண்','Arun'],['மீனா','Meena'],['கவின்','Kavin'],['தமிழ்','Tamil'],['பிரியா','Priya'],['முகிலன்','Mugilan'],['நிலா','Nila'],['இனியன்','Iniyan']];
const person = () => pick(NAMES);
const U = (u) => v => u === '₹' ? '₹' + n2(v) : (u ? n2(v) + ' ' + u : n2(v));
const r4 = x => typeof x === 'number' ? Math.round(x * 1e4) / 1e4 : x;
// numeric question: p = [ta,en], ans number, cands numbers, unit
function Q(pta, pen, scene, ans, cands, unit, exta, exen){ ans = r4(ans); cands = cands.map(r4); return {p:S(pta, pen), scene:scene || '', opts: opts(ans, cands, U(unit)), ans, ex:S(exta, exen)}; }
// choice question over strings
function C(pta, pen, scene, ans, list, exta, exen, labels){ const lab = labels ? (v => labels[v]) : (v => v); return {p:S(pta, pen), scene:scene || '', opts: opts(ans, list.filter(x => x !== ans), lab, Math.min(4, list.length)), ans, ex:S(exta, exen)}; }

/* ================= PHYSICS ================= */
const VEH = [['🚌','பேருந்து','bus',[30,40,45,50,60,80]],['🚆','ரயில்','train',[60,72,80,90,100,120]],['🚲','சைக்கிள்','bicycle',[10,12,15,20]],['🛺','ஆட்டோ','auto-rickshaw',[20,30,40]],['🏍️','பைக்','bike',[30,40,50,60]]];
X.speedStory = { title:S('வேகம் – தூரம் – நேரம் கதைகள்', 'Speed–distance–time stories'), icon:'🚌',
  intro:S('வேகம் என்றால் 1 மணி நேரத்தில் செல்லும் தூரம். 60 km/h = ஒவ்வொரு மணிக்கும் 60 km. எனவே தூரம் = வேகம் × நேரம்; நேரம் = தூரம் ÷ வேகம்; வேகம் = தூரம் ÷ நேரம். பயணம் எப்போது முடியும் என்று கணிக்க இதுவே வழி!',
          'Speed is the distance covered in ONE hour. 60 km/h = 60 km every hour. So distance = speed × time; time = distance ÷ speed; speed = distance ÷ time. This is how you predict when a journey ends!'),
  gen(){ const v = pick(VEH), s = pick(v[3]), t = v[2] === 'bicycle' ? ri(1, 4) : ri(1, 6), d = s * t, k = ri(0, 2), nm = person();
    if(k === 0) return Q(`${nm[0]} ${v[1]} ${s} km/h வேகத்தில் ${t} மணி நேரம் செல்கிறது. தூரம் எவ்வளவு?`, `A ${v[2]} travels at ${s} km/h for ${t} hours. How far does it go?`, `<div style="font-size:42px">${v[0]}</div>`, d, [s + t, s * t + s, d * 2, Math.round(s / t)], 'km', `ஒவ்வொரு மணிக்கும் ${s} km × ${t} மணி = ${d} km`, `${s} km every hour × ${t} hours = ${d} km`);
    if(k === 1) return Q(`${v[1]} ${s} km/h வேகத்தில் ${d} km செல்ல எவ்வளவு நேரம்?`, `A ${v[2]} goes ${d} km at ${s} km/h. How long does it take?`, `<div style="font-size:42px">${v[0]}</div>`, t, [d - s, d * s, t + 1, t * 2], 'hours', `நேரம் = தூரம் ÷ வேகம் = ${d} ÷ ${s} = ${t} மணி`, `time = distance ÷ speed = ${d} ÷ ${s} = ${t} hours`);
    return Q(`${v[1]} ${d} km தூரத்தை ${t} மணியில் கடந்தது. வேகம் எவ்வளவு?`, `A ${v[2]} covers ${d} km in ${t} hours. What is its speed?`, `<div style="font-size:42px">${v[0]}</div>`, s, [d - t, d * t, s + 10, s * 2], 'km/h', `வேகம் = தூரம் ÷ நேரம் = ${d} ÷ ${t} = ${s} km/h`, `speed = distance ÷ time = ${d} ÷ ${t} = ${s} km/h`); } };

const KS = [10, 20, 25, 40, 50, 100];
X.springStretch = { title:S('சுருள்வில் எவ்வளவு நீளும்?', 'How far does the spring stretch?'), icon:'🧷',
  intro:S('ஹூக் விதி: F = k × x. எடை (விசை) இரட்டிப்பானால் நீட்சியும் இரட்டிப்பு. k = சுருள்வில்லின் உறுதி (N/m). 100 g எடை ≈ 1 N (g = 10 எனக் கொள்க). நீட்சி (cm) = எடை (g) ÷ k, ஏனெனில் F = எடை ÷ 100, x = F ÷ k × 100.',
          'Hooke\'s law: F = k × x. Double the weight, double the stretch. k is the spring\'s stiffness (N/m). 100 g weighs ≈ 1 N (take g = 10). Stretch (cm) = mass (g) ÷ k, because F = mass ÷ 100 and x = F ÷ k × 100.'),
  gen(){ const k = pick(KS); const x = ri(1, 12), m = x * k, t = ri(0, 2); // m grams, x cm
    if(t === 0) return Q(`k = ${k} N/m உள்ள சுருள்வில்லில் ${m} g எடையைத் தொங்கவிட்டால் நீட்சி? (g = 10 m/s²)`, `A spring with k = ${k} N/m carries a ${m} g mass. Stretch? (g = 10 m/s²)`, '<div style="font-size:40px">🧷⬇️</div>', x, [x * 2, Math.max(1, x - 1), x + 2, m / 10], 'cm', `F = ${m} ÷ 100 = ${n2(m / 100)} N; x = F ÷ k = ${n2(m / 100)} ÷ ${k} m = ${x} cm`, `F = ${m} ÷ 100 = ${n2(m / 100)} N; x = F ÷ k = ${n2(m / 100)} ÷ ${k} m = ${x} cm`);
    if(t === 1) return Q(`k = ${k} N/m சுருள்வில் ${x} cm நீண்டது. தொங்கிய எடை எவ்வளவு? (g = 10 m/s²)`, `A spring (k = ${k} N/m) stretched ${x} cm. What mass hangs on it? (g = 10 m/s²)`, '<div style="font-size:40px">🧷⬇️</div>', m, [m * 2, m / 2 + 10, m + 100, x * 10], 'g', `F = k × x = ${k} × ${n2(x / 100)} = ${n2(k * x / 100)} N → ${m} g`, `F = k × x = ${k} × ${n2(x / 100)} = ${n2(k * x / 100)} N → ${m} g`);
    return Q(`${m} g எடை சுருள்வில்லை ${x} cm நீட்டியது. சுருள்வில்லின் k எவ்வளவு? (g = 10 m/s²)`, `A ${m} g mass stretches a spring ${x} cm. Find k. (g = 10 m/s²)`, '<div style="font-size:40px">🧷⬇️</div>', k, [k * 2, Math.round(k / 2), k + 10, m], 'N/m', `F = ${n2(m / 100)} N, x = ${n2(x / 100)} m → k = F ÷ x = ${k} N/m`, `F = ${n2(m / 100)} N, x = ${n2(x / 100)} m → k = F ÷ x = ${k} N/m`); } };

const MAT = [['கார்க்','cork',0.25],['மரம்','wood',0.6],['பனிக்கட்டி','ice',0.92],['பிளாஸ்டிக்','plastic',1.1],['அலுமினியம்','aluminium',2.7],['இரும்பு','iron',7.8],['செம்பு','copper',8.9],['தங்கம்','gold',19.3]];
const LIQ = [['எண்ணெய்','oil',0.9],['நீர்','water',1],['உப்பு நீர்','salt water',1.2],['பாதரசம்','mercury',13.6]];
X.densityFloat = { title:S('மிதக்குமா? மூழ்குமா?', 'Float or sink?'), icon:'🧊',
  intro:S('அடர்த்தி = நிறை ÷ கனஅளவு (g/cm³). நீரின் அடர்த்தி 1. பொருளின் அடர்த்தி திரவத்தை விடக் குறைவு → மிதக்கும்; அதிகம் → மூழ்கும். இரும்புக் கப்பல் மிதப்பது ஏன்? உள்ளே நிறையக் காற்று — மொத்த அடர்த்தி நீரை விடக் குறைவு!',
          'Density = mass ÷ volume (g/cm³). Water is 1. Object denser than the liquid → sinks; less dense → floats. Why does an iron ship float? It holds lots of air, so its overall density is below water!'),
  gen(){ const k = ri(0, 2);
    if(k === 0){ const V = pick([10, 20, 25, 50, 100]), rho = pick([0.5, 0.8, 1.2, 2, 2.5, 4, 5, 8]), m = rho * V; if(!Number.isInteger(m)) return X.densityFloat.gen();
      return Q(`ஒரு பொருளின் நிறை ${m} g, கனஅளவு ${V} cm³. அடர்த்தி?`, `An object has mass ${m} g and volume ${V} cm³. Its density?`, '', rho, [m - V, m * V, rho * 2, V / 10], 'g/cm³', `அடர்த்தி = ${m} ÷ ${V} = ${n2(rho)} g/cm³`, `density = ${m} ÷ ${V} = ${n2(rho)} g/cm³`); }
    if(k === 1){ const o = pick(MAT), l = pick(LIQ); if(o[2] === l[2]) return X.densityFloat.gen(); const fl = o[2] < l[2];
      return C(`${o[0]} (அடர்த்தி ${o[2]}) ${l[0]}-ல் (அடர்த்தி ${l[2]}) போட்டால்?`, `A piece of ${o[1]} (density ${o[2]}) is dropped in ${l[1]} (density ${l[2]}). It will…`, '', fl ? 'float' : 'sink', ['float', 'sink'], `${o[2]} ${fl ? '<' : '>'} ${l[2]} ஆகையால் ${fl ? 'மிதக்கும்' : 'மூழ்கும்'}`, `${o[2]} is ${fl ? 'less' : 'more'} than ${l[2]}, so it ${fl ? 'floats' : 'sinks'}`, {float:'மிதக்கும் / floats', sink:'மூழ்கும் / sinks'}); }
    const V = pick([10, 20, 40, 50]), m = pick([5, 10, 20, 40, 60, 100, 200, 400]); const rho = m / V, fl = rho < 1;
    return C(`நிறை ${m} g, கனஅளவு ${V} cm³ உள்ள பொருளை நீரில் போட்டால்? (நீர் = 1 g/cm³)`, `A ${m} g object of volume ${V} cm³ goes into water (1 g/cm³). It will…`, '', rho === 1 ? 'hover' : (fl ? 'float' : 'sink'), rho === 1 ? ['hover', 'float', 'sink'] : ['float', 'sink'], `அடர்த்தி = ${m} ÷ ${V} = ${n2(rho)} ${rho === 1 ? '= நீரின் அடர்த்தி → நடுவில் நிற்கும்' : (fl ? '< 1 → மிதக்கும்' : '> 1 → மூழ்கும்')}`, `density = ${m} ÷ ${V} = ${n2(rho)} ${rho === 1 ? '= water → hovers' : (fl ? '< 1 → floats' : '> 1 → sinks')}`, {float:'மிதக்கும் / floats', sink:'மூழ்கும் / sinks', hover:'நடுவில் நிற்கும் / hovers'}); } };

X.pressureFelt = { title:S('அழுத்தம் — ஊசி ஏன் குத்துகிறது?', 'Pressure — why does a needle prick?'), icon:'📌',
  intro:S('அழுத்தம் = விசை ÷ பரப்பு. அதே விசை சிறிய பரப்பில் செயல்பட்டால் அழுத்தம் அதிகம் — அதனால்தான் ஊசி குத்தும், கத்தி வெட்டும்; அகலமான காலணி/டிராக்டர் சக்கரம் மண்ணில் புதையாது.',
          'Pressure = force ÷ area. The same force on a tiny area gives huge pressure — that is why a needle pricks and a knife cuts, and why wide tractor tyres don\'t sink into mud.'),
  gen(){ const A = pick([2, 4, 5, 10, 20, 25, 50]), P = ri(2, 40), F = P * A, k = ri(0, 3);
    if(k === 0) return Q(`${F} N விசை ${A} cm² பரப்பில் செயல்படுகிறது. அழுத்தம்?`, `A force of ${F} N acts on ${A} cm². Pressure?`, '', P, [F - A, F * A, P * 2, Math.max(1, Math.round(P / 2))], 'N/cm²', `அழுத்தம் = ${F} ÷ ${A} = ${P} N/cm²`, `pressure = ${F} ÷ ${A} = ${P} N/cm²`);
    if(k === 1) return Q(`அழுத்தம் ${P} N/cm², பரப்பு ${A} cm². விசை எவ்வளவு?`, `Pressure ${P} N/cm² on an area of ${A} cm². Force?`, '', F, [P + A, Math.round(F / 2), F * 2, F + 10], 'N', `விசை = அழுத்தம் × பரப்பு = ${P} × ${A} = ${F} N`, `force = pressure × area = ${P} × ${A} = ${F} N`);
    if(k === 2) return Q(`${F} N விசை, அழுத்தம் ${P} N/cm². பரப்பு எவ்வளவு?`, `Force ${F} N gives pressure ${P} N/cm². What is the area?`, '', A, [F - P, F * P, A * 2, A + 3], 'cm²', `பரப்பு = விசை ÷ அழுத்தம் = ${F} ÷ ${P} = ${A} cm²`, `area = force ÷ pressure = ${F} ÷ ${P} = ${A} cm²`);
    const f = pick([2, 4, 5]); return C(`அதே விசை, ஆனால் பரப்பு ${f} மடங்கு குறைந்தால் அழுத்தம்?`, `Same force, but the area becomes ${f} times smaller. Pressure…`, '', 'up', ['up', 'down', 'same'], `P = F ÷ A; A சிறியதானால் P பெரிதாகும் (${f} மடங்கு)`, `P = F ÷ A; smaller A means bigger P (${f} times)`, {up:`${f} மடங்கு கூடும் / rises ${f}×`, down:'குறையும் / falls', same:'மாறாது / same'}); } };

X.ohmHome = { title:S('V – I – R: வீட்டு மின்சாரம்', 'V – I – R: home electricity'), icon:'💡',
  intro:S('ஓம் விதி: V = I × R (V வோல்ட், I ஆம்பியர், R ஓம்). தடை அதிகம் → மின்னோட்டம் குறைவு. நம் வீட்டு மின்னழுத்தம் 220 V. மின்னோட்டம் அளவு மீறினால் கம்பி சூடாகி தீ பிடிக்கும் — அதனால்தான் பியூஸ்!',
          'Ohm\'s law: V = I × R (volts, amperes, ohms). More resistance → less current. Our home supply is 220 V. Too much current heats wires and can start a fire — that is why fuses exist!'),
  gen(){ const k = ri(0, 2), home = Math.random() < 0.4; let R, I, V;
    if(home){ I = pick([1, 2, 4, 5, 10, 11, 20]); V = 220; R = V / I; } else { R = pick([2, 3, 4, 5, 6, 10, 12, 20, 25, 50]); I = ri(1, 10); V = I * R; }
    const ap = ['🔦','💡','🔥','🌀'][ri(0, 3)];
    if(k === 0) return Q(`${V} V மின்னழுத்தம், தடை ${R} Ω. மின்னோட்டம்?`, `Voltage ${V} V across ${R} Ω. Current?`, `<div style="font-size:40px">${ap}</div>`, I, [V - R, V * R, I + 1, I * 2], 'A', `I = V ÷ R = ${V} ÷ ${R} = ${I} A`, `I = V ÷ R = ${V} ÷ ${R} = ${I} A`);
    if(k === 1) return Q(`${R} Ω தடையில் ${I} A மின்னோட்டம். மின்னழுத்தம்?`, `${I} A flows through ${R} Ω. Voltage?`, `<div style="font-size:40px">${ap}</div>`, V, [V + R, Math.round(V / 2), R + I, V * 2], 'V', `V = I × R = ${I} × ${R} = ${V} V`, `V = I × R = ${I} × ${R} = ${V} V`);
    return Q(`${V} V-ல் ${I} A மின்னோட்டம் ஓடினால் தடை?`, `${I} A flows when ${V} V is applied. Resistance?`, `<div style="font-size:40px">${ap}</div>`, R, [V - I, V * I, R * 2, R + 5], 'Ω', `R = V ÷ I = ${V} ÷ ${I} = ${R} Ω`, `R = V ÷ I = ${V} ÷ ${I} = ${R} Ω`); } };

const APP = [['🌀','மின்விசிறி','fan',60],['💡','LED பல்பு','LED bulb',9],['💡','குழல் விளக்கு','tube light',40],['📺','தொலைக்காட்சி','TV',100],['🧊','குளிர்சாதனப் பெட்டி','fridge',150],['👔','இஸ்திரிப் பெட்டி','iron',1000],['🍹','மிக்சி','mixer',500],['❄️','ஏசி','AC',1500],['🚿','கீசர்','geyser',2000],['💡','பழைய பல்பு','old bulb',60],['🔌','சார்ஜர்','charger',10]];
X.billSaver = { title:S('மின் கட்டணம் — யூனிட் கணக்கு', 'Electricity bill — unit maths'), icon:'🧾',
  intro:S('1 யூனிட் = 1 kWh = 1000 W கருவி 1 மணி நேரம் ஓடினால் ஆகும் மின்சாரம். யூனிட் = (வாட் × மணி × நாள்) ÷ 1000. கட்டணம் = யூனிட் × ஒரு யூனிட் விலை. இதைத் தெரிந்தால் எந்தக் கருவி அதிகம் செலவு என்று சொல்லிச் சேமிக்கலாம்! (விலை ஒரு எடுத்துக்காட்டு மட்டும்.)',
          '1 unit = 1 kWh = a 1000 W device running for 1 hour. Units = (watts × hours × days) ÷ 1000. Bill = units × price per unit. Knowing this tells you which device costs most, so you can save! (The price is just an example.)'),
  gen(){ const a = pick(APP), h = ri(1, 10), days = pick([10, 20, 30]), rate = pick([4, 5, 6, 8]), units = a[3] * h * days / 1000, k = ri(0, 2);
    if(!Number.isInteger(units * 100)) return X.billSaver.gen();
    if(k === 0) return Q(`${a[1]} (${a[3]} W) தினமும் ${h} மணி நேரம் ${days} நாட்கள் ஓடுகிறது. எத்தனை யூனிட்?`, `The ${a[2]} (${a[3]} W) runs ${h} hours a day for ${days} days. How many units?`, `<div style="font-size:40px">${a[0]}</div>`, units, [units * 10, units / 10, a[3] * h * days, units * 2], 'units', `${a[3]} × ${h} × ${days} ÷ 1000 = ${n2(units)} யூனிட்`, `${a[3]} × ${h} × ${days} ÷ 1000 = ${n2(units)} units`);
    if(k === 1) return Q(`${a[1]} (${a[3]} W) தினமும் ${h} மணி நேரம் ${days} நாட்கள் ஓடுகிறது. ஒரு யூனிட் ₹${rate} எனில் கட்டணம்?`, `The ${a[2]} (${a[3]} W) runs ${h} hours a day for ${days} days. At ₹${rate} per unit, the cost?`, `<div style="font-size:40px">${a[0]}</div>`, units * rate, [units + rate, units * rate * 10, units * rate / 10, units * rate * 2], '₹', `யூனிட் = ${n2(units)}; கட்டணம் = ${n2(units)} × ${rate} = ₹${n2(units * rate)}`, `units = ${n2(units)}; cost = ${n2(units)} × ${rate} = ₹${n2(units * rate)}`);
    const b = pick(APP.filter(x => x !== a && x[3] !== a[3])), h2 = ri(1, 10), uA = a[3] * h * 30 / 1000, uB = b[3] * h2 * 30 / 1000; if(uA === uB) return X.billSaver.gen();
    const ans = uA > uB ? a[1] : b[1];
    return {p:S(`எது மாதம் அதிக யூனிட் எடுக்கும்? ${a[1]} ${a[3]} W × ${h} h/நாள், அல்லது ${b[1]} ${b[3]} W × ${h2} h/நாள்`, `Which uses more units a month (30 days)? ${a[2]} ${a[3]} W × ${h} h/day, or ${b[2]} ${b[3]} W × ${h2} h/day`), scene:`<div style="font-size:34px">${a[0]} ⚖️ ${b[0]}</div>`, opts:shuffle([{v:a[1], h:`${a[1]} / ${a[2]}`},{v:b[1], h:`${b[1]} / ${b[2]}`}]), ans,
      ex:S(`${a[1]}: ${a[3]}×${h}×30÷1000 = ${n2(uA)} யூனிட்; ${b[1]}: ${b[3]}×${h2}×30÷1000 = ${n2(uB)} யூனிட்`, `${a[2]}: ${a[3]}×${h}×30÷1000 = ${n2(uA)} units; ${b[2]}: ${b[3]}×${h2}×30÷1000 = ${n2(uB)} units`)}; } };

X.seesawBalance = { title:S('சீ-சா சமநிலை', 'Seesaw balance'), icon:'⚖️',
  intro:S('சமநிலை வர: இடது எடை × தூரம் = வலது எடை × தூரம் (திருப்புத்திறன்). கனமானவர் மையத்துக்கு அருகில், இலகுவானவர் தொலைவில் அமர்ந்தால் சமநிலை! கத்தரிக்கோல், ஆணிபிடுங்கி, கிணற்றுத் துலா எல்லாம் இதே விதி.',
          'Balance needs: left weight × distance = right weight × distance (the moment). A heavy person near the pivot and a light one far away can balance! Scissors, claw hammers and the village well-sweep all use this.'),
  gen(){ let wL, dL, wR, dR, tries = 0; do { wL = ri(2, 10); dL = ri(1, 6); wR = ri(2, 10); dR = wL * dL / wR; tries++; } while((!Number.isInteger(dR) || dR < 1 || dR > 8 || wL === wR) && tries < 200);
    if(!Number.isInteger(dR)){ wL = 4; dL = 3; wR = 6; dR = 2; } const a = person(), b = pick(NAMES.filter(x => x !== a)), k = ri(0, 2);
    const scene = `<div style="font-size:34px">🧒⚖️🧒</div>`;
    if(k === 0) return Q(`${a[0]} (${wL} kg) மையத்திலிருந்து ${dL} அடி தூரத்தில். ${b[0]} (${wR} kg) எவ்வளவு தூரத்தில் அமர்ந்தால் சமநிலை?`, `${a[1]} (${wL} kg) sits ${dL} ft from the pivot. How far must ${b[1]} (${wR} kg) sit to balance?`, scene, dR, [dL, wL * dL, dR + 1, Math.max(1, dR - 1)], 'ft', `${wL} × ${dL} = ${wL * dL}; ${wR} × ? = ${wL * dL} → ? = ${dR} அடி`, `${wL} × ${dL} = ${wL * dL}; ${wR} × ? = ${wL * dL} → ? = ${dR} ft`);
    if(k === 1) return Q(`இடது: ${wL} kg ${dL} அடியில். வலது: ${dR} அடியில் எத்தனை kg வைத்தால் சமநிலை?`, `Left: ${wL} kg at ${dL} ft. Right side is at ${dR} ft. What weight balances it?`, scene, wR, [wL, wL * dL, wR + 2, Math.max(1, wR - 1)], 'kg', `${wL} × ${dL} = ${wL * dL}; ? × ${dR} = ${wL * dL} → ? = ${wR} kg`, `${wL} × ${dL} = ${wL * dL}; ? × ${dR} = ${wL * dL} → ? = ${wR} kg`);
    return Q(`இடது: ${wL} kg × ${dL} அடி. வலது: ${wR} kg × ${dR} அடி. இடது பக்கத் திருப்புத்திறன் (எடை × தூரம்) எவ்வளவு?`, `Left: ${wL} kg × ${dL} ft. Right: ${wR} kg × ${dR} ft. What is the left moment (weight × distance)?`, scene, wL * dL, [wL + dL, wR * dR + 1, wL * dL + 2, wL * dL - 2], 'kg·ft', `${wL} × ${dL} = ${wL * dL}. வலது: ${wR} × ${dR} = ${wR * dR} → சமம், சமநிலை!`, `${wL} × ${dL} = ${wL * dL}. Right: ${wR} × ${dR} = ${wR * dR} → equal, so balanced!`); } };

X.energyHeight = { title:S('உயரத்தில் ஆற்றல்', 'Energy of height & motion'), icon:'🎢',
  intro:S('உயரத்தில் உள்ள பொருளுக்கு நிலை ஆற்றல் PE = m × g × h (g = 10). இயங்கும் பொருளுக்கு இயக்க ஆற்றல் KE = ½ m v². கீழே விழும்போது PE → KE ஆகிறது; அதனால் v = √(2gh). ரோலர் கோஸ்டரும் அணை நீர் மின்சாரமும் இதுவே.',
          'A raised object has potential energy PE = m × g × h (g = 10). A moving object has kinetic energy KE = ½ m v². Falling turns PE into KE, so v = √(2gh). Roller coasters and hydro-power use exactly this.'),
  gen(){ const k = ri(0, 2);
    if(k === 0){ const m = pick([1, 2, 5, 10, 20, 50]), h = pick([1, 2, 3, 5, 10, 20]), E = m * 10 * h; return Q(`${m} kg பொருள் ${h} m உயரத்தில் உள்ளது. நிலை ஆற்றல்? (g = 10)`, `A ${m} kg object is ${h} m high. Its potential energy? (g = 10)`, '<div style="font-size:36px">🧱⬆️</div>', E, [m * h, E * 2, E + 10, E / 2], 'J', `PE = m g h = ${m} × 10 × ${h} = ${E} J`, `PE = m g h = ${m} × 10 × ${h} = ${E} J`); }
    if(k === 1){ const m = pick([2, 4, 6, 10, 20]), v = pick([2, 4, 5, 10]), E = m * v * v / 2; return Q(`${m} kg பொருள் ${v} m/s வேகத்தில் செல்கிறது. இயக்க ஆற்றல்?`, `A ${m} kg object moves at ${v} m/s. Its kinetic energy?`, '<div style="font-size:36px">🏃💨</div>', E, [m * v, m * v * v, E * 2, E + 5], 'J', `KE = ½ m v² = ½ × ${m} × ${v}² = ${E} J`, `KE = ½ m v² = ½ × ${m} × ${v}² = ${E} J`); }
    const h = pick([5, 20, 45, 80]), v = Math.sqrt(2 * 10 * h); return Q(`ஒரு கல் ${h} m உயரத்திலிருந்து விழுகிறது. தரையைத் தொடும் வேகம்? (g = 10, v = √(2gh))`, `A stone falls from ${h} m. Speed when it hits the ground? (g = 10, v = √(2gh))`, '<div style="font-size:36px">🪨⬇️</div>', v, [h, h * 2, v + 5, v / 2], 'm/s', `v = √(2 × 10 × ${h}) = √${20 * h} = ${v} m/s`, `v = √(2 × 10 × ${h}) = √${20 * h} = ${v} m/s`); } };

X.echoThunder = { title:S('எதிரொலி & இடி — தூரம் கண்டுபிடி', 'Echo & thunder — find the distance'), icon:'⛈️',
  intro:S('ஒலி காற்றில் வினாடிக்கு ≈ 340 m செல்கிறது; ஒளி கிட்டத்தட்ட உடனே வருகிறது. மின்னலைப் பார்த்து இடி கேட்கும் வரை உள்ள நொடி × 340 = மின்னல் எவ்வளவு தொலைவு. எதிரொலியில் ஒலி போய்த் திரும்புவதால் தூரம் = 340 × நேரம் ÷ 2. வௌவால், டால்ஃபின், சோனார் இதையே பயன்படுத்துகின்றன.',
          'Sound travels ≈ 340 m every second in air; light arrives almost instantly. Seconds between lightning and thunder × 340 = distance of the lightning. An echo goes there and back, so distance = 340 × time ÷ 2. Bats, dolphins and sonar use this.'),
  gen(){ const k = ri(0, 2);
    if(k === 0){ const t = ri(1, 10), d = 340 * t; return Q(`மின்னல் தெரிந்து ${t} வினாடிக்குப் பின் இடி கேட்டது. மின்னல் எத்தனை மீட்டர் தொலைவில்? (ஒலி = 340 m/s)`, `Thunder is heard ${t} s after the lightning flash. How far is the lightning? (sound = 340 m/s)`, '<div style="font-size:38px">⛈️</div>', d, [d / 2, 340 + t, d * 2, t * 100], 'm', `தூரம் = 340 × ${t} = ${fmt(d)} m`, `distance = 340 × ${t} = ${fmt(d)} m`); }
    if(k === 1){ const t = pick([1, 2, 4, 6, 8]), d = 170 * t; return Q(`மலையை நோக்கிக் கத்தினான். எதிரொலி ${t} வினாடியில் திரும்பியது. மலை எவ்வளவு தொலைவு? (ஒலி = 340 m/s)`, `A boy shouts at a cliff; the echo returns after ${t} s. How far is the cliff? (sound = 340 m/s)`, '<div style="font-size:38px">🏔️📣</div>', d, [340 * t, d / 2, d + 340, t * 100], 'm', `ஒலி போய்த் திரும்பியது: 340 × ${t} = ${340 * t} m; ஒரு வழி = ${d} m`, `Sound went there and back: 340 × ${t} = ${340 * t} m; one way = ${d} m`); }
    const t = pick([2, 4, 6, 8]), d = 1500 * t / 2; return Q(`கப்பலின் சோனார் அனுப்பிய ஒலி ${t} வினாடியில் கடல் தரையிலிருந்து திரும்பியது. நீரில் ஒலி = 1500 m/s. கடலின் ஆழம்?`, `A ship\'s sonar pulse returns from the sea floor after ${t} s. Sound in water = 1500 m/s. Depth?`, '<div style="font-size:38px">🚢🌊</div>', d, [1500 * t, d / 2, d + 1500, 340 * t / 2], 'm', `ஆழம் = 1500 × ${t} ÷ 2 = ${fmt(d)} m`, `depth = 1500 × ${t} ÷ 2 = ${fmt(d)} m`); } };

X.workPower = { title:S('வேலை & திறன்', 'Work & power'), icon:'🏋️',
  intro:S('அறிவியலில் வேலை = விசை × விசையின் திசையில் நகர்ந்த தூரம் (J). திறன் = வேலை ÷ நேரம் (W). ஒரே வேலையை விரைவாகச் செய்பவருக்கு திறன் அதிகம். 1000 W = 1 kW.',
          'In science, work = force × distance moved in the force\'s direction (J). Power = work ÷ time (W). Doing the same work faster means more power. 1000 W = 1 kW.'),
  gen(){ const k = ri(0, 2), F = pick([10, 20, 50, 100, 200]), d = ri(2, 12), W = F * d, t = pick([2, 4, 5, 10]);
    if(k === 0) return Q(`${F} N விசையால் பெட்டியை ${d} m தள்ளினால் செய்த வேலை?`, `A ${F} N force pushes a box ${d} m. Work done?`, '<div style="font-size:38px">📦➡️</div>', W, [F + d, W * 2, F * d * 10, W / 2], 'J', `வேலை = F × d = ${F} × ${d} = ${W} J`, `work = F × d = ${F} × ${d} = ${W} J`);
    if(k === 1){ const P = W / t; if(!Number.isInteger(P)) return X.workPower.gen(); return Q(`${W} J வேலையை ${t} வினாடியில் செய்தால் திறன்?`, `${W} J of work is done in ${t} s. Power?`, '<div style="font-size:38px">⚡</div>', P, [W * t, W - t, P * 2, Math.round(P / 2)], 'W', `திறன் = ${W} ÷ ${t} = ${P} W`, `power = ${W} ÷ ${t} = ${P} W`); }
    const m = ri(2, 10), h = ri(2, 6), w = m * 10 * h; return Q(`${m} kg வாளி நீரை கிணற்றிலிருந்து ${h} m மேலே தூக்கினால் செய்த வேலை? (g = 10)`, `Lifting a ${m} kg bucket of water ${h} m. Work done? (g = 10)`, '<div style="font-size:38px">🪣⬆️</div>', w, [m * h, w * 2, w + 10, w / 2], 'J', `விசை = ${m} × 10 = ${m * 10} N; வேலை = ${m * 10} × ${h} = ${w} J`, `force = ${m} × 10 = ${m * 10} N; work = ${m * 10} × ${h} = ${w} J`); } };

/* ================= CHEMISTRY ================= */
const EL = [['H','ஹைட்ரஜன்','Hydrogen',1,1],['He','ஹீலியம்','Helium',2,4],['Li','லித்தியம்','Lithium',3,7],['Be','பெரிலியம்','Beryllium',4,9],['B','போரான்','Boron',5,11],['C','கார்பன்','Carbon',6,12],['N','நைட்ரஜன்','Nitrogen',7,14],['O','ஆக்சிஜன்','Oxygen',8,16],['F','ஃப்ளூரின்','Fluorine',9,19],['Ne','நியான்','Neon',10,20],['Na','சோடியம்','Sodium',11,23],['Mg','மெக்னீசியம்','Magnesium',12,24],['Al','அலுமினியம்','Aluminium',13,27],['Si','சிலிக்கான்','Silicon',14,28],['P','பாஸ்பரஸ்','Phosphorus',15,31],['S','கந்தகம்','Sulphur',16,32],['Cl','குளோரின்','Chlorine',17,35],['Ar','ஆர்கான்','Argon',18,40],['K','பொட்டாசியம்','Potassium',19,39],['Ca','கால்சியம்','Calcium',20,40]];
const ION = [['Na',1],['K',1],['Li',1],['Mg',2],['Ca',2],['Al',3],['Cl',-1],['F',-1],['O',-2],['S',-2]];
X.atomBuilder = { title:S('அணுவைக் கட்டு — p, n, e', 'Build the atom — p, n, e'), icon:'⚛️',
  intro:S('அணு எண் (Z) = புரோட்டான்கள் = தனிமத்தின் அடையாளம். நிறை எண் (A) = புரோட்டான் + நியூட்ரான். நியூட்ரான் = A − Z. நடுநிலை அணுவில் எலக்ட்ரான் = புரோட்டான். எலக்ட்ரானை இழந்தால் நேர் அயனி (+), பெற்றால் எதிர் அயனி (−).',
          'Atomic number (Z) = protons = the element\'s identity. Mass number (A) = protons + neutrons. Neutrons = A − Z. A neutral atom has electrons = protons. Lose electrons → positive ion (+); gain → negative ion (−).'),
  gen(){ const k = ri(0, 4), e = pick(EL);
    if(k === 0) return Q(`${e[1]} (${e[0]}) — Z = ${e[3]}, A = ${e[4]}. நியூட்ரான்கள்?`, `${e[2]} (${e[0]}): Z = ${e[3]}, A = ${e[4]}. How many neutrons?`, '', e[4] - e[3], [e[4], e[3], e[4] + e[3], e[4] - e[3] + 1], '', `நியூட்ரான் = A − Z = ${e[4]} − ${e[3]} = ${e[4] - e[3]}`, `neutrons = A − Z = ${e[4]} − ${e[3]} = ${e[4] - e[3]}`);
    if(k === 1) return Q(`நடுநிலை ${e[1]} (${e[0]}) அணுவில் (Z = ${e[3]}) எலக்ட்ரான்கள்?`, `How many electrons in a neutral ${e[2]} (${e[0]}) atom (Z = ${e[3]})?`, '', e[3], [e[4], e[3] + 1, e[3] - 1, e[4] - e[3]], '', `நடுநிலை அணு: எலக்ட்ரான் = புரோட்டான் = ${e[3]}`, `Neutral atom: electrons = protons = ${e[3]}`);
    if(k === 2){ const o = pick(EL.filter(x => x !== e)); return C(`${e[3]} புரோட்டான்கள் உள்ள அணு எது?`, `Which atom has ${e[3]} protons?`, '', e[0], shuffle(EL.filter(x => x[3] !== e[3])).slice(0, 3).map(x => x[0]).concat([e[0]]), `புரோட்டான் எண் = Z; Z = ${e[3]} → ${e[1]} (${e[0]})`, `Proton number Z = ${e[3]} → ${e[2]} (${e[0]})`); }
    if(k === 3){ const io = pick(ION), el = EL.find(x => x[0] === io[0]), n = el[3] - io[1], sg = io[1] > 0 ? '+'.repeat(1) : '−'; return Q(`${el[0]}${Math.abs(io[1]) > 1 ? Math.abs(io[1]) : ''}${sg} அயனியில் (Z = ${el[3]}) எலக்ட்ரான்கள்?`, `How many electrons in the ion ${el[0]}${Math.abs(io[1]) > 1 ? Math.abs(io[1]) : ''}${sg} (Z = ${el[3]})?`, '', n, [el[3], n + 1, n - 1, el[3] + Math.abs(io[1]) * 2], '', `எலக்ட்ரான் = Z − மின்னூட்டம் = ${el[3]} − (${io[1]}) = ${n}`, `electrons = Z − charge = ${el[3]} − (${io[1]}) = ${n}`); }
    const p = e[3], el = ri(Math.max(0, p - 2), p + 2), ch = p - el; return C(`${p} புரோட்டான், ${el} எலக்ட்ரான் உள்ள துகள்?`, `A particle has ${p} protons and ${el} electrons. It is a…`, '', ch === 0 ? 'neutral' : (ch > 0 ? 'positive' : 'negative'), ['neutral', 'positive', 'negative'], `மின்னூட்டம் = ${p} − ${el} = ${ch}`, `charge = ${p} − ${el} = ${ch}`, {neutral:'நடுநிலை அணு / neutral atom', positive:'நேர் அயனி / positive ion', negative:'எதிர் அயனி / negative ion'}); } };

const FM = [['H₂O',{H:2,O:1}],['CO₂',{C:1,O:2}],['NH₃',{N:1,H:3}],['CH₄',{C:1,H:4}],['H₂SO₄',{H:2,S:1,O:4}],['NaCl',{Na:1,Cl:1}],['CaCO₃',{Ca:1,C:1,O:3}],['NaOH',{Na:1,O:1,H:1}],['HCl',{H:1,Cl:1}],['Mg(OH)₂',{Mg:1,O:2,H:2}],['C₆H₁₂O₆',{C:6,H:12,O:6}],['Al₂O₃',{Al:2,O:3}],['MgCl₂',{Mg:1,Cl:2}],['HNO₃',{H:1,N:1,O:3}],['NaHCO₃',{Na:1,H:1,C:1,O:3}],['CaO',{Ca:1,O:1}]];
const MASS = {H:1,C:12,N:14,O:16,Na:23,Mg:24,Al:27,S:32,Cl:35.5,Ca:40};
const SUBN = '₀₁₂₃₄₅₆₇₈₉';
X.atomCount = { title:S('சூத்திரத்தில் அணுக்களை எண்ணு', 'Count atoms in a formula'), icon:'🔬',
  intro:S('சூத்திரத்தில் சிறிய கீழ் எண் = அந்த அணுவின் எண்ணிக்கை (H₂O → 2 H, 1 O). முன்னால் உள்ள பெரிய எண் = மூலக்கூறுகளின் எண்ணிக்கை (3 H₂O → 3 நீர் மூலக்கூறு). அணுக்கள் = முன் எண் × கீழ் எண். வேதிச் சமன்பாடு சமப்படுத்த இதுவே முதல் படி.',
          'A small subscript is the number of that atom (H₂O → 2 H, 1 O). The big number in front is the number of molecules (3 H₂O → 3 water molecules). Atoms = front number × subscript. This is step one of balancing equations.'),
  gen(){ const f = pick(FM), c = ri(1, 5), els = Object.keys(f[1]), k = ri(0, 1);
    if(k === 0){ const el = pick(els), n = c * f[1][el]; return Q(`${c > 1 ? c : ''}${f[0]} — மொத்தம் எத்தனை ${el} அணுக்கள்?`, `${c > 1 ? c : ''}${f[0]} — how many ${el} atoms in total?`, '', n, [c, f[1][el], n + 1, n * 2], '', `${c} × ${f[1][el]} = ${n}`, `${c} × ${f[1][el]} = ${n}`); }
    const tot = els.reduce((a, e) => a + f[1][e], 0) * c; return Q(`${c > 1 ? c : ''}${f[0]} — மொத்தம் எத்தனை அணுக்கள் (எல்லாத் தனிமமும் சேர்த்து)?`, `${c > 1 ? c : ''}${f[0]} — how many atoms in total (all elements together)?`, '', tot, [els.length * c, tot + 1, tot - 1, tot * 2], '', `ஒரு மூலக்கூறில் ${els.map(e => e + f[1][e]).join(' + ')} = ${tot / c}; × ${c} = ${tot}`, `One molecule: ${els.map(e => e + f[1][e]).join(' + ')} = ${tot / c}; × ${c} = ${tot}`); } };

X.moleCalc = { title:S('மோல் & மூலக்கூறு நிறை', 'Moles & molar mass'), icon:'⚖️',
  intro:S('மூலக்கூறு நிறை = சூத்திரத்தில் உள்ள எல்லா அணுக்களின் அணு நிறையின் கூட்டுத்தொகை (H = 1, C = 12, N = 14, O = 16, Na = 23, Mg = 24, Al = 27, S = 32, Cl = 35.5, Ca = 40). 1 மோல் = அந்த நிறை கிராமில். மோல் = நிறை (g) ÷ மூலக்கூறு நிறை. மருந்து, உரத் தொழிற்சாலை இதை வைத்துத்தான் அளவு கணக்கிடுகின்றன.',
          'Molar mass = sum of atomic masses of all atoms in the formula (H = 1, C = 12, N = 14, O = 16, Na = 23, Mg = 24, Al = 27, S = 32, Cl = 35.5, Ca = 40). 1 mole = that mass in grams. Moles = mass (g) ÷ molar mass. Medicine and fertiliser factories size their batches this way.'),
  gen(){ const f = pick(FM), M = Object.keys(f[1]).reduce((a, e) => a + MASS[e] * f[1][e], 0), k = ri(0, 2);
    if(k === 0) return Q(`${f[0]}-ன் மூலக்கூறு நிறை? (${Object.keys(f[1]).map(e => `${e} = ${MASS[e]}`).join(', ')})`, `Molar mass of ${f[0]}? (${Object.keys(f[1]).map(e => `${e} = ${MASS[e]}`).join(', ')})`, '', M, [M + 2, M - 2, M * 2, M + 10], 'g/mol', `${Object.keys(f[1]).map(e => `${f[1][e]}×${MASS[e]}`).join(' + ')} = ${n2(M)}`, `${Object.keys(f[1]).map(e => `${f[1][e]}×${MASS[e]}`).join(' + ')} = ${n2(M)}`);
    const mol = pick([0.5, 1, 2, 3, 4]), g = M * mol;
    if(k === 1) return Q(`${n2(g)} g ${f[0]}-ல் எத்தனை மோல்? (மூலக்கூறு நிறை = ${n2(M)} g/mol)`, `How many moles in ${n2(g)} g of ${f[0]}? (molar mass = ${n2(M)} g/mol)`, '', mol, [mol * 2, mol + 1, Math.max(0.25, mol / 2), g / 10], 'mol', `மோல் = ${n2(g)} ÷ ${n2(M)} = ${n2(mol)}`, `moles = ${n2(g)} ÷ ${n2(M)} = ${n2(mol)}`);
    return Q(`${n2(mol)} மோல் ${f[0]}-ன் நிறை? (மூலக்கூறு நிறை = ${n2(M)} g/mol)`, `Mass of ${n2(mol)} mol of ${f[0]}? (molar mass = ${n2(M)} g/mol)`, '', g, [M, g + M, g / 2, g * 2], 'g', `நிறை = ${n2(mol)} × ${n2(M)} = ${n2(g)} g`, `mass = ${n2(mol)} × ${n2(M)} = ${n2(g)} g`); } };

const SUBS = [['எலுமிச்சை சாறு','lemon juice',2],['வினிகர்','vinegar',3],['தக்காளி','tomato',4.5],['கருப்புக் காபி','black coffee',5],['மழைநீர்','rain water',5.6],['பால்','milk',6.5],['தூய நீர்','pure water',7],['இரத்தம்','blood',7.4],['கடல் நீர்','sea water',8],['சமையல் சோடா','baking soda',8.3],['பற்பசை','toothpaste',9],['சோப்பு','soap',10],['மெக்னீசியா பால் (ஆன்டாசிட்)','milk of magnesia (antacid)',10.5],['ப்ளீச்','bleach',12.5]];
X.phLife = { title:S('pH — அமிலமா, காரமா?', 'pH — acid or base?'), icon:'🧪',
  intro:S('pH 0–14: 7-க்குக் கீழே அமிலம், 7 நடுநிலை, 7-க்கு மேலே காரம். எண் குறைந்தால் அமிலம் வலிமை. ஒவ்வொரு 1 pH வேறுபாடும் 10 மடங்கு! pH 3 அமிலம், pH 5 அமிலத்தைவிட 100 மடங்கு வலிமை. ஆன்டாசிட் (காரம்) வயிற்று அமிலத்தை நடுநிலையாக்குகிறது.',
          'pH 0–14: below 7 acid, 7 neutral, above 7 base. Lower number = stronger acid. Every 1 pH step is 10×! pH 3 is 100× stronger than pH 5. An antacid (a base) neutralises stomach acid.'),
  gen(){ const k = ri(0, 2);
    if(k === 0){ const s = pick(SUBS), ty = s[2] < 7 ? 'acid' : (s[2] === 7 ? 'neutral' : 'base'); return C(`${s[0]}-ன் pH ≈ ${s[2]}. இது?`, `${s[1]} has pH ≈ ${s[2]}. It is…`, '', ty, ['acid', 'neutral', 'base'], `pH ${s[2]} ${s[2] < 7 ? '< 7 → அமிலம்' : (s[2] === 7 ? '= 7 → நடுநிலை' : '> 7 → காரம்')}`, `pH ${s[2]} is ${s[2] < 7 ? 'below 7 → acid' : (s[2] === 7 ? '7 → neutral' : 'above 7 → base')}`, {acid:'அமிலம் / acid', neutral:'நடுநிலை / neutral', base:'காரம் / base'}); }
    if(k === 1){ const a = ri(1, 6), d = ri(1, 3), b = a + d; return Q(`pH ${a} கரைசல் pH ${b} கரைசலைவிட எத்தனை மடங்கு அமிலத்தன்மை வாய்ந்தது?`, `A solution of pH ${a} is how many times more acidic than one of pH ${b}?`, '', Math.pow(10, d), [d, d * 10, Math.pow(10, d + 1), 10 * (d + 1)], '×', `வேறுபாடு ${d} pH → 10^${d} = ${Math.pow(10, d)} மடங்கு`, `Difference of ${d} pH → 10^${d} = ${Math.pow(10, d)} times`); }
    const three = shuffle(SUBS.filter(s => s[2] < 7)).slice(0, 3), strongest = three.reduce((a, b) => b[2] < a[2] ? b : a); if(new Set(three.map(x => x[2])).size < 3) return X.phLife.gen();
    return {p:S('இவற்றில் எது வலிமையான அமிலம்?', 'Which is the strongest acid here?'), scene:'', opts:shuffle(three.map(s => ({v:s[1], h:`${s[0]} (pH ${s[2]}) / ${s[1]}`}))), ans:strongest[1], ex:S(`pH குறைவு = அமிலம் வலிமை: ${strongest[0]} (pH ${strongest[2]})`, `Lowest pH = strongest acid: ${strongest[1]} (pH ${strongest[2]})`)}; } };

const EQN = [
 {t:['2H₂ + O₂ → 2H₂O',[2,1,2]], sp:['H₂','O₂','H₂O']}, {t:['N₂ + 3H₂ → 2NH₃',[1,3,2]], sp:['N₂','H₂','NH₃']}, {t:['CH₄ + 2O₂ → CO₂ + 2H₂O',[1,2,1,2]], sp:['CH₄','O₂','CO₂','H₂O']},
 {t:['4Fe + 3O₂ → 2Fe₂O₃',[4,3,2]], sp:['Fe','O₂','Fe₂O₃']}, {t:['2Mg + O₂ → 2MgO',[2,1,2]], sp:['Mg','O₂','MgO']}, {t:['C₃H₈ + 5O₂ → 3CO₂ + 4H₂O',[1,5,3,4]], sp:['C₃H₈','O₂','CO₂','H₂O']},
 {t:['2Na + Cl₂ → 2NaCl',[2,1,2]], sp:['Na','Cl₂','NaCl']}, {t:['4Al + 3O₂ → 2Al₂O₃',[4,3,2]], sp:['Al','O₂','Al₂O₃']}, {t:['2KClO₃ → 2KCl + 3O₂',[2,2,3]], sp:['KClO₃','KCl','O₂']},
 {t:['H₂ + Cl₂ → 2HCl',[1,1,2]], sp:['H₂','Cl₂','HCl']}, {t:['Zn + 2HCl → ZnCl₂ + H₂',[1,2,1,1]], sp:['Zn','HCl','ZnCl₂','H₂']}, {t:['2H₂O → 2H₂ + O₂',[2,2,1]], sp:['H₂O','H₂','O₂']}];
EQN.forEach(q => { const [l, r] = q.t[0].split(' → '); q.nre = l.split(' + ').length; });
X.balanceFill = { title:S('வேதிச் சமன்பாடு — விடுபட்ட எண்', 'Chemical equation — missing number'), icon:'⚗️',
  intro:S('வினைக்கு முன்னும் பின்னும் ஒவ்வொரு தனிமத்தின் அணுக்கள் சமமாக இருக்க வேண்டும் (நிறை அழியாமை). முன்னால் உள்ள எண்ணை (கெழு) மட்டுமே மாற்றலாம்; சூத்திரத்தை மாற்றக் கூடாது. கெழுக்கள் விகிதத்தையும் சொல்கின்றன: 2H₂ + O₂ → 2H₂O என்றால் 2 H₂ : 1 O₂ : 2 H₂O.',
          'Atoms of every element must be equal before and after (conservation of mass). Change only the numbers in front (coefficients), never the formulas. Coefficients also give the ratio: 2H₂ + O₂ → 2H₂O means 2 H₂ : 1 O₂ : 2 H₂O.'),
  gen(){ const e = pick(EQN), co = e.t[1], k = ri(0, 1);
    if(k === 0){ const miss = ri(0, co.length - 1), show = e.t[0].replace(/(^|\+ |→ )(\d+)?(?=[A-Z])/g, (m, a, b) => m); const parts = e.t[0].split(/ \+ | → /); const label = parts.map((s, i) => { const f = s.replace(/^\d+/, ''); return `${i === miss ? '□' : (co[i] > 1 ? co[i] : '')}${f}`; }); const eq = label.slice(0, e.nre).join(' + ') + ' → ' + label.slice(e.nre).join(' + ');
      return Q(`சமன்பாட்டைச் சமப்படுத்த □-ல் வரவேண்டிய எண்: ${eq}`, `Balance it — the number that goes in □: ${eq}`, '', co[miss], [co[miss] + 1, Math.max(1, co[miss] - 1), co[miss] * 2, 6], '', `இரு பக்கமும் அணுக்கள் சமமாக: ${e.t[0]} → □ = ${co[miss]}`, `For equal atoms on both sides: ${e.t[0]} → □ = ${co[miss]}`); }
    const r = ri(0, e.nre - 1), p = ri(e.nre, co.length - 1), n = pick([2, 4, 6, 10, 20]), num = n * co[p]; if(num % co[r] !== 0) return X.balanceFill.gen(); const ans = num / co[r];
    return Q(`${e.t[0]}\n${n} மூலக்கூறு ${e.sp[p]} உருவாக ${e.sp[r]} எத்தனை மூலக்கூறு தேவை?`.replace('\n', ' — '), `${e.t[0]} — how many ${e.sp[r]} molecules are needed to make ${n} molecules of ${e.sp[p]}?`.replace('\n', ' — '), '', ans * co[p] / co[p] === ans && (n * co[r]) / co[p] === (n * co[r]) / co[p] ? (n * co[r]) / co[p] : 0, [n, n * 2, n + co[r], co[r]], '', `விகிதம் ${co[r]} : ${co[p]}; ${n} × ${co[r]} ÷ ${co[p]} = ${(n * co[r]) / co[p]}`, `Ratio ${co[r]} : ${co[p]}; ${n} × ${co[r]} ÷ ${co[p]} = ${(n * co[r]) / co[p]}`); } };

const SEP = [['மணலும் நீரும் கலந்தது','sand mixed in water','filtration'],['உப்பு நீரிலிருந்து உப்பு','salt from salt water','evaporation'],['சேறு நீர் தெளிய வைத்தல்','letting muddy water settle','sedimentation'],['இரும்புத் துகள் + மணல்','iron filings + sand','magnet'],['பாலிலிருந்து கிரீம்','cream from milk','centrifuge'],['மையின் நிறங்களைப் பிரித்தல்','splitting the colours of ink','chromatography'],['கடல் நீரிலிருந்து குடிநீர்','drinking water from sea water','distillation'],['நெல் + உமி (காற்றில்)','grain + husk (using wind)','winnowing'],['எண்ணெய் + நீர்','oil + water','funnel'],['கற்பூரம் + உப்பு','camphor + salt','sublimation'],['மாவிலிருந்து கட்டிகளை நீக்குதல்','removing lumps from flour','sieving'],['அரிசியிலிருந்து கற்கள்','stones from rice','handpick']];
const SEPN = {filtration:['வடிகட்டுதல்','filtration'],evaporation:['ஆவியாக்குதல்','evaporation'],sedimentation:['படிய வைத்தல்','sedimentation & decanting'],magnet:['காந்தத்தால் பிரித்தல்','magnetic separation'],centrifuge:['மையவிலக்கு','centrifugation'],chromatography:['நிறப்பிரிகை','chromatography'],distillation:['காய்ச்சி வடித்தல்','distillation'],winnowing:['தூற்றுதல்','winnowing'],funnel:['பிரிப்பு புனல்','separating funnel'],sublimation:['பதங்கமாதல்','sublimation'],sieving:['சலித்தல்','sieving'],handpick:['கையால் பொறுக்குதல்','hand-picking']};
X.separateMix = { title:S('கலவையைப் பிரிப்பது எப்படி?', 'How to separate a mixture?'), icon:'🥣',
  intro:S('கலவையின் பகுதிகளுக்கு இடையே உள்ள வேறுபாடு (அளவு, எடை, காந்தம், கரைதல், கொதிநிலை) எந்த முறை என்பதைத் தீர்மானிக்கும். மணல் கரையாது → வடிகட்டு. உப்பு கரையும் → ஆவியாக்கு. இரும்பு காந்தத்தால் இழுக்கப்படும் → காந்தம். நெல்லையும் உமியையும் எடை வேறு → தூற்று.',
          'The way to separate depends on a difference between the parts (size, weight, magnetism, solubility, boiling point). Sand doesn\'t dissolve → filter. Salt dissolves → evaporate. Iron is magnetic → magnet. Grain and husk differ in weight → winnow.'),
  gen(){ const s = pick(SEP), others = shuffle(Object.keys(SEPN).filter(k => k !== s[2])).slice(0, 3);
    return {p:S(`${s[0]} — எந்த முறையில் பிரிக்கலாம்?`, `${s[1]} — which method separates it?`), scene:'', opts:shuffle([s[2]].concat(others).map(k => ({v:k, h:`${SEPN[k][0]} / ${SEPN[k][1]}`}))), ans:s[2], ex:S(`${s[0]} → ${SEPN[s[2]][0]}`, `${s[1]} → ${SEPN[s[2]][1]}`)}; } };

/* ================= BIOLOGY ================= */
const CHAINS = [['புல்','grass','🌾'],['வெட்டுக்கிளி','grasshopper','🦗'],['தவளை','frog','🐸'],['பாம்பு','snake','🐍'],['கழுகு','eagle','🦅']];
const CH2 = [['நெற்பயிர்','paddy','🌾'],['எலி','rat','🐀'],['பாம்பு','snake','🐍'],['கழுகு','eagle','🦅']];
const CH3 = [['பாசி','algae','🟢'],['சிறு மீன்','small fish','🐟'],['பெரிய மீன்','big fish','🐠'],['கொக்கு','heron','🦢']];
const CH4 = [['இலை','leaf','🍃'],['கம்பளிப்புழு','caterpillar','🐛'],['சிட்டுக்குருவி','sparrow','🐦'],['பருந்து','hawk','🦅']];
const CHAINLIST = [CHAINS, CH2, CH3, CH4];
const LV = [['உற்பத்தியாளர் (producer)','producer'],['முதல்நிலை நுகர்வோர்','primary consumer'],['இரண்டாம்நிலை நுகர்வோர்','secondary consumer'],['மூன்றாம்நிலை நுகர்வோர்','tertiary consumer'],['நான்காம்நிலை நுகர்வோர்','quaternary consumer']];
X.foodWeb = { title:S('உணவுச் சங்கிலி & ஆற்றல்', 'Food chains & energy'), icon:'🦅',
  intro:S('உணவுச் சங்கிலி: சூரிய ஆற்றலை தாவரம் (உற்பத்தியாளர்) பிடிக்கிறது → தாவர உண்ணி → மாமிச உண்ணி. அம்பு "உண்ணப்படுகிறது → உண்பவர்" திசை. ஒவ்வொரு படியிலும் ஆற்றலில் ≈ 10% மட்டுமே அடுத்த நிலைக்குப் போகும் (10% விதி); மீதி வெப்பமாகவும் கழிவாகவும் போகிறது. அதனால்தான் சங்கிலி நீளமாக இருக்காது.',
          'In a food chain a plant (producer) captures sunlight → herbivore → carnivore. Arrows show "is eaten by". Only ≈ 10% of energy passes to the next level (10% rule); the rest is lost as heat and waste. That is why chains are short.'),
  gen(){ const ch = pick(CHAINLIST), k = ri(0, 3), line = ch.map(x => x[2] + ' ' + x[0]).join(' → '), lineEn = ch.map(x => x[2] + ' ' + x[1]).join(' → ');
    if(k === 0){ const i = ri(0, ch.length - 1); return {p:S(`${line}. ${ch[i][0]} எந்த நிலை?`, `${lineEn}. What level is the ${ch[i][1]}?`), scene:'', opts:opts(LV[i][1], LV.slice(0, Math.max(4, ch.length)).map(x => x[1]).filter(x => x !== LV[i][1]), v => { const L = LV.find(x => x[1] === v); return `${L[0]} / ${v}`; }, 4), ans:LV[i][1], ex:S(`சங்கிலியின் ${i + 1}-வது இடம் → ${LV[i][0]}`, `Position ${i + 1} in the chain → ${LV[i][1]}`)}; }
    if(k === 1){ const i = ri(1, ch.length - 2); return C(`${line}. ${ch[i][0]} இல்லாமல் போனால் ${ch[i - 1][0]}-ன் எண்ணிக்கை?`, `${lineEn}. If the ${ch[i][1]} disappears, the ${ch[i - 1][1]} population will…`, '', 'up', ['up', 'down', 'same'], `${ch[i - 1][0]}-ஐ உண்பவர் இல்லை → அது பெருகும் (ஆனால் பின்னர் உணவு குறைந்து சிக்கல்)`, `Nothing eats the ${ch[i - 1][1]} → it increases (then food runs short)`, {up:'கூடும் / increases', down:'குறையும் / decreases', same:'மாறாது / stays same'}); }
    if(k === 2){ const i = ri(1, ch.length - 2); return C(`${line}. ${ch[i - 1][0]} எண்ணிக்கை திடீரெனக் குறைந்தால் ${ch[i][0]}-ன் எண்ணிக்கை?`, `${lineEn}. If the ${ch[i - 1][1]} suddenly decreases, the ${ch[i][1]} will…`, '', 'down', ['up', 'down', 'same'], `${ch[i][0]}-க்கு உணவு குறைகிறது → அது குறையும்`, `The ${ch[i][1]} loses its food → it decreases`, {up:'கூடும் / increases', down:'குறையும் / decreases', same:'மாறாது / stays same'}); }
    const E0 = pick([1000, 2000, 5000, 10000, 20000]), lv = ri(2, 4), E = E0 / Math.pow(10, lv - 1);
    return Q(`புல்/தாவரத்தில் ${fmt(E0)} kJ ஆற்றல் உள்ளது. 10% விதிப்படி ${lv}-வது நிலை உயிரிக்கு (தாவரம் = 1-வது நிலை) கிடைக்கும் ஆற்றல்?`, `Producers hold ${fmt(E0)} kJ. By the 10% rule, how much reaches trophic level ${lv} (producer = level 1)?`, '', E, [E * 10, E / 10, E0 / 2, E0 * 0.9], 'kJ', `ஒவ்வொரு படியிலும் ×0.1: ${fmt(E0)} × 0.1^${lv - 1} = ${n2(E)} kJ`, `×0.1 at each step: ${fmt(E0)} × 0.1^${lv - 1} = ${n2(E)} kJ`); } };

const TRAITS = [['உயரம்','height','T','உயரமான','tall','குள்ளமான','short'],['விதை வடிவம்','seed shape','R','உருண்டை','round','சுருக்கம்','wrinkled'],['பூ நிறம்','flower colour','P','ஊதா','purple','வெள்ளை','white'],['விதை நிறம்','seed colour','Y','மஞ்சள்','yellow','பச்சை','green']];
function cross(a, b){ const kids = []; for(const x of a) for(const y of b) kids.push(x + y); return kids; }
X.traitCross = { title:S('மரபு — குறுக்கு இனப்பெருக்கம்', 'Heredity — crosses'), icon:'🧬',
  intro:S('மெண்டல்: ஒவ்வொரு பண்புக்கும் இரு மரபணுக்கள் (தாய், தந்தை). பெரிய எழுத்து = ஓங்கு (dominant), சிறிய எழுத்து = ஒடுங்கு (recessive). Tt இல் T ஓங்குவதால் உயரமாகத் தெரியும். இரு பெற்றோரின் கேமீட்டுகளை இணைத்துச் சதுரம் போட்டால் குழந்தைகளின் வாய்ப்பு தெரியும் (Punnett).',
          'Mendel: each trait has two genes (one from each parent). Capital = dominant, small = recessive. In Tt, T dominates so the plant looks tall. Combine the parents\' gametes in a Punnett square to see the chances for offspring.'),
  gen(){ const tr = pick(TRAITS), A = tr[2], a = A.toLowerCase(), pars = pick([[A + A, A + A], [A + A, A + a], [A + A, a + a], [A + a, A + a], [A + a, a + a], [a + a, a + a]]), kids = cross(pars[0], pars[1]), dom = kids.filter(g => g.includes(A)).length, k = ri(0, 1);
    const frac = n => ({0:'0%',1:'25%',2:'50%',3:'75%',4:'100%'})[n];
    if(k === 0) return C(`${tr[1]} பண்பு (${A} = ${tr[3]}, ${a} = ${tr[5]}). ${pars[0]} × ${pars[1]} குறுக்கில் ${tr[3]} தோற்றம் உள்ள சந்ததி எத்தனை சதவீதம்?`, `Trait: ${tr[1]} (${A} = ${tr[4]}, ${a} = ${tr[6]}). In the cross ${pars[0]} × ${pars[1]}, what percent of offspring show the ${tr[4]} trait?`, '', frac(dom), ['0%', '25%', '50%', '75%', '100%'], `சந்ததிகள்: ${kids.join(', ')} → ${A} உள்ளவை ${dom}/4 = ${frac(dom)}`, `Offspring: ${kids.join(', ')} → with ${A}: ${dom}/4 = ${frac(dom)}`);
    const rec = 4 - dom; return C(`${tr[1]}: ${pars[0]} × ${pars[1]}. ${tr[5]} (${a}${a}) சந்ததி எத்தனை சதவீதம்?`, `${tr[1]}: ${pars[0]} × ${pars[1]}. What percent of offspring are ${tr[6]} (${a}${a})?`, '', frac(rec), ['0%', '25%', '50%', '75%', '100%'], `சந்ததிகள்: ${kids.join(', ')} → ${a}${a} = ${rec}/4 = ${frac(rec)}`, `Offspring: ${kids.join(', ')} → ${a}${a} = ${rec}/4 = ${frac(rec)}`); } };

X.heartRate = { title:S('இதயம் & சுவாசம் — எண்களில்', 'Heartbeat & breathing in numbers'), icon:'❤️',
  intro:S('நம் இதயம் ஓய்வில் நிமிடத்துக்கு சுமார் 60–100 முறை துடிக்கும்; சுவாசம் 12–20 முறை. ஒரு நிமிடக் கணக்கை நேரத்தால் பெருக்கினால் எந்த நேரத்துக்கும் எண்ணிக்கை கிடைக்கும். ஒரு துடிப்பில் இதயம் சுமார் 70 mL இரத்தம் பம்ப் செய்கிறது. உன் நாடித் துடிப்பை 15 வினாடி எண்ணி ×4 செய்து பார்!',
          'At rest the heart beats about 60–100 times a minute and we breathe 12–20 times. Multiply the per-minute rate by the time to get any total. Each beat pumps about 70 mL of blood. Count your own pulse for 15 s and ×4!'),
  gen(){ const k = ri(0, 2);
    if(k === 0){ const r = pick([60, 64, 68, 72, 76, 80, 84, 90]), m = pick([5, 10, 30, 60]); return Q(`நிமிடத்துக்கு ${r} துடிப்பு. ${m} நிமிடத்தில் எத்தனை துடிப்பு?`, `A heart beats ${r} times a minute. How many beats in ${m} minutes?`, '<div style="font-size:38px">❤️</div>', r * m, [r + m, r * m + r, r * m / 2, r * 24], 'beats', `${r} × ${m} = ${fmt(r * m)}`, `${r} × ${m} = ${fmt(r * m)}`); }
    if(k === 1){ const r = pick([60, 70, 72, 75, 80]), d = r * 60 * 24; return Q(`நிமிடத்துக்கு ${r} துடிப்பு எனில் ஒரு நாளில் (24 மணி) இதயம் எத்தனை முறை துடிக்கும்?`, `At ${r} beats a minute, how many beats in one day (24 h)?`, '<div style="font-size:38px">❤️</div>', d, [r * 60, r * 24, d / 10, d * 2], 'beats', `${r} × 60 × 24 = ${fmt(d)}`, `${r} × 60 × 24 = ${fmt(d)}`); }
    const r = pick([60, 72, 80]), L = r * 70 / 1000; return Q(`ஒரு துடிப்பில் 70 mL இரத்தம். நிமிடத்துக்கு ${r} துடிப்பு. ஒரு நிமிடத்தில் பம்ப் ஆகும் இரத்தம் (லிட்டர்)?`, `70 mL per beat, ${r} beats a minute. Blood pumped per minute (litres)?`, '<div style="font-size:38px">🩸</div>', L, [r * 70, L * 10, L / 10, L + 1], 'L', `${r} × 70 = ${r * 70} mL = ${n2(L)} L`, `${r} × 70 = ${r * 70} mL = ${n2(L)} L`); } };

X.microMagnify = { title:S('நுண்ணோக்கி — எவ்வளவு பெரிதாகும்?', 'Microscope — how much bigger?'), icon:'🔬',
  intro:S('மொத்தப் பெருக்கம் = கண்ணருகு லென்ஸ் × பொருளருகு லென்ஸ். 10× கண்ணருகு, 40× பொருளருகு → 400×. 0.02 mm செல் 400× ஆகப் பார்த்தால் 8 mm அளவு தெரியும். இப்படித்தான் ராபர்ட் ஹூக் செல்லைக் கண்டார்!',
          'Total magnification = eyepiece × objective. 10× eyepiece with a 40× objective gives 400×. A 0.02 mm cell seen at 400× appears 8 mm wide. This is how Robert Hooke first saw cells!'),
  gen(){ const e = pick([5, 10, 15]), o = pick([4, 10, 40, 100]), M = e * o, k = ri(0, 2);
    if(k === 0) return Q(`கண்ணருகு லென்ஸ் ${e}×, பொருளருகு லென்ஸ் ${o}×. மொத்தப் பெருக்கம்?`, `Eyepiece ${e}×, objective ${o}×. Total magnification?`, '<div style="font-size:38px">🔬</div>', M, [e + o, M * 2, M / 2, M + 10], '×', `${e} × ${o} = ${M}×`, `${e} × ${o} = ${M}×`);
    if(k === 1) return Q(`மொத்தப் பெருக்கம் ${M}×; கண்ணருகு லென்ஸ் ${e}×. பொருளருகு லென்ஸ் எத்தனை ×?`, `Total magnification ${M}×, eyepiece ${e}×. What is the objective?`, '<div style="font-size:38px">🔬</div>', o, [M - e, M * e, o * 2, e], '×', `${M} ÷ ${e} = ${o}×`, `${M} ÷ ${e} = ${o}×`);
    const sz = pick([0.01, 0.02, 0.05]), im = sz * M; return Q(`${sz} mm செல் ${M}× பெருக்கத்தில் எவ்வளவு அளவு தெரியும்?`, `A ${sz} mm cell viewed at ${M}× looks how big?`, '<div style="font-size:38px">🦠</div>', +im.toFixed(3), [sz + M, im * 10, im / 10, +(im * 2).toFixed(3)], 'mm', `${sz} × ${M} = ${n2(im)} mm`, `${sz} × ${M} = ${n2(im)} mm`); } };

X.mealEnergy = { title:S('உணவின் ஆற்றல் — kcal கணக்கு', 'Energy in food — kcal maths'), icon:'🍛',
  intro:S('1 g மாவுச்சத்து ≈ 4 kcal, 1 g புரதம் ≈ 4 kcal, 1 g கொழுப்பு ≈ 9 kcal. கொழுப்பு இரு மடங்குக்கு மேல் ஆற்றல் தருவதால் நெய், எண்ணெய் அளவோடு சாப்பிட வேண்டும். உணவு லேபிளில் உள்ள கிராம் எண்களை வைத்து நீயே கலோரியைக் கணக்கிடலாம்.',
          '1 g carbohydrate ≈ 4 kcal, 1 g protein ≈ 4 kcal, 1 g fat ≈ 9 kcal. Fat gives more than twice the energy, so ghee and oil belong in small amounts. You can work out calories yourself from the grams on a food label.'),
  gen(){ const k = ri(0, 1);
    if(k === 0){ const c = pick([10, 20, 30, 40, 50, 60, 80]), p = pick([0, 5, 10, 15, 20]), f = pick([0, 5, 10, 15, 20]), E = c * 4 + p * 4 + f * 9; return Q(`ஒரு உணவில் மாவுச்சத்து ${c} g, புரதம் ${p} g, கொழுப்பு ${f} g. மொத்த ஆற்றல்? (4, 4, 9 kcal/g)`, `A meal has ${c} g carbohydrate, ${p} g protein, ${f} g fat. Total energy? (4, 4, 9 kcal/g)`, '<div style="font-size:38px">🍛</div>', E, [(c + p + f) * 4, (c + p + f) * 9, E + 36, E - 20], 'kcal', `${c}×4 + ${p}×4 + ${f}×9 = ${c * 4} + ${p * 4} + ${f * 9} = ${E} kcal`, `${c}×4 + ${p}×4 + ${f}×9 = ${c * 4} + ${p * 4} + ${f * 9} = ${E} kcal`); }
    const f = pick([5, 10, 15, 20]), c = pick([10, 15, 20, 25, 30, 40]); if(f * 9 === c * 4) return X.mealEnergy.gen(); const ans = f * 9 > c * 4 ? 'fat' : 'carb';
    return {p:S(`எது அதிக ஆற்றல் தரும்: ${f} g கொழுப்பு அல்லது ${c} g மாவுச்சத்து?`, `Which gives more energy: ${f} g of fat or ${c} g of carbohydrate?`), scene:'', opts:shuffle([{v:'fat', h:`${f} g கொழுப்பு / fat`}, {v:'carb', h:`${c} g மாவுச்சத்து / carbohydrate`}]), ans, ex:S(`கொழுப்பு ${f}×9 = ${f * 9} kcal; மாவு ${c}×4 = ${c * 4} kcal`, `Fat ${f}×9 = ${f * 9} kcal; carbohydrate ${c}×4 = ${c * 4} kcal`)}; } };

X.germGrowth = { title:S('கிருமிகள் இரட்டிப்பாகும் — கை கழுவுவது ஏன்?', 'Germs double — why wash hands?'), icon:'🦠',
  intro:S('பாக்டீரியா பெரும்பாலும் வேகமாகப் பிரிந்து இரட்டிப்பாகும் (எ.கா. 20 நிமிடத்துக்கு ஒரு முறை). n முறை இரட்டிப்பு → தொடக்க எண் × 2ⁿ. 1 கிருமி 6 மணிநேரத்தில் லட்சக்கணக்கு ஆகலாம்! அதனால்தான் கை கழுவுதல், உணவை மூடுதல், ஆன்டிபயாடிக் முழுக் கோர்ஸ் முக்கியம்.',
          'Many bacteria multiply by doubling fast (e.g. every 20 minutes). After n doublings: start × 2ⁿ. One germ can become hundreds of thousands in 6 hours! That is why washing hands, covering food and finishing antibiotics matter.'),
  gen(){ const N0 = pick([1, 2, 5, 10, 100]), dt = pick([20, 30, 60]), h = ri(1, 4), n = h * 60 / dt, N = N0 * Math.pow(2, n);
    return Q(`${N0} பாக்டீரியா; ஒவ்வொரு ${dt} நிமிடத்துக்கும் இரட்டிப்பாகிறது. ${h} மணி நேரத்தில் எத்தனை?`, `${N0} bacteria double every ${dt} minutes. How many after ${h} hour${h > 1 ? 's' : ''}?`, '<div style="font-size:38px">🦠🦠</div>', N, [N0 * n, N0 * h * 2, N / 2, N * 2], '', `${h} மணி = ${h * 60} நிமிடம் → ${n} முறை இரட்டிப்பு → ${N0} × 2^${n} = ${fmt(N)}`, `${h * 60} minutes → ${n} doublings → ${N0} × 2^${n} = ${fmt(N)}`); } };

const PHOTO = [
 ['இருட்டறையில் 3 நாள் வைத்த செடி','a plant kept 3 days in a dark room','light','ஒளி இல்லை → ஒளிச்சேர்க்கை நடக்காது → ஸ்டார்ச் உருவாகாது','No light → no photosynthesis → no starch'],
 ['காற்றில் CO₂ முழுவதும் நீக்கப்பட்ட பெட்டியில் செடி','a plant in a box with all CO₂ removed','co2','CO₂ இல்லை → குளுக்கோஸ் செய்ய மூலப்பொருள் இல்லை','No CO₂ → no raw material for glucose'],
 ['நீர் ஊற்றாமல் வாடிய செடி','a wilted plant given no water','water','நீர் ஒரு மூலப்பொருள்; குறைந்தால் ஒளிச்சேர்க்கை குறையும்','Water is a raw material; less water means less photosynthesis'],
 ['வெள்ளைப் பகுதி உள்ள இலை (குளோரோஃபில் இல்லை)','the white part of a variegated leaf (no chlorophyll)','chlorophyll','பச்சையம் ஒளியைப் பிடிக்கிறது; அது இல்லாத வெள்ளைப் பகுதியில் ஸ்டார்ச் இல்லை','Chlorophyll traps light; the white part has none, so no starch']];
X.photoWhy = { title:S('ஒளிச்சேர்க்கை — எது தேவை?', 'Photosynthesis — what is needed?'), icon:'🌿',
  intro:S('ஒளிச்சேர்க்கை: CO₂ + நீர் —(சூரிய ஒளி, குளோரோஃபில்)→ குளுக்கோஸ் + ஆக்சிஜன். நான்கு தேவைகள்: ஒளி, CO₂, நீர், குளோரோஃபில். ஒன்று இல்லாவிட்டாலும் உணவு தயாராகாது. இந்த ஆக்சிஜன்தான் நாம் சுவாசிக்கிறோம்; இந்த உணவுதான் எல்லா உணவுச் சங்கிலிக்கும் தொடக்கம்.',
          'Photosynthesis: CO₂ + water —(sunlight, chlorophyll)→ glucose + oxygen. Four needs: light, CO₂, water, chlorophyll. Miss one and no food is made. The oxygen is what we breathe; the food starts every food chain.'),
  gen(){ const k = ri(0, 2), s = pick(PHOTO);
    if(k === 0) return {p:S(`${s[0]} — எந்தத் தேவை இல்லை?`, `${s[1]} — which requirement is missing?`), scene:'', opts:shuffle([['light','ஒளி / light'],['co2','CO₂'],['water','நீர் / water'],['chlorophyll','குளோரோஃபில் / chlorophyll']].map(x => ({v:x[0], h:x[1]}))), ans:s[2], ex:S(s[3], s[4])};
    if(k === 1) return C('ஒளிச்சேர்க்கையில் செடி வெளியிடும் வாயு?', 'Which gas do plants release in photosynthesis?', '', 'O2', ['O2', 'CO2', 'N2', 'H2'], 'ஆக்சிஜன் (O₂) வெளியாகிறது; CO₂ உள்ளே எடுக்கப்படுகிறது', 'Oxygen (O₂) is released; CO₂ is taken in', {O2:'ஆக்சிஜன் / oxygen', CO2:'கார்பன் டையாக்சைடு / CO₂', N2:'நைட்ரஜன் / nitrogen', H2:'ஹைட்ரஜன் / hydrogen'});
    return C('செடியின் எந்தப் பகுதி ஒளிச்சேர்க்கை நடக்கும் முக்கிய இடம்?', 'Which plant part is the main site of photosynthesis?', '', 'leaf', ['leaf', 'root', 'flower', 'seed'], 'இலையில் குளோரோஃபில் அதிகம்; அங்குதான் ஒளிச்சேர்க்கை', 'Leaves hold the most chlorophyll, so photosynthesis happens there', {leaf:'இலை / leaf', root:'வேர் / root', flower:'பூ / flower', seed:'விதை / seed'}); } };

/* ================= REAL-LIFE MATHS ================= */
const GOODS = [['அரிசி','rice','kg'],['சர்க்கரை','sugar','kg'],['எண்ணெய்','oil','L'],['பருப்பு','dal','kg'],['பால்பொடி','milk powder','kg'],['தேங்காய் எண்ணெய்','coconut oil','L']];
X.bestBuy = { title:S('எது மலிவு? — அலகு விலை', 'Best buy — unit price'), icon:'🛒',
  intro:S('எந்தப் பொதி மலிவு என்று தெரிய "1 kg (அல்லது 1 L) விலை" பார். அலகு விலை = விலை ÷ அளவு. பெரிய பொதி எப்போதும் மலிவு அல்ல — கணக்குப் போடு!',
          'To find the cheaper pack, compare the price of ONE kg (or litre). Unit price = price ÷ quantity. A bigger pack is not always cheaper — do the maths!'),
  gen(){ const g = pick(GOODS), u1 = ri(30, 120), qa = pick([1, 2, 5]), qb = pick([2, 5, 10].filter(x => x !== qa)), pa = qa * u1, pb = qb * (u1 + pick([-6, -3, -1, 1, 3, 6]) ), ua = pa / qa, ub = pb / qb; if(ua === ub || pb <= 0) return X.bestBuy.gen();
    const ans = ua < ub ? 'A' : 'B'; return {p:S(`${g[0]}: பொதி A — ${qa} ${g[2]} ₹${pa}; பொதி B — ${qb} ${g[2]} ₹${pb}. எது மலிவு?`, `${g[1]}: pack A — ${qa} ${g[2]} for ₹${pa}; pack B — ${qb} ${g[2]} for ₹${pb}. Which is cheaper?`), scene:'<div style="font-size:34px">🛒</div>', opts:shuffle([{v:'A', h:`பொதி A / pack A (${qa} ${g[2]})`}, {v:'B', h:`பொதி B / pack B (${qb} ${g[2]})`}]), ans, ex:S(`A: ${pa} ÷ ${qa} = ₹${n2(ua)}/${g[2]}; B: ${pb} ÷ ${qb} = ₹${n2(ub)}/${g[2]}`, `A: ${pa} ÷ ${qa} = ₹${n2(ua)}/${g[2]}; B: ${pb} ÷ ${qb} = ₹${n2(ub)}/${g[2]}`)}; } };

X.percentLife = { title:S('சதவீத மாற்றம் — நிஜ வாழ்க்கை', 'Percent change in real life'), icon:'📈',
  intro:S('% மாற்றம் = (புதியது − பழையது) ÷ பழையது × 100. விலை உயர்வு, தள்ளுபடி, மதிப்பெண் முன்னேற்றம், மக்கள்தொகை வளர்ச்சி எல்லாவற்றுக்கும் இதே சூத்திரம். எப்போதும் பழைய மதிப்பையே அடிப்படையாக வை!',
          '% change = (new − old) ÷ old × 100. Price rises, discounts, mark improvements, population growth all use it. Always divide by the OLD value!'),
  gen(){ const old = pick([20, 40, 50, 80, 100, 120, 200, 250, 400, 500]), p = pick([5, 10, 15, 20, 25, 30, 40, 50]), up = Math.random() < 0.5, nw = old * (up ? 100 + p : 100 - p) / 100, k = ri(0, 1); if(!Number.isInteger(nw)) return X.percentLife.gen();
    const what = pick([['ஒரு பொருளின் விலை (₹)','a product price (₹)'],['மதிப்பெண்','marks'],['ஒரு கிராமத்தின் மக்கள்தொகை','a village population']]);
    if(k === 0) return Q(`${what[0]} ${old}-லிருந்து ${nw} ஆனது. இது எத்தனை % ${up ? 'உயர்வு' : 'குறைவு'}?`, `${what[1]} changed from ${old} to ${nw}. What percent ${up ? 'increase' : 'decrease'} is that?`, '', p, [100 - p, p * 2, Math.round(Math.abs(nw - old) / nw * 100) === p ? p + 5 : Math.round(Math.abs(nw - old) / nw * 100), p + 5], '%', `மாற்றம் = ${Math.abs(nw - old)}; ${Math.abs(nw - old)} ÷ ${old} × 100 = ${p}%`, `change = ${Math.abs(nw - old)}; ${Math.abs(nw - old)} ÷ ${old} × 100 = ${p}%`);
    return Q(`${what[0]} ${old}. அது ${p}% ${up ? 'உயர்ந்தால்' : 'குறைந்தால்'} புதிய மதிப்பு?`, `${what[1]} is ${old}. After a ${p}% ${up ? 'rise' : 'fall'}, the new value is…`, '', nw, [old + (up ? -1 : 1) * old * p / 100, old * p / 100, old + p, old * (100 + (up ? p : -p) * 2) / 100], '', `${old} × ${up ? 100 + p : 100 - p} ÷ 100 = ${nw}`, `${old} × ${up ? 100 + p : 100 - p} ÷ 100 = ${nw}`); } };

X.mapScale = { title:S('வரைபட அளவுகோல்', 'Map scale'), icon:'🗺️',
  intro:S('வரைபடத்தில் 1 cm = 5 km என்றால் ஒவ்வொரு 1 cm-க்கும் உண்மையில் 5 km. நிஜ தூரம் = வரைபட தூரம் × அளவுகோல். Google Maps-ம் இதே கணக்கில்தான் இயங்குகிறது.',
          'If 1 cm on the map = 5 km, then every 1 cm is really 5 km. Real distance = map distance × scale. Online maps use the same idea.'),
  gen(){ const sc = pick([2, 5, 10, 20, 25, 50]), cm = ri(2, 30), real = sc * cm;
    if(Math.random() < 0.5) return Q(`வரைபடத்தில் 1 cm = ${sc} km. இரு ஊர்களுக்கு இடையே ${cm} cm. உண்மை தூரம்?`, `On a map 1 cm = ${sc} km. Two towns are ${cm} cm apart. Real distance?`, '<div style="font-size:34px">🗺️</div>', real, [sc + cm, real * 2, real / 2, cm * 10], 'km', `${cm} × ${sc} = ${real} km`, `${cm} × ${sc} = ${real} km`);
    return Q(`வரைபடத்தில் 1 cm = ${sc} km. இரு ஊர்களின் உண்மை தூரம் ${real} km. வரைபடத்தில் எத்தனை cm?`, `On a map 1 cm = ${sc} km. Two towns are ${real} km apart. How many cm on the map?`, '<div style="font-size:34px">🗺️</div>', cm, [real - sc, real * sc, cm + 2, cm * 2], 'cm', `${real} ÷ ${sc} = ${cm} cm`, `${real} ÷ ${sc} = ${cm} cm`); } };

X.mileageCost = { title:S('மைலேஜ் & பயணச் செலவு', 'Mileage & trip cost'), icon:'⛽',
  intro:S('மைலேஜ் = ஒரு லிட்டரில் செல்லும் km. தேவையான எரிபொருள் = தூரம் ÷ மைலேஜ்; செலவு = லிட்டர் × விலை. எந்த வாகனம் சிக்கனம், நீண்ட பயணத்துக்கு எவ்வளவு பணம் என்று இதனால் திட்டமிடலாம் (விலை ஒரு எடுத்துக்காட்டு).',
          'Mileage = km per litre. Fuel needed = distance ÷ mileage; cost = litres × price. Plan which vehicle is thrifty and what a long trip costs (the price is just an example).'),
  gen(){ const mil = pick([20, 25, 40, 50, 60]), L = pick([2, 3, 4, 5, 6, 8, 10]), d = mil * L, pr = pick([90, 100, 105, 110]), k = ri(0, 1);
    if(k === 0) return Q(`ஒரு பைக் லிட்டருக்கு ${mil} km தரும். ${d} km செல்ல எத்தனை லிட்டர்?`, `A bike gives ${mil} km per litre. Fuel needed for ${d} km?`, '<div style="font-size:34px">🏍️⛽</div>', L, [d - mil, d * mil, L + 1, L * 2], 'L', `${d} ÷ ${mil} = ${L} L`, `${d} ÷ ${mil} = ${L} L`);
    return Q(`பைக் லிட்டருக்கு ${mil} km. பெட்ரோல் ₹${pr}/L. ${d} km பயணச் செலவு?`, `A bike does ${mil} km/L; petrol costs ₹${pr}/L. Fuel cost for ${d} km?`, '<div style="font-size:34px">🏍️⛽</div>', L * pr, [d * pr, L + pr, L * pr / 2, mil * pr], '₹', `${d} ÷ ${mil} = ${L} L; ${L} × ${pr} = ₹${L * pr}`, `${d} ÷ ${mil} = ${L} L; ${L} × ${pr} = ₹${L * pr}`); } };

G.KALVI_SCI = X;
})(typeof window !== 'undefined' ? window : globalThis);
