/* Kalvi Kalanjiyam — Classes 6–8 fact games: science, social, life skills, languages.
   Small curated datasets; every fact checked against standard textbooks (Samacheer / NCERT). */
(function(G){
'use strict';
const {S} = G.KALVI_UTIL;
const {pairGame, sortGame} = G.KALVI_BUILD;
const M = G.KALVI_MID;
const items = arr => arr.map(([e, ta, en, bin]) => ({e, ta, en, bin}));
const pairs = (arr, grp) => arr.map(([e, qta, qen, ata, aen]) => ({e, grp, q:S(qta, qen), a:S(ata, aen)}));

/* ================= SCIENCE ================= */
M.siUnits = pairGame({title:S('SI அலகுகள்', 'SI units'), icon:'📏',
  intro:S('உலகம் முழுவதும் ஒரே அலகுகள் (SI): நீளம் — மீட்டர், நிறை — கிலோகிராம், காலம் — வினாடி, வெப்பநிலை — கெல்வின், மின்னோட்டம் — ஆம்பியர். விசை — நியூட்டன், ஆற்றல் — ஜூல், திறன் — வாட், அழுத்தம் — பாஸ்கல். ஒரே அலகு இருப்பதால்தான் உலக விஞ்ஞானிகள் சேர்ந்து வேலை செய்ய முடிகிறது!', 'The whole world uses the same units (SI): length — metre, mass — kilogram, time — second, temperature — kelvin, current — ampere. Force — newton, energy — joule, power — watt, pressure — pascal. Shared units let scientists everywhere work together!')},
  pairs([['📏','நீளத்தின் SI அலகு?','SI unit of length?','மீட்டர் (m)','metre (m)'],['⚖️','நிறையின் SI அலகு?','SI unit of mass?','கிலோகிராம் (kg)','kilogram (kg)'],['⏱️','காலத்தின் SI அலகு?','SI unit of time?','வினாடி (s)','second (s)'],
    ['🌡️','வெப்பநிலையின் SI அலகு?','SI unit of temperature?','கெல்வின் (K)','kelvin (K)'],['🔌','மின்னோட்டத்தின் SI அலகு?','SI unit of electric current?','ஆம்பியர் (A)','ampere (A)'],['🧪','பொருளின் அளவின் SI அலகு?','SI unit of amount of substance?','மோல் (mol)','mole (mol)'],
    ['💡','ஒளிச்செறிவின் SI அலகு?','SI unit of luminous intensity?','கேண்டிலா (cd)','candela (cd)'],['💪','விசையின் SI அலகு?','SI unit of force?','நியூட்டன் (N)','newton (N)'],['🔋','ஆற்றல் / வேலையின் SI அலகு?','SI unit of energy / work?','ஜூல் (J)','joule (J)'],
    ['⚡','திறனின் SI அலகு?','SI unit of power?','வாட் (W)','watt (W)'],['🧱','அழுத்தத்தின் SI அலகு?','SI unit of pressure?','பாஸ்கல் (Pa)','pascal (Pa)'],['🎵','அதிர்வெண்ணின் SI அலகு?','SI unit of frequency?','ஹெர்ட்ஸ் (Hz)','hertz (Hz)']]));
M.changes = sortGame({title:S('இயற்பியல் மாற்றம், வேதியியல் மாற்றம்', 'Physical or chemical change?'), icon:'🔥',
  intro:S('இயற்பியல் மாற்றம்: வடிவம் அல்லது நிலை மட்டும் மாறும், புதிய பொருள் உருவாகாது, பெரும்பாலும் திரும்பப் பெறலாம் (பனி உருகுதல்). வேதியியல் மாற்றம்: புதிய பொருள் உருவாகும், திரும்பப் பெற முடியாது (காகிதம் எரிதல், இரும்பு துருப்பிடித்தல்).', 'Physical change: only shape or state changes, no new substance forms, often reversible (ice melting). Chemical change: a new substance forms and it can’t be undone (paper burning, iron rusting).'),
  ask:S('எந்த மாற்றம்?', 'Which kind of change?'), rule:S('புதிய பொருள் உருவானால் → வேதியியல் மாற்றம்', 'New substance formed → chemical change')},
  [{id:'p', e:'🧊', ta:'இயற்பியல்', en:'Physical'}, {id:'c', e:'🔥', ta:'வேதியியல்', en:'Chemical'}],
  items([['🧊','பனிக்கட்டி உருகுதல்','ice melting','p'],['🥄','சர்க்கரை நீரில் கரைதல்','sugar dissolving in water','p'],['📄','காகிதம் கிழித்தல்','tearing paper','p'],['♨️','நீர் கொதித்தல்','water boiling','p'],['🥛','கண்ணாடி உடைதல்','glass breaking','p'],['👕','துணி மடித்தல்','folding clothes','p'],['🥕','காய்கறி நறுக்குதல்','cutting vegetables','p'],['✏️','பென்சில் சீவுதல்','sharpening a pencil','p'],
    ['🔥','காகிதம் எரிதல்','paper burning','c'],['🔩','இரும்பு துருப்பிடித்தல்','iron rusting','c'],['🍚','அரிசி சமைத்தல்','cooking rice','c'],['🥛','பால் தயிராதல்','milk turning into curd','c'],['🍌','பழம் பழுத்தல்','fruit ripening','c'],['🍽️','உணவு செரித்தல்','digesting food','c'],['🪵','மரக்கட்டை எரிதல்','wood burning','c']]), 6);
M.acidBase = sortGame({title:S('அமிலம், காரம், நடுநிலை', 'Acid, base or neutral?'), icon:'🧪',
  intro:S('அமிலங்கள் புளிப்புச் சுவை, நீல லிட்மஸைச் சிவப்பாக்கும் (எலுமிச்சை, புளி, வினிகர், தயிர்). காரங்கள் கசப்பு, வழவழப்பு, சிவப்பு லிட்மஸை நீலமாக்கும் (சோப்பு, சமையல் சோடா, சுண்ணாம்பு நீர்). மஞ்சள் ஒரு இயற்கைக் காட்டி — காரத்தில் சிவப்பாக மாறும்! சுவைத்துப் பார்க்காதே — காட்டியைப் பயன்படுத்து.', 'Acids taste sour and turn blue litmus red (lemon, tamarind, vinegar, curd). Bases are bitter and soapy and turn red litmus blue (soap, baking soda, lime water). Turmeric is a natural indicator — it turns red in a base! Never taste to test — use an indicator.'),
  ask:S('எந்த வகை?', 'Which kind?'), rule:S('புளிப்பு → அமிலம் • சோப்பு போன்றது → காரம் • தூய நீர், சர்க்கரை, உப்புக் கரைசல் → நடுநிலை', 'Sour → acid • soapy → base • pure water, sugar or salt solution → neutral')},
  [{id:'a', e:'🍋', ta:'அமிலம்', en:'Acid'}, {id:'b', e:'🧼', ta:'காரம்', en:'Base'}, {id:'n', e:'💧', ta:'நடுநிலை', en:'Neutral'}],
  items([['🍋','எலுமிச்சைச் சாறு','lemon juice','a'],['🍶','வினிகர்','vinegar','a'],['🍊','ஆரஞ்சுச் சாறு','orange juice','a'],['🥣','தயிர்','curd','a'],['🟤','புளி','tamarind','a'],['🍅','தக்காளிச் சாறு','tomato juice','a'],
    ['🧼','சோப்புக் கரைசல்','soap solution','b'],['🧁','சமையல் சோடா','baking soda','b'],['🥛','சுண்ணாம்பு நீர்','lime water','b'],['💊','மில்க் ஆஃப் மெக்னீசியா','milk of magnesia','b'],['🧺','சலவைச் சோடா','washing soda','b'],
    ['💧','தூய நீர்','pure water','n'],['🍬','சர்க்கரைக் கரைசல்','sugar solution','n'],['🧂','சாதாரண உப்புக் கரைசல்','common salt solution','n']]), 6);
M.acidSource = pairGame({title:S('இயற்கை அமிலங்கள்', 'Natural acids'), icon:'🍋',
  intro:S('எலுமிச்சை, ஆரஞ்சு — சிட்ரிக் அமிலம்; வினிகர் — அசிட்டிக் அமிலம்; தயிர் — லாக்டிக் அமிலம்; புளி — டார்டாரிக் அமிலம்; தக்காளி — ஆக்சாலிக் அமிலம்; எறும்புக் கடி — ஃபார்மிக் அமிலம்; ஆப்பிள் — மாலிக் அமிலம்.', 'Lemon, orange — citric acid; vinegar — acetic acid; curd — lactic acid; tamarind — tartaric acid; tomato — oxalic acid; ant sting — formic acid; apple — malic acid.')},
  pairs([['🍋','எலுமிச்சையில் உள்ள அமிலம்?','Acid in lemon?','சிட்ரிக் அமிலம்','citric acid'],['🍊','ஆரஞ்சில் உள்ள அமிலம்?','Acid in orange?','சிட்ரிக் அமிலம்','citric acid'],['🍶','வினிகரில் உள்ள அமிலம்?','Acid in vinegar?','அசிட்டிக் அமிலம்','acetic acid'],
    ['🥣','தயிரில் உள்ள அமிலம்?','Acid in curd?','லாக்டிக் அமிலம்','lactic acid'],['🟤','புளியில் உள்ள அமிலம்?','Acid in tamarind?','டார்டாரிக் அமிலம்','tartaric acid'],['🍅','தக்காளியில் உள்ள அமிலம்?','Acid in tomato?','ஆக்சாலிக் அமிலம்','oxalic acid'],
    ['🐜','எறும்புக் கடியில் உள்ள அமிலம்?','Acid in an ant sting?','ஃபார்மிக் அமிலம்','formic acid'],['🍎','ஆப்பிளில் உள்ள அமிலம்?','Acid in apple?','மாலிக் அமிலம்','malic acid']]));
M.cellParts = pairGame({title:S('செல்லின் பகுதிகள்', 'Parts of a cell'), icon:'🦠',
  intro:S('செல் = உயிரின் அடிப்படை அலகு. உட்கரு — கட்டுப்பாட்டு மையம்; மைட்டோகாண்ட்ரியா — ஆற்றல் நிலையம்; பசுங்கணிகம் — ஒளிச்சேர்க்கை (தாவரங்களில்); செல் சுவர் — உறுதி தரும் (தாவரங்களில்); செல் சவ்வு — உள்ளே வருவதையும் வெளியே போவதையும் கட்டுப்படுத்தும்; நுண்குமிழ் — சேமிப்பு; ரைபோசோம் — புரதம் தயாரிப்பு.', 'A cell is the basic unit of life. Nucleus — control centre; mitochondria — powerhouse; chloroplast — photosynthesis (plants); cell wall — gives strength (plants); cell membrane — controls what goes in and out; vacuole — storage; ribosome — makes proteins.')},
  pairs([['🎯','செல்லின் கட்டுப்பாட்டு மையம்?','Control centre of the cell?','உட்கரு','nucleus'],['⚡','செல்லின் ஆற்றல் நிலையம்?','Powerhouse of the cell?','மைட்டோகாண்ட்ரியா','mitochondria'],['🌿','ஒளிச்சேர்க்கை நடக்கும் இடம்?','Where photosynthesis happens?','பசுங்கணிகம்','chloroplast'],
    ['🧱','தாவர செல்லுக்கு உறுதி தரும் வெளி அடுக்கு?','Rigid outer layer of a plant cell?','செல் சுவர்','cell wall'],['🚪','உள்ளே/வெளியே செல்வதைக் கட்டுப்படுத்துவது?','Controls what enters and leaves?','செல் சவ்வு','cell membrane'],['🫙','நீரையும் பொருள்களையும் சேமிப்பது?','Stores water and materials?','நுண்குமிழ் (வாக்குவோல்)','vacuole'],['🏭','புரதத்தைத் தயாரிப்பது?','Makes proteins?','ரைபோசோம்','ribosome']]));
M.plantAnimalCell = sortGame({title:S('தாவர செல், விலங்கு செல்', 'Plant cell or animal cell?'), icon:'🌱',
  intro:S('தாவர செல்லில் மட்டும்: செல் சுவர், பசுங்கணிகம், பெரிய மைய நுண்குமிழ். விலங்கு செல்லில் மட்டும்: சென்ட்ரியோல். இரண்டிலும்: உட்கரு, செல் சவ்வு, மைட்டோகாண்ட்ரியா, சைட்டோபிளாசம், ரைபோசோம்.', 'Only in plant cells: cell wall, chloroplast, large central vacuole. Only in animal cells: centrioles. In both: nucleus, cell membrane, mitochondria, cytoplasm, ribosomes.'),
  ask:S('இந்தப் பகுதி எங்கே இருக்கும்?', 'Where is this part found?'), rule:S('சுவர், பசுங்கணிகம், பெரிய நுண்குமிழ் → தாவரம் • சென்ட்ரியோல் → விலங்கு', 'Wall, chloroplast, big vacuole → plant • centrioles → animal')},
  [{id:'p', e:'🌿', ta:'தாவரம் மட்டும்', en:'Plant only'}, {id:'a', e:'🐾', ta:'விலங்கு மட்டும்', en:'Animal only'}, {id:'b', e:'🤝', ta:'இரண்டிலும்', en:'Both'}],
  items([['🧱','செல் சுவர்','cell wall','p'],['🌿','பசுங்கணிகம்','chloroplast','p'],['🫙','பெரிய மைய நுண்குமிழ்','large central vacuole','p'],['✳️','சென்ட்ரியோல்','centrioles','a'],
    ['🎯','உட்கரு','nucleus','b'],['🚪','செல் சவ்வு','cell membrane','b'],['⚡','மைட்டோகாண்ட்ரியா','mitochondria','b'],['🌊','சைட்டோபிளாசம்','cytoplasm','b'],['🏭','ரைபோசோம்','ribosomes','b']]), 6);
M.bodySystems = pairGame({title:S('உடல் மண்டலங்கள்', 'Body systems'), icon:'🫀',
  intro:S('இதயம் — இரத்த ஓட்ட மண்டலம்; நுரையீரல் — சுவாச மண்டலம்; இரைப்பை — செரிமான மண்டலம்; மூளை — நரம்பு மண்டலம்; சிறுநீரகம் — கழிவு நீக்க மண்டலம்; எலும்புகள் — எலும்பு மண்டலம்.', 'Heart — circulatory system; lungs — respiratory; stomach — digestive; brain — nervous; kidneys — excretory; bones — skeletal.')},
  pairs([['🫀','இதயம் எந்த மண்டலம்?','The heart belongs to…','இரத்த ஓட்ட மண்டலம்','circulatory system'],['🫁','நுரையீரல் எந்த மண்டலம்?','The lungs belong to…','சுவாச மண்டலம்','respiratory system'],['🍽️','இரைப்பை எந்த மண்டலம்?','The stomach belongs to…','செரிமான மண்டலம்','digestive system'],
    ['🧠','மூளை எந்த மண்டலம்?','The brain belongs to…','நரம்பு மண்டலம்','nervous system'],['🫘','சிறுநீரகம் எந்த மண்டலம்?','The kidneys belong to…','கழிவு நீக்க மண்டலம்','excretory system'],['🦴','எலும்புகள் எந்த மண்டலம்?','Bones belong to…','எலும்பு மண்டலம்','skeletal system'],['💪','தசைகள் எந்த மண்டலம்?','Muscles belong to…','தசை மண்டலம்','muscular system']]));
M.deficiency = pairGame({title:S('ஊட்டச்சத்துக் குறைபாட்டு நோய்கள்', 'Deficiency diseases'), icon:'🥕',
  intro:S('வைட்டமின் A குறைந்தால் — மாலைக்கண்; B1 — பெரிபெரி; C — ஸ்கர்வி (ஈறுகளில் இரத்தம்); D — ரிக்கெட்ஸ் (வளைந்த எலும்பு); இரும்புச்சத்து — இரத்தசோகை; அயோடின் — முன்கழுத்துக் கழலை; புரதம் — குவாஷியோர்கர். சரிவிகித உணவே மருந்து!', 'Lack of vitamin A — night blindness; B1 — beriberi; C — scurvy (bleeding gums); D — rickets (bent bones); iron — anaemia; iodine — goitre; protein — kwashiorkor. A balanced diet is the best medicine!')},
  pairs([['🥕','வைட்டமின் A குறைபாடு?','Lack of vitamin A causes…','மாலைக்கண் நோய்','night blindness'],['🌾','வைட்டமின் B1 குறைபாடு?','Lack of vitamin B1 causes…','பெரிபெரி','beriberi'],['🍊','வைட்டமின் C குறைபாடு?','Lack of vitamin C causes…','ஸ்கர்வி','scurvy'],
    ['☀️','வைட்டமின் D குறைபாடு?','Lack of vitamin D causes…','ரிக்கெட்ஸ்','rickets'],['🥬','இரும்புச்சத்துக் குறைபாடு?','Lack of iron causes…','இரத்தசோகை','anaemia'],['🧂','அயோடின் குறைபாடு?','Lack of iodine causes…','முன்கழுத்துக் கழலை','goitre'],['🍲','புரதக் குறைபாடு?','Lack of protein causes…','குவாஷியோர்கர்','kwashiorkor']]));
M.magnetic = sortGame({title:S('காந்தம் ஈர்க்குமா?', 'Magnetic or not?'), icon:'🧲',
  intro:S('காந்தம் இரும்பு, நிக்கல், கோபால்ட் ஆகியவற்றை ஈர்க்கும். செம்பு, அலுமினியம், தங்கம், பிளாஸ்டிக், மரம், கண்ணாடி, ரப்பர் ஆகியவற்றை ஈர்க்காது — "உலோகம் எல்லாம் காந்தத்தில் ஒட்டும்" என்பது தவறு!', 'A magnet attracts iron, nickel and cobalt. It does not attract copper, aluminium, gold, plastic, wood, glass or rubber — "all metals stick to magnets" is wrong!'),
  ask:S('காந்தம் ஈர்க்குமா?', 'Does a magnet attract it?'), rule:S('இரும்பு, நிக்கல், கோபால்ட் → ஈர்க்கும்', 'Iron, nickel, cobalt → attracted')},
  [{id:'y', e:'🧲', ta:'ஈர்க்கும்', en:'Magnetic'}, {id:'n', e:'🚫', ta:'ஈர்க்காது', en:'Non-magnetic'}],
  items([['🔩','இரும்பு ஆணி','iron nail','y'],['⚙️','நிக்கல்','nickel','y'],['🔘','கோபால்ட்','cobalt','y'],['✨','இரும்புத் தூள்','iron filings','y'],['📎','இரும்பு ஊசி','iron pin','y'],
    ['🥤','பிளாஸ்டிக் பாட்டில்','plastic bottle','n'],['🪵','மரக்கட்டை','wood','n'],['🥛','கண்ணாடி','glass','n'],['🟠','செம்புக் கம்பி','copper wire','n'],['🍫','அலுமினியத் தாள்','aluminium foil','n'],['💍','தங்க மோதிரம்','gold ring','n'],['🧽','ரப்பர்','rubber','n']]), 6);
M.conductors = sortGame({title:S('மின்கடத்தி, மின்காப்பான்', 'Conductor or insulator?'), icon:'🔌',
  intro:S('மின்கடத்திகள் மின்சாரத்தைச் செல்ல விடும் — பெரும்பாலான உலோகங்கள் (செம்பு, இரும்பு, அலுமினியம், வெள்ளி) மற்றும் கிராஃபைட் (பென்சில் முனை). மின்காப்பான்கள் விடாது — ரப்பர், பிளாஸ்டிக், உலர்ந்த மரம், கண்ணாடி. அதனால்தான் மின்கம்பிகளுக்குப் பிளாஸ்டிக் உறை! ஈரமான கையால் சுவிட்சைத் தொடாதே.', 'Conductors let electricity flow — most metals (copper, iron, aluminium, silver) and graphite (pencil lead). Insulators don’t — rubber, plastic, dry wood, glass. That’s why wires have plastic covers! Never touch a switch with wet hands.'),
  ask:S('மின்சாரம் செல்லுமா?', 'Does electricity flow through it?'), rule:S('உலோகங்கள், கிராஃபைட் → கடத்தி', 'Metals, graphite → conductor')},
  [{id:'c', e:'⚡', ta:'மின்கடத்தி', en:'Conductor'}, {id:'i', e:'🛡️', ta:'மின்காப்பான்', en:'Insulator'}],
  items([['🟠','செம்புக் கம்பி','copper wire','c'],['🔩','இரும்பு ஆணி','iron nail','c'],['🍫','அலுமினியத் தாள்','aluminium foil','c'],['🥄','வெள்ளிக் கரண்டி','silver spoon','c'],['✏️','பென்சில் முனை (கிராஃபைட்)','pencil lead (graphite)','c'],
    ['🧽','ரப்பர்','rubber','i'],['🥤','பிளாஸ்டிக்','plastic','i'],['🪵','உலர்ந்த மரம்','dry wood','i'],['🥛','கண்ணாடி','glass','i'],['📄','காகிதம்','paper','i'],['🧶','பருத்தித் துணி','cotton cloth','i']]), 6);
M.lightObjects = sortGame({title:S('ஒளி கடக்குமா?', 'Does light pass through?'), icon:'🔦',
  intro:S('ஒளி ஊடுருவும் (தெளிவாகத் தெரியும்) — கண்ணாடி, நீர், காற்று. ஒளி கசியும் (மங்கலாகத் தெரியும்) — பட்டர் பேப்பர், உறைந்த கண்ணாடி, எண்ணெய் தடவிய காகிதம். ஒளி புகா (ஒன்றும் தெரியாது, நிழல் விழும்) — மரம், கல், உலோகம், அட்டை.', 'Transparent (see clearly) — clear glass, water, air. Translucent (see blurrily) — butter paper, frosted glass, oiled paper. Opaque (nothing passes, makes a shadow) — wood, stone, metal, cardboard.'),
  ask:S('ஒளி எவ்வளவு கடக்கும்?', 'How much light passes?'), rule:S('தெளிவு → ஊடுருவும் • மங்கல் → கசியும் • இல்லை → புகா', 'Clear → transparent • blurry → translucent • none → opaque')},
  [{id:'t', e:'🪟', ta:'ஒளி ஊடுருவும்', en:'Transparent'}, {id:'l', e:'🌫️', ta:'ஒளி கசியும்', en:'Translucent'}, {id:'o', e:'🧱', ta:'ஒளி புகா', en:'Opaque'}],
  items([['🪟','தெளிவான கண்ணாடி','clear glass','t'],['💧','தூய நீர்','clean water','t'],['🌬️','காற்று','air','t'],['🧈','பட்டர் பேப்பர்','butter paper','l'],['🚿','உறைந்த கண்ணாடி','frosted glass','l'],['📃','எண்ணெய் தடவிய காகிதம்','oiled paper','l'],['📜','டிரேசிங் பேப்பர்','tracing paper','l'],
    ['🪵','மரப் பலகை','wooden board','o'],['🪨','கல்','stone','o'],['🍳','உலோகத் தட்டு','metal plate','o'],['📦','அட்டைப் பெட்டி','cardboard','o'],['📕','புத்தகம்','book','o']]), 6);
M.metals = sortGame({title:S('உலோகம், அலோகம்', 'Metal or non-metal?'), icon:'🥇',
  intro:S('உலோகங்கள்: பளபளப்பு, தட்டினால் ஒலி, வெப்பமும் மின்சாரமும் கடத்தும், தகடாக்கலாம், கம்பியாக்கலாம் (இரும்பு, செம்பு, அலுமினியம், தங்கம், வெள்ளி, துத்தநாகம்). பாதரசம் அறை வெப்பநிலையில் திரவமாக உள்ள உலோகம்! அலோகங்கள்: கார்பன், கந்தகம், ஆக்சிஜன், நைட்ரஜன், பாஸ்பரஸ், அயோடின், குளோரின், ஹைட்ரஜன்.', 'Metals are shiny, ring when struck, conduct heat and electricity, and can be beaten into sheets and drawn into wires (iron, copper, aluminium, gold, silver, zinc). Mercury is a metal that is liquid at room temperature! Non-metals: carbon, sulphur, oxygen, nitrogen, phosphorus, iodine, chlorine, hydrogen.'),
  ask:S('உலோகமா, அலோகமா?', 'Metal or non-metal?'), rule:S('பளபளப்பு, கடத்தும் → உலோகம்', 'Shiny, conducts → metal')},
  [{id:'m', e:'🔩', ta:'உலோகம்', en:'Metal'}, {id:'n', e:'💨', ta:'அலோகம்', en:'Non-metal'}],
  items([['🔩','இரும்பு','iron','m'],['🟠','செம்பு','copper','m'],['🍫','அலுமினியம்','aluminium','m'],['💍','தங்கம்','gold','m'],['🥈','வெள்ளி','silver','m'],['⚪','துத்தநாகம்','zinc','m'],['🌡️','பாதரசம்','mercury','m'],
    ['✏️','கார்பன்','carbon','n'],['🟡','கந்தகம்','sulphur','n'],['🫁','ஆக்சிஜன்','oxygen','n'],['🌫️','நைட்ரஜன்','nitrogen','n'],['🔥','பாஸ்பரஸ்','phosphorus','n'],['🟣','அயோடின்','iodine','n'],['🟢','குளோரின்','chlorine','n']]), 6);
M.elements = pairGame({title:S('தனிமங்களின் குறியீடுகள்', 'Element symbols'), icon:'⚛️',
  intro:S('ஒவ்வொரு தனிமத்துக்கும் ஒரு குறியீடு. சில ஆங்கிலப் பெயரிலிருந்து: H (Hydrogen), O (Oxygen), C (Carbon). சில லத்தீன் பெயரிலிருந்து: Na (Natrium — சோடியம்), K (Kalium — பொட்டாசியம்), Fe (Ferrum — இரும்பு), Cu (Cuprum — செம்பு), Ag (Argentum — வெள்ளி), Au (Aurum — தங்கம்), Hg (பாதரசம்), Pb (Plumbum — ஈயம்).', 'Every element has a symbol. Some come from English names: H (hydrogen), O (oxygen), C (carbon). Some from Latin: Na (natrium — sodium), K (kalium — potassium), Fe (ferrum — iron), Cu (cuprum — copper), Ag (argentum — silver), Au (aurum — gold), Hg (mercury), Pb (plumbum — lead).')},
  [['ஹைட்ரஜன்','Hydrogen','H'],['ஹீலியம்','Helium','He'],['கார்பன்','Carbon','C'],['நைட்ரஜன்','Nitrogen','N'],['ஆக்சிஜன்','Oxygen','O'],['சோடியம்','Sodium','Na'],['மெக்னீசியம்','Magnesium','Mg'],['அலுமினியம்','Aluminium','Al'],['கந்தகம்','Sulphur','S'],['குளோரின்','Chlorine','Cl'],
   ['பொட்டாசியம்','Potassium','K'],['கால்சியம்','Calcium','Ca'],['இரும்பு','Iron','Fe'],['செம்பு','Copper','Cu'],['துத்தநாகம்','Zinc','Zn'],['வெள்ளி','Silver','Ag'],['தங்கம்','Gold','Au'],['பாதரசம்','Mercury','Hg'],['ஈயம்','Lead','Pb'],['வெள்ளீயம்','Tin','Sn']]
    .map(([ta, en, sym]) => ({e:'⚛️', q:S(`${ta} — குறியீடு?`, `Symbol of ${en}?`), a:S(sym, sym)})));
M.energySources = sortGame({title:S('புதுப்பிக்கத்தக்க ஆற்றல்', 'Renewable or not?'), icon:'☀️',
  intro:S('புதுப்பிக்கத்தக்கவை — இயற்கை மீண்டும் மீண்டும் தரும்: சூரிய ஒளி, காற்று, நீர் மின்சாரம், கடல் அலை, புவி வெப்பம், உயிரி எரிபொருள். புதுப்பிக்க முடியாதவை — தீர்ந்துவிடும்: நிலக்கரி, பெட்ரோலியம், இயற்கை எரிவாயு, யுரேனியம். தமிழ்நாடு காற்றாலை மின்சாரத்தில் இந்தியாவின் முன்னோடி மாநிலங்களில் ஒன்று!', 'Renewable — nature keeps giving: sunlight, wind, hydro power, tides, geothermal heat, biomass. Non-renewable — they run out: coal, petroleum, natural gas, uranium. Tamil Nadu is one of India’s leading states in wind power!'),
  ask:S('எந்த வகை ஆற்றல்?', 'Which kind?'), rule:S('மீண்டும் கிடைக்கும் → புதுப்பிக்கத்தக்கது', 'Comes back again → renewable')},
  [{id:'r', e:'♻️', ta:'புதுப்பிக்கத்தக்கது', en:'Renewable'}, {id:'n', e:'⛽', ta:'புதுப்பிக்க முடியாதது', en:'Non-renewable'}],
  items([['☀️','சூரிய ஒளி','solar','r'],['🌬️','காற்று','wind','r'],['💧','நீர் மின்சாரம்','hydro','r'],['🌊','கடல் அலை','tidal','r'],['🌋','புவி வெப்பம்','geothermal','r'],['🌾','உயிரி எரிபொருள்','biomass','r'],
    ['⚫','நிலக்கரி','coal','n'],['🛢️','பெட்ரோலியம்','petroleum','n'],['🔥','இயற்கை எரிவாயு','natural gas','n'],['☢️','யுரேனியம்','uranium','n']]), 6);
M.microbes = sortGame({title:S('நோய்களும் நுண்ணுயிரிகளும்', 'Diseases & microbes'), icon:'🦠',
  intro:S('வைரஸ்: சளி, போலியோ, சின்னம்மை, தட்டம்மை, டெங்கு (ஏடிஸ் கொசு பரப்பும்). பாக்டீரியா: டைபாய்டு, காலரா, காசநோய். புரோட்டோசோவா: மலேரியா (பெண் அனோபிலஸ் கொசு பரப்பும்), அமீபா வயிற்றுப்போக்கு. தடுப்பூசி, சுத்தமான நீர், கைகழுவுதல், கொசு ஒழிப்பு — நம்மைக் காக்கும்!', 'Virus: common cold, polio, chickenpox, measles, dengue (spread by the Aedes mosquito). Bacteria: typhoid, cholera, tuberculosis. Protozoa: malaria (spread by the female Anopheles mosquito), amoebic dysentery. Vaccines, clean water, handwashing and mosquito control protect us!'),
  ask:S('எந்த நுண்ணுயிரி காரணம்?', 'Which microbe causes it?'), rule:S('சளி, போலியோ, அம்மை, டெங்கு → வைரஸ் • டைபாய்டு, காலரா, காசநோய் → பாக்டீரியா • மலேரியா → புரோட்டோசோவா', 'Cold, polio, pox, measles, dengue → virus • typhoid, cholera, TB → bacteria • malaria → protozoa')},
  [{id:'v', e:'🦠', ta:'வைரஸ்', en:'Virus'}, {id:'b', e:'🧫', ta:'பாக்டீரியா', en:'Bacteria'}, {id:'p', e:'🔬', ta:'புரோட்டோசோவா', en:'Protozoa'}],
  items([['🤧','சளி','common cold','v'],['🦵','போலியோ','polio','v'],['🔴','சின்னம்மை','chickenpox','v'],['🌡️','தட்டம்மை','measles','v'],['🦟','டெங்கு','dengue','v'],
    ['🤒','டைபாய்டு','typhoid','b'],['💧','காலரா','cholera','b'],['🫁','காசநோய்','tuberculosis','b'],['🦟','மலேரியா','malaria','p'],['🚽','அமீபா வயிற்றுப்போக்கு','amoebic dysentery','p']]), 6);
const PL = [['புதன்','Mercury'],['வெள்ளி','Venus'],['பூமி','Earth'],['செவ்வாய்','Mars'],['வியாழன்','Jupiter'],['சனி','Saturn'],['யுரேனஸ்','Uranus'],['நெப்டியூன்','Neptune']];
const ORD = [['முதல்','1st'],['இரண்டாவது','2nd'],['மூன்றாவது','3rd'],['நான்காவது','4th'],['ஐந்தாவது','5th'],['ஆறாவது','6th'],['ஏழாவது','7th'],['எட்டாவது','8th']];
M.planets = pairGame({title:S('சூரியக் குடும்பம்', 'The solar system'), icon:'🪐',
  intro:S('சூரியனிலிருந்து வரிசை: புதன், வெள்ளி, பூமி, செவ்வாய், வியாழன், சனி, யுரேனஸ், நெப்டியூன். மிகப் பெரியது வியாழன், மிகச் சிறியது புதன், மிக வெப்பமானது வெள்ளி (அடர்த்தியான வளிமண்டலம்), "சிவப்புக் கோள்" செவ்வாய். உயிர்கள் இருப்பதாகத் தெரிந்த ஒரே கோள் பூமி.', 'Order from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune. Largest Jupiter, smallest Mercury, hottest Venus (thick atmosphere), the "red planet" Mars. Earth is the only planet known to have life.')},
  PL.map(([ta, en], i) => ({e:'🪐', q:S(`சூரியனிலிருந்து ${ORD[i][0]} கோள்?`, `The ${ORD[i][1]} planet from the Sun?`), a:S(ta, en)}))
    .concat([['மிகப் பெரிய கோள்?','Largest planet?',4],['மிகச் சிறிய கோள்?','Smallest planet?',0],['மிக வெப்பமான கோள்?','Hottest planet?',1],['"சிவப்புக் கோள்"?','The "red planet"?',3],['உயிர்கள் உள்ளதாகத் தெரிந்த ஒரே கோள்?','The only planet known to have life?',2]]
      .map(([qt, qe, i]) => ({e:'🔭', q:S(qt, qe), a:S(PL[i][0], PL[i][1])}))));

/* ================= SOCIAL SCIENCE ================= */
M.capitals = pairGame({title:S('மாநிலங்களும் தலைநகரங்களும்', 'States & capitals'), icon:'🗺️',
  intro:S('இந்தியாவில் 28 மாநிலங்களும் 8 யூனியன் பிரதேசங்களும் உள்ளன. தமிழ்நாடு — சென்னை, கேரளா — திருவனந்தபுரம், கர்நாடகா — பெங்களூரு, தெலங்கானா — ஹைதராபாத், மகாராஷ்டிரா — மும்பை.', 'India has 28 states and 8 union territories. Tamil Nadu — Chennai, Kerala — Thiruvananthapuram, Karnataka — Bengaluru, Telangana — Hyderabad, Maharashtra — Mumbai.')},
  [['தமிழ்நாடு','Tamil Nadu','சென்னை','Chennai'],['கேரளா','Kerala','திருவனந்தபுரம்','Thiruvananthapuram'],['கர்நாடகா','Karnataka','பெங்களூரு','Bengaluru'],['தெலங்கானா','Telangana','ஹைதராபாத்','Hyderabad'],['மகாராஷ்டிரா','Maharashtra','மும்பை','Mumbai'],
   ['குஜராத்','Gujarat','காந்திநகர்','Gandhinagar'],['ராஜஸ்தான்','Rajasthan','ஜெய்ப்பூர்','Jaipur'],['பஞ்சாப்','Punjab','சண்டிகர்','Chandigarh'],['உத்தரப் பிரதேசம்','Uttar Pradesh','லக்னோ','Lucknow'],['பீகார்','Bihar','பாட்னா','Patna'],['மேற்கு வங்காளம்','West Bengal','கொல்கத்தா','Kolkata'],
   ['ஒடிசா','Odisha','புவனேஸ்வர்','Bhubaneswar'],['மத்தியப் பிரதேசம்','Madhya Pradesh','போபால்','Bhopal'],['சத்தீஸ்கர்','Chhattisgarh','ராய்ப்பூர்','Raipur'],['ஜார்கண்ட்','Jharkhand','ராஞ்சி','Ranchi'],['அசாம்','Assam','திஸ்பூர்','Dispur'],['மேகாலயா','Meghalaya','ஷில்லாங்','Shillong'],
   ['மணிப்பூர்','Manipur','இம்பால்','Imphal'],['மிசோரம்','Mizoram','ஐசால்','Aizawl'],['நாகாலாந்து','Nagaland','கோஹிமா','Kohima'],['திரிபுரா','Tripura','அகர்தலா','Agartala'],['அருணாச்சலப் பிரதேசம்','Arunachal Pradesh','இட்டாநகர்','Itanagar'],['சிக்கிம்','Sikkim','காங்டாக்','Gangtok'],['கோவா','Goa','பனாஜி','Panaji']]
    .map(([a, b, c, d]) => ({e:'📍', q:S(`${a} — தலைநகர்?`, `Capital of ${b}?`), a:S(c, d)})));
M.monuments = pairGame({title:S('யார் கட்டியது?', 'Who built it?'), icon:'🛕',
  intro:S('தஞ்சைப் பெரிய கோயில் — முதலாம் இராஜராஜ சோழன் (சுமார் கி.பி. 1010). கங்கைகொண்ட சோழபுரம் — முதலாம் இராஜேந்திர சோழன். தாராசுரம் ஐராவதேசுவரர் கோயில் — இரண்டாம் இராஜராஜ சோழன். மாமல்லபுரம் ஐந்து ரதங்கள் — பல்லவர் (முதலாம் நரசிம்மவர்மன்). காஞ்சி கைலாசநாதர் கோயில் — இராஜசிம்ம பல்லவன். தாஜ்மஹால் — ஷாஜஹான். சாஞ்சி ஸ்தூபி — அசோகர்.', 'Thanjavur Big Temple — Rajaraja Chola I (about 1010 CE). Gangaikonda Cholapuram — Rajendra Chola I. Airavatesvara Temple, Darasuram — Rajaraja Chola II. Five Rathas, Mamallapuram — the Pallavas (Narasimhavarman I). Kailasanathar Temple, Kanchipuram — Rajasimha Pallava. Taj Mahal — Shah Jahan. Sanchi Stupa — Ashoka.')},
  pairs([['🛕','தஞ்சைப் பெரிய கோயிலைக் கட்டியவர்?','Who built the Thanjavur Big Temple (Brihadeeswarar)?','முதலாம் இராஜராஜ சோழன்','Rajaraja Chola I'],['🛕','கங்கைகொண்ட சோழபுரம் கோயிலைக் கட்டியவர்?','Who built the Gangaikonda Cholapuram temple?','முதலாம் இராஜேந்திர சோழன்','Rajendra Chola I'],
    ['🛕','தாராசுரம் ஐராவதேசுவரர் கோயிலைக் கட்டியவர்?','Who built the Airavatesvara Temple, Darasuram?','இரண்டாம் இராஜராஜ சோழன்','Rajaraja Chola II'],['🪨','மாமல்லபுரம் ஐந்து ரதங்களை அமைத்தவர்?','Who made the Five Rathas at Mamallapuram?','முதலாம் நரசிம்மவர்மப் பல்லவன்','Narasimhavarman I (Pallava)'],
    ['🛕','காஞ்சி கைலாசநாதர் கோயிலைக் கட்டியவர்?','Who built the Kailasanathar Temple, Kanchipuram?','இராஜசிம்ம பல்லவன்','Rajasimha Pallava'],['🕌','தாஜ்மஹாலைக் கட்டியவர்?','Who built the Taj Mahal?','ஷாஜஹான்','Shah Jahan'],['☸️','சாஞ்சி ஸ்தூபியை முதலில் அமைத்தவர்?','Who first built the Sanchi Stupa?','அசோகர்','Ashoka']], 'k'));
M.ancientSites = pairGame({title:S('அகழாய்வுகள் — நம் பழமை', 'Excavations — our ancient past'), icon:'⛏️',
  intro:S('சிந்துவெளி நாகரிகம்: ஹரப்பா (1921-ல் முதலில் அகழாய்வு), மொகஞ்சதாரோ (பெருங்குளம்), லோத்தல் (கப்பல் துறை). தமிழ்நாடு: கீழடி (சிவகங்கை மாவட்டம், வைகை ஆற்றங்கரை) — சங்ககால நகர நாகரிகம்; ஆதிச்சநல்லூர் (தூத்துக்குடி மாவட்டம், தாமிரபரணிக் கரை) — தாழிகள்.', 'Indus Valley Civilisation: Harappa (first excavated in 1921), Mohenjo-daro (the Great Bath), Lothal (a dockyard). Tamil Nadu: Keezhadi (Sivaganga district, on the Vaigai) — a Sangam-age urban settlement; Adichanallur (Thoothukudi district, on the Thamirabarani) — burial urns.')},
  pairs([['🛁','"பெருங்குளம்" கண்டெடுக்கப்பட்ட இடம்?','Where was the "Great Bath" found?','மொகஞ்சதாரோ','Mohenjo-daro'],['⚓','சிந்துவெளியின் கப்பல் துறை உள்ள இடம்?','Which Indus site had a dockyard?','லோத்தல்','Lothal'],['⛏️','1921-ல் முதலில் அகழாய்வு செய்த சிந்துவெளி நகரம்?','Which Indus city was excavated first, in 1921?','ஹரப்பா','Harappa']], 's')
  .concat(pairs([['🏺','கீழடி எந்த மாவட்டத்தில் உள்ளது?','Keezhadi is in which district?','சிவகங்கை','Sivaganga'],['⚱️','ஆதிச்சநல்லூர் எந்த மாவட்டத்தில் உள்ளது?','Adichanallur is in which district?','தூத்துக்குடி','Thoothukudi']], 'd'))
  .concat([{e:'🏞️', q:S('கீழடி எந்த ஆற்றின் கரையில் உள்ளது?', 'Keezhadi lies near which river?'), a:S('வைகை','Vaigai'), alts:[S('காவிரி','Kaveri'), S('தாமிரபரணி','Thamirabarani'), S('பாலாறு','Palar')]}]));
M.riverSource = pairGame({title:S('ஆறுகள் எங்கே தொடங்குகின்றன?', 'Where do rivers begin?'), icon:'🏞️',
  intro:S('காவிரி — தலைக்காவிரி (கர்நாடகா, குடகு மலை). கங்கை — கங்கோத்ரி பனியாறு (உத்தராகண்ட்). யமுனை — யமுனோத்ரி (உத்தராகண்ட்). கோதாவரி — திரியம்பகேஸ்வர் (மகாராஷ்டிரா). கிருஷ்ணா — மகாபலேஸ்வர் (மகாராஷ்டிரா). நர்மதை — அமர்கண்டக் (மத்தியப் பிரதேசம்).', 'Kaveri — Talakaveri (Kodagu hills, Karnataka). Ganga — Gangotri glacier (Uttarakhand). Yamuna — Yamunotri (Uttarakhand). Godavari — Trimbakeshwar (Maharashtra). Krishna — Mahabaleshwar (Maharashtra). Narmada — Amarkantak (Madhya Pradesh).')},
  pairs([['🌊','காவிரி தோன்றும் இடம்?','Where does the Kaveri begin?','தலைக்காவிரி','Talakaveri'],['🌊','கங்கை தோன்றும் இடம்?','Where does the Ganga begin?','கங்கோத்ரி','Gangotri'],['🌊','யமுனை தோன்றும் இடம்?','Where does the Yamuna begin?','யமுனோத்ரி','Yamunotri'],
    ['🌊','கோதாவரி தோன்றும் இடம்?','Where does the Godavari begin?','திரியம்பகேஸ்வர்','Trimbakeshwar'],['🌊','கிருஷ்ணா தோன்றும் இடம்?','Where does the Krishna begin?','மகாபலேஸ்வர்','Mahabaleshwar'],['🌊','நர்மதை தோன்றும் இடம்?','Where does the Narmada begin?','அமர்கண்டக்','Amarkantak']]));
M.latitudes = pairGame({title:S('அட்சரேகை, தீர்க்கரேகை', 'Latitudes & longitudes'), icon:'🌐',
  intro:S('நிலநடுக்கோடு 0° அட்சரேகை. கடகரேகை 23½° வடக்கு (இந்தியாவின் நடுவே செல்கிறது!). மகரரேகை 23½° தெற்கு. ஆர்க்டிக் வட்டம் 66½° வடக்கு, அண்டார்டிக் வட்டம் 66½° தெற்கு. முதன்மைத் தீர்க்கரேகை 0° (கிரீன்விச், இலண்டன்). இந்தியத் திட்டத் தீர்க்கரேகை 82½° கிழக்கு.', 'The Equator is 0° latitude. Tropic of Cancer 23½° N (it passes through the middle of India!). Tropic of Capricorn 23½° S. Arctic Circle 66½° N, Antarctic Circle 66½° S. Prime Meridian 0° (Greenwich, London). India’s standard meridian 82½° E.')},
  pairs([['🌍','நிலநடுக்கோடு?','The Equator?','0° அட்சரேகை','0° latitude'],['🌍','கடகரேகை?','Tropic of Cancer?','23½° வடக்கு','23½° N'],['🌍','மகரரேகை?','Tropic of Capricorn?','23½° தெற்கு','23½° S'],['❄️','ஆர்க்டிக் வட்டம்?','Arctic Circle?','66½° வடக்கு','66½° N'],
    ['🧊','அண்டார்டிக் வட்டம்?','Antarctic Circle?','66½° தெற்கு','66½° S'],['🕐','முதன்மைத் தீர்க்கரேகை (கிரீன்விச்)?','Prime Meridian (Greenwich)?','0° தீர்க்கரேகை','0° longitude'],['🇮🇳','இந்தியத் திட்டத் தீர்க்கரேகை?','India’s standard meridian?','82½° கிழக்கு','82½° E']]));
const cq = (e, qt, qe, at, ae, alts) => ({e, q:S(qt, qe), a:S(at, ae), alts: alts.map(([t, n]) => S(t, n))});
M.constitution = pairGame({title:S('நம் அரசியலமைப்பு', 'Our Constitution'), icon:'📜',
  intro:S('அரசியலமைப்பு 1949 நவம்பர் 26 அன்று ஏற்கப்பட்டது (அரசியலமைப்பு தினம்), 1950 ஜனவரி 26 அன்று நடைமுறைக்கு வந்தது. வரைவுக் குழுத் தலைவர் டாக்டர் பி.ஆர். அம்பேத்கர். அடிப்படை உரிமைகள் 6, அடிப்படைக் கடமைகள் 11. 6–14 வயதுக் குழந்தைகளுக்கு இலவசக் கட்டாயக் கல்வி உரிமை (2009). தகவல் அறியும் உரிமைச் சட்டம் 2005. பஞ்சாயத்து ராஜ் — 73-வது திருத்தம் (1992).', 'The Constitution was adopted on 26 November 1949 (Constitution Day) and came into force on 26 January 1950. The Drafting Committee was chaired by Dr B. R. Ambedkar. There are 6 Fundamental Rights and 11 Fundamental Duties. Children aged 6–14 have the right to free and compulsory education (2009). Right to Information Act 2005. Panchayati Raj — 73rd Amendment (1992).')},
  [cq('📜','அரசியலமைப்பு ஏற்கப்பட்ட நாள்?','When was the Constitution adopted?','26 நவம்பர் 1949','26 November 1949',[['26 ஜனவரி 1950','26 January 1950'],['15 ஆகஸ்ட் 1947','15 August 1947'],['2 அக்டோபர் 1949','2 October 1949']]),
   cq('🇮🇳','அரசியலமைப்பு நடைமுறைக்கு வந்த நாள்?','When did the Constitution come into force?','26 ஜனவரி 1950','26 January 1950',[['26 நவம்பர் 1949','26 November 1949'],['15 ஆகஸ்ட் 1947','15 August 1947'],['26 ஜனவரி 1947','26 January 1947']]),
   cq('✍️','வரைவுக் குழுத் தலைவர்?','Chairman of the Drafting Committee?','டாக்டர் பி.ஆர். அம்பேத்கர்','Dr B. R. Ambedkar',[['டாக்டர் இராஜேந்திர பிரசாத்','Dr Rajendra Prasad'],['ஜவஹர்லால் நேரு','Jawaharlal Nehru'],['சர்தார் வல்லபாய் படேல்','Sardar Vallabhbhai Patel']]),
   cq('🏛️','இந்தியாவின் முதல் குடியரசுத் தலைவர்?','India’s first President?','டாக்டர் இராஜேந்திர பிரசாத்','Dr Rajendra Prasad',[['டாக்டர் எஸ். இராதாகிருஷ்ணன்','Dr S. Radhakrishnan'],['டாக்டர் பி.ஆர். அம்பேத்கர்','Dr B. R. Ambedkar'],['டாக்டர் ஏ.பி.ஜே. அப்துல் கலாம்','Dr A. P. J. Abdul Kalam']]),
   cq('⚖️','அடிப்படை உரிமைகள் எத்தனை?','How many Fundamental Rights are there?','6','6',[['7','7'],['11','11'],['4','4']]),
   cq('🤲','அடிப்படைக் கடமைகள் எத்தனை?','How many Fundamental Duties are there?','11','11',[['6','6'],['10','10'],['12','12']]),
   cq('🎒','இலவசக் கட்டாயக் கல்வி உரிமை — எந்த வயதுக் குழந்தைகளுக்கு?','Right to free and compulsory education is for children aged…','6 முதல் 14 வயது','6 to 14 years',[['3 முதல் 10 வயது','3 to 10 years'],['5 முதல் 18 வயது','5 to 18 years'],['10 முதல் 16 வயது','10 to 16 years']]),
   cq('🔎','தகவல் அறியும் உரிமைச் சட்டம் வந்த ஆண்டு?','Year of the Right to Information Act?','2005','2005',[['2009','2009'],['1992','1992'],['1950','1950']]),
   cq('🏡','பஞ்சாயத்து ராஜுக்கு அரசியலமைப்பு அங்கீகாரம் தந்த திருத்தம்?','Which amendment gave Panchayati Raj constitutional status?','73-வது திருத்தம் (1992)','73rd Amendment (1992)',[['42-வது திருத்தம் (1976)','42nd Amendment (1976)'],['86-வது திருத்தம் (2002)','86th Amendment (2002)'],['61-வது திருத்தம் (1988)','61st Amendment (1988)']])]);
M.sectors = sortGame({title:S('பொருளாதாரத் துறைகள்', 'Sectors of the economy'), icon:'🏭',
  intro:S('முதன்மைத் துறை — இயற்கையிலிருந்து நேரடியாக (விவசாயம், மீன்பிடித்தல், சுரங்கம், பால்பண்ணை). இரண்டாம் துறை — பொருள்களைத் தயாரித்தல் (ஆலை, தொழிற்சாலை, கட்டுமானம்). மூன்றாம் துறை — சேவைகள் (வங்கி, கற்பித்தல், போக்குவரத்து, மருத்துவம், மென்பொருள்).', 'Primary sector — directly from nature (farming, fishing, mining, dairy). Secondary — making goods (mills, factories, construction). Tertiary — services (banking, teaching, transport, healthcare, software).'),
  ask:S('எந்தத் துறை?', 'Which sector?'), rule:S('இயற்கை → முதன்மை • தயாரிப்பு → இரண்டாம் • சேவை → மூன்றாம்', 'Nature → primary • making → secondary • service → tertiary')},
  [{id:'1', e:'🌾', ta:'முதன்மை', en:'Primary'}, {id:'2', e:'🏭', ta:'இரண்டாம்', en:'Secondary'}, {id:'3', e:'🏦', ta:'மூன்றாம்', en:'Tertiary'}],
  items([['🌾','நெல் விவசாயம்','rice farming','1'],['🎣','மீன்பிடித்தல்','fishing','1'],['⛏️','சுரங்கம்','mining','1'],['🐄','பால்பண்ணை','dairy farming','1'],
    ['🧵','துணி ஆலை','textile mill','2'],['🍬','சர்க்கரை ஆலை','sugar mill','2'],['🚗','கார் தொழிற்சாலை','car factory','2'],['🏗️','கட்டுமானம்','construction','2'],
    ['🏦','வங்கி','banking','3'],['👩‍🏫','கற்பித்தல்','teaching','3'],['🚌','போக்குவரத்து','transport','3'],['🩺','மருத்துவம்','healthcare','3'],['💻','மென்பொருள் சேவை','software services','3']]), 6);
M.revolutions = pairGame({title:S('இந்தியாவின் புரட்சிகள்', 'India’s revolutions in farming'), icon:'🌾',
  intro:S('பசுமைப் புரட்சி — உணவு தானிய உற்பத்தி (டாக்டர் எம்.எஸ். சுவாமிநாதன்). வெண்மைப் புரட்சி (ஆப்பரேஷன் ஃபிளட்) — பால் உற்பத்தி (டாக்டர் வர்கீஸ் குரியன்); இன்று உலகிலேயே அதிகப் பால் உற்பத்தி செய்யும் நாடு இந்தியா. நீலப் புரட்சி — மீன். மஞ்சள் புரட்சி — எண்ணெய் வித்துகள்.', 'Green Revolution — food grains (Dr M. S. Swaminathan). White Revolution (Operation Flood) — milk (Dr Verghese Kurien); India is now the world’s largest milk producer. Blue Revolution — fish. Yellow Revolution — oilseeds.')},
  pairs([['🌾','பசுமைப் புரட்சி — எதன் உற்பத்தி?','Green Revolution — production of…','உணவு தானியங்கள்','food grains'],['🥛','வெண்மைப் புரட்சி — எதன் உற்பத்தி?','White Revolution — production of…','பால்','milk'],['🐟','நீலப் புரட்சி — எதன் உற்பத்தி?','Blue Revolution — production of…','மீன்','fish'],['🌻','மஞ்சள் புரட்சி — எதன் உற்பத்தி?','Yellow Revolution — production of…','எண்ணெய் வித்துகள்','oilseeds']], 'r')
  .concat([cq('👨‍🔬','இந்தியப் பசுமைப் புரட்சியின் தந்தை?','Father of India’s Green Revolution?','டாக்டர் எம்.எஸ். சுவாமிநாதன்','Dr M. S. Swaminathan',[['டாக்டர் வர்கீஸ் குரியன்','Dr Verghese Kurien'],['டாக்டர் சி.வி. ராமன்','Dr C. V. Raman'],['டாக்டர் விக்ரம் சாராபாய்','Dr Vikram Sarabhai']]),
    cq('🐄','வெண்மைப் புரட்சியின் தந்தை?','Father of the White Revolution?','டாக்டர் வர்கீஸ் குரியன்','Dr Verghese Kurien',[['டாக்டர் எம்.எஸ். சுவாமிநாதன்','Dr M. S. Swaminathan'],['டாக்டர் ஹோமி பாபா','Dr Homi Bhabha'],['டாக்டர் விக்ரம் சாராபாய்','Dr Vikram Sarabhai']])]));

/* ================= LIFE SKILLS ================= */
M.onlineSafety = sortGame({title:S('இணையப் பாதுகாப்பு', 'Staying safe online'), icon:'🔐',
  intro:S('இணையம் ஒரு பெரிய நகரம் — நல்ல இடங்களும் ஆபத்தான இடங்களும் உண்டு. கடவுச்சொல், OTP, வீட்டு முகவரியை யாரிடமும் பகிராதே. தெரியாதவர் அனுப்பும் "பரிசு" இணைப்பைத் தொடாதே. ஏதாவது பயமுறுத்தினால் உடனே பெற்றோரிடம் சொல். ஒரு செய்தியைப் பகிரும் முன் சரிபார்.', 'The internet is a big city — with good places and dangerous ones. Never share passwords, OTPs or your home address. Don’t tap "prize" links from strangers. If something online scares you, tell a parent at once. Check news before you share it.'),
  ask:S('பாதுகாப்பானதா, ஆபத்தானதா?', 'Safe or unsafe?'), rule:S('தனிப்பட்ட தகவல் பகிர்வு, தெரியாத இணைப்புகள் → ஆபத்து • பெற்றோரிடம் சொல்வது, சரிபார்ப்பது → பாதுகாப்பு', 'Sharing private info, unknown links → unsafe • telling parents, checking → safe')},
  [{id:'s', e:'✅', ta:'பாதுகாப்பானது', en:'Safe'}, {id:'u', e:'⚠️', ta:'ஆபத்தானது', en:'Unsafe'}],
  items([['🔑','வலுவான கடவுச்சொல் வைத்தல்','using a strong password','s'],['👨‍👩‍👧','பயமுறுத்தும் செய்தியைப் பெற்றோரிடம் சொல்லுதல்','telling parents about a scary message','s'],['🔎','செய்தியைப் பகிரும் முன் சரிபார்த்தல்','checking news before sharing','s'],['🚪','பொதுக் கணினியில் log out செய்தல்','logging out on a shared computer','s'],['🙅','தெரியாதவரின் நட்பு அழைப்பை மறுத்தல்','declining a stranger’s friend request','s'],
    ['🔢','OTP-யை அழைப்பவரிடம் சொல்லுதல்','telling a caller your OTP','u'],['🎁','"பரிசு வென்றீர்கள்" இணைப்பைத் தொடுதல்','tapping a "you won a prize" link','u'],['🏠','வீட்டு முகவரியைப் பொதுவில் பதிவிடுதல்','posting your home address publicly','u'],['📸','தெரியாதவருக்குப் புகைப்படம் அனுப்புதல்','sending photos to a stranger','u'],['🗝️','நண்பனிடம் கடவுச்சொல் பகிர்தல்','sharing your password with a friend','u']]), 6);
M.needsWants = sortGame({title:S('தேவையா, விருப்பமா?', 'Need or want?'), icon:'💰',
  intro:S('தேவை = வாழ அவசியம் (உணவு, நீர், உடை, வீடு, மருந்து, கல்வி). விருப்பம் = இருந்தால் மகிழ்ச்சி, இல்லாவிட்டாலும் வாழலாம் (பொம்மை, புதிய போன், சினிமா). பணத்தை முதலில் தேவைக்கு, பிறகு சேமிப்பு, மீதி விருப்பத்துக்கு — இதுவே புத்திசாலித்தனமான பட்ஜெட்!', 'Need = necessary to live (food, water, clothes, home, medicine, education). Want = nice to have, but we can live without it (toys, a new phone, a movie). Spend on needs first, then save, then wants — that’s a smart budget!'),
  ask:S('தேவையா, விருப்பமா?', 'Need or want?'), rule:S('வாழ அவசியம் → தேவை', 'Necessary to live → need')},
  [{id:'n', e:'🏠', ta:'தேவை', en:'Need'}, {id:'w', e:'🎁', ta:'விருப்பம்', en:'Want'}],
  items([['🍚','உணவு','food','n'],['💧','குடிநீர்','drinking water','n'],['📚','பள்ளிப் புத்தகங்கள்','school books','n'],['💊','மருந்து','medicine','n'],['🏠','வீடு','a home','n'],['🧥','குளிருக்கு உடை','clothes for the weather','n'],
    ['🎮','வீடியோ கேம்','video game','w'],['📱','புதிய மாடல் போன்','latest phone model','w'],['👟','பிராண்ட் ஷூ','branded shoes','w'],['🎬','சினிமா டிக்கெட்','cinema ticket','w'],['🍔','துரித உணவு','fast food','w'],['🧸','பொம்மை','toy','w']]), 6);

/* ================= LANGUAGES ================= */
M.langFamily = sortGame({title:S('இந்திய மொழிக் குடும்பங்கள்', 'Language families of India'), icon:'🌳',
  intro:S('திராவிட மொழிக் குடும்பம்: தமிழ், தெலுங்கு, கன்னடம், மலையாளம், துளு — தமிழ் இவற்றில் மிகப் பழமையான இலக்கியம் கொண்டது. இந்தோ-ஆரிய மொழிக் குடும்பம்: இந்தி, வங்காளம், மராத்தி, குஜராத்தி, பஞ்சாபி, ஒடியா. இரண்டும் சேர்ந்ததே இந்தியாவின் செல்வம்!', 'Dravidian family: Tamil, Telugu, Kannada, Malayalam, Tulu — Tamil has the oldest literature among them. Indo-Aryan family: Hindi, Bengali, Marathi, Gujarati, Punjabi, Odia. Together they are India’s treasure!'),
  ask:S('எந்த மொழிக் குடும்பம்?', 'Which language family?'), rule:S('தென்னிந்திய மொழிகள் பெரும்பாலும் திராவிடம்', 'Most South Indian languages are Dravidian')},
  [{id:'d', e:'🌴', ta:'திராவிடம்', en:'Dravidian'}, {id:'a', e:'🏔️', ta:'இந்தோ-ஆரியம்', en:'Indo-Aryan'}],
  items([['அ','தமிழ்','Tamil','d'],['అ','தெலுங்கு','Telugu','d'],['ಅ','கன்னடம்','Kannada','d'],['അ','மலையாளம்','Malayalam','d'],['🗣️','துளு','Tulu','d'],
    ['अ','இந்தி','Hindi','a'],['অ','வங்காளம்','Bengali','a'],['म','மராத்தி','Marathi','a'],['અ','குஜராத்தி','Gujarati','a'],['ਅ','பஞ்சாபி','Punjabi','a'],['ଅ','ஒடியா','Odia','a']]), 6);
M.tamilToEnglish = pairGame({title:S('ஆங்கிலத்துக்குச் சென்ற தமிழ்ச் சொற்கள்', 'Tamil words in English'), icon:'🚢',
  intro:S('தமிழ் உலகுக்குச் சொற்களைக் கொடுத்திருக்கிறது! கட்டுமரம் → catamaran, கறி → curry, மிளகுத் தண்ணீர் → mulligatawny, பந்தல் → pandal, மாங்காய் → mango (போர்த்துகீசியர் வழியாக).', 'Tamil has given words to the world! கட்டுமரம் (kattumaram) → catamaran, கறி (kari) → curry, மிளகுத் தண்ணீர் (milagu thanni) → mulligatawny, பந்தல் (pandal) → pandal, மாங்காய் (maangai) → mango (via Portuguese).')},
  pairs([['⛵','"கட்டுமரம்" எந்த ஆங்கிலச் சொல்லானது?','"Kattumaram" became which English word?','catamaran','catamaran'],['🍛','"கறி" எந்த ஆங்கிலச் சொல்லானது?','"Kari" became which English word?','curry','curry'],['🍲','"மிளகுத் தண்ணீர்" எந்த ஆங்கிலச் சொல்லானது?','"Milagu thanni" became which English word?','mulligatawny','mulligatawny'],
    ['⛺','"பந்தல்" எந்த ஆங்கிலச் சொல்லானது?','"Pandal" became which English word?','pandal','pandal'],['🥭','"மாங்காய்" எந்த ஆங்கிலச் சொல்லானது?','"Maangai" became which English word?','mango','mango']], 'w'));
})(typeof window !== 'undefined' ? window : globalThis);
