/* Kalvi Kalanjiyam — Classes 9–10: curated fact games + generated English grammar.
   Only well-established textbook facts (Samacheer / NCERT); anything disputed is left out. */
(function(G){
'use strict';
const {S, pick, shuffle} = G.KALVI_UTIL;
const {pairGame, sortGame} = G.KALVI_BUILD;
const {opts} = G.KALVI_MID_UTIL;
const H = G.KALVI_HIGH;
const items = arr => arr.map(([e, ta, en, bin]) => ({e, ta, en, bin}));
const pairs = (arr, grp) => arr.map(([e, qta, qen, ata, aen]) => ({e, grp, q:S(qta, qen), a:S(ata, aen)}));
const cq = (e, qt, qe, at, ae, alts) => ({e, q:S(qt, qe), a:S(at, ae), alts: alts.map(([t, n]) => S(t, n))});

/* ================= TAMIL ================= */
H.vetrumai = pairGame({title:S('வேற்றுமை உருபுகள்', 'Case markers (vetrumai)'), icon:'🔗',
  intro:S('பெயர்ச்சொல்லின் பொருளை வேறுபடுத்துவது வேற்றுமை. முதல் வேற்றுமை (எழுவாய்) — உருபு இல்லை. இரண்டாம் — ஐ (பாடத்தை). மூன்றாம் — ஆல், ஓடு, ஒடு (கத்தியால்). நான்காம் — கு (அம்மாவுக்கு). ஐந்தாம் — இன், இல் (மரத்தின் நின்று). ஆறாம் — அது (என்னது). ஏழாம் — கண் (வீட்டின்கண்). எட்டாம் — விளி (அம்மா!).', 'Vetrumai changes the role of a noun. 1st (subject) — no marker. 2nd — ஐ (பாடத்தை). 3rd — ஆல், ஓடு, ஒடு (கத்தியால்). 4th — கு (அம்மாவுக்கு). 5th — இன், இல். 6th — அது. 7th — கண். 8th — calling (அம்மா!).')},
  [['ஐ','இரண்டாம் வேற்றுமை','2nd case'],['ஆல்','மூன்றாம் வேற்றுமை','3rd case'],['கு','நான்காம் வேற்றுமை','4th case'],['இன்','ஐந்தாம் வேற்றுமை','5th case'],['அது','ஆறாம் வேற்றுமை','6th case'],['கண்','ஏழாம் வேற்றுமை','7th case']]
    .map(([u, ta, en]) => ({e:'🔗', q:S(`"${u}" எந்த வேற்றுமையின் உருபு?`, `"${u}" is the marker of which case?`), a:S(ta, en)})));
H.tamilLit2 = pairGame({title:S('தமிழ் இலக்கியச் செல்வம்', 'Treasures of Tamil literature'), icon:'📚',
  intro:S('ஐம்பெருங்காப்பியங்கள்: சிலப்பதிகாரம், மணிமேகலை, சீவக சிந்தாமணி, வளையாபதி, குண்டலகேசி. சீவக சிந்தாமணி — திருத்தக்கத் தேவர்; குண்டலகேசி — நாதகுத்தனார்; பெரியபுராணம் — சேக்கிழார்; திருவாசகம் — மாணிக்கவாசகர். பட்டங்கள்: மகாகவி — பாரதியார்; புரட்சிக்கவி — பாரதிதாசன்; கவிமணி — தேசிக விநாயகம் பிள்ளை; தமிழ்த் தாத்தா — உ. வே. சாமிநாதையர் (பழைய ஓலைச்சுவடிகளைத் தேடிப் பதிப்பித்தவர்). பொன்னியின் செல்வன் — கல்கி.', 'The five great epics: Silappathikaram, Manimegalai, Seevaka Chinthamani, Valayapathi, Kundalakesi. Seevaka Chinthamani — Thiruthakka Thevar; Kundalakesi — Nathakuthanar; Periyapuranam — Sekkizhar; Thiruvasagam — Manikkavasagar. Titles: Mahakavi — Bharathiyar; Puratchi Kavi — Bharathidasan; Kavimani — Desigavinayagam Pillai; Tamil Thatha — U. Ve. Saminatha Iyer (who found and published old palm-leaf manuscripts). Ponniyin Selvan — Kalki.')},
  pairs([['📜','"சீவக சிந்தாமணி" எழுதியவர்?','Who wrote "Seevaka Chinthamani"?','திருத்தக்கத் தேவர்','Thiruthakka Thevar'],['📜','"குண்டலகேசி" எழுதியவர்?','Who wrote "Kundalakesi"?','நாதகுத்தனார்','Nathakuthanar'],['📜','"பெரியபுராணம்" எழுதியவர்?','Who wrote "Periyapuranam"?','சேக்கிழார்','Sekkizhar'],
    ['📜','"திருவாசகம்" எழுதியவர்?','Who wrote "Thiruvasagam"?','மாணிக்கவாசகர்','Manikkavasagar'],['📜','"சிலப்பதிகாரம்" எழுதியவர்?','Who wrote "Silappathikaram"?','இளங்கோவடிகள்','Ilango Adigal'],['📖','"பொன்னியின் செல்வன்" எழுதியவர்?','Who wrote "Ponniyin Selvan"?','கல்கி','Kalki'],['📖','"பாஞ்சாலி சபதம்" எழுதியவர்?','Who wrote "Panchali Sabatham"?','பாரதியார்','Bharathiyar'],['📖','"குடும்ப விளக்கு" எழுதியவர்?','Who wrote "Kudumba Vilakku"?','பாரதிதாசன்','Bharathidasan']], 'a')
  .concat(pairs([['🏅','"மகாகவி" என்று போற்றப்படுபவர்?','Who is called "Mahakavi"?','பாரதியார்','Bharathiyar'],['🏅','"புரட்சிக்கவி" என்று போற்றப்படுபவர்?','Who is called "Puratchi Kavi"?','பாரதிதாசன்','Bharathidasan'],['🏅','"கவிமணி" என்று போற்றப்படுபவர்?','Who is called "Kavimani"?','தேசிக விநாயகம் பிள்ளை','Desigavinayagam Pillai'],['🏅','"தமிழ்த் தாத்தா" என்று போற்றப்படுபவர்?','Who is called "Tamil Thatha"?','உ. வே. சாமிநாதையர்','U. Ve. Saminatha Iyer']], 't'))
  .concat([cq('📚','ஐம்பெருங்காப்பியங்கள் எத்தனை?','How many great epics (aimperum kappiyangal)?','5','5',[['8','8'],['10','10'],['18','18']]), cq('📚','எட்டுத்தொகை — எத்தனை நூல்கள்?','How many works are in Ettuthogai?','8','8',[['10','10'],['18','18'],['5','5']]), cq('📚','பத்துப்பாட்டு — எத்தனை நூல்கள்?','How many works are in Pathupattu?','10','10',[['8','8'],['18','18'],['5','5']]), cq('📚','பதினெண்கீழ்க்கணக்கு — எத்தனை நூல்கள்?','How many works are in Pathinenkeezhkanakku?','18','18',[['8','8'],['10','10'],['5','5']])]));

/* ================= ENGLISH (generated) ================= */
const PV = [['kick','kicked'],['paint','painted'],['clean','cleaned'],['open','opened'],['write','written'],['build','built'],['eat','eaten'],['sing','sung'],['draw','drawn'],['teach','taught'],['catch','caught'],['make','made']];
const PAST = {kick:'kicked', paint:'painted', clean:'cleaned', open:'opened', write:'wrote', build:'built', eat:'ate', sing:'sang', draw:'drew', teach:'taught', catch:'caught', make:'made'};
const SO = {kick:[['The boy','the ball']], paint:[['Ravi','the wall']], clean:[['Meena','the room']], open:[['The guard','the gate']], write:[['Priya','a letter']], build:[['The workers','the bridge']], eat:[['The cat','the fish']], sing:[['The children','a song']], draw:[['Arun','a map']], teach:[['Mrs. Latha','the lesson']], catch:[['The fielder','the ball']], make:[['Grandmother','the sweets']]};
const cap = s => s[0].toUpperCase() + s.slice(1), low = s => /^(The|A) /.test(s) ? s[0].toLowerCase() + s.slice(1) : s;
H.passive = { title:S('Active → Passive voice', 'Active → Passive voice'), icon:'🔄',
  intro:S('Active: "The boy kicks the ball." (செய்பவர் முதலில்). Passive: "The ball is kicked by the boy." (பொருள் முதலில்). வடிவம்: be + V3 (past participle) + by. Present: is/are + V3. Past: was/were + V3.', 'Active: "The boy kicks the ball." (doer first). Passive: "The ball is kicked by the boy." (object first). Form: be + V3 (past participle) + by. Present: is/are + V3. Past: was/were + V3.'),
  gen(){ const [v, v3] = pick(PV), [sub, obj] = SO[v][0], past = Math.random() < .5, plSub = /workers|children/.test(sub), plObj = /sweets/.test(obj);
    const v1s = plSub ? v : (v === 'teach' || v === 'catch' ? v + 'es' : v + 's'), act = `${sub} ${past ? PAST[v] : v1s} ${obj}.`, be = past ? (plObj ? 'were' : 'was') : (plObj ? 'are' : 'is');
    const ans = `${cap(obj)} ${be} ${v3} by ${low(sub)}.`, wrongBe = past ? (plObj ? 'was' : 'were') : (plObj ? 'is' : 'are'), otherTense = past ? (plObj ? 'are' : 'is') : (plObj ? 'were' : 'was');
    return {p:S(`Passive voice: "${act}"`, `Change to passive voice: "${act}"`), scene:'', opts: opts(ans, [`${cap(obj)} ${wrongBe} ${v3} by ${low(sub)}.`, `${cap(obj)} ${otherTense} ${v3} by ${low(sub)}.`, `${cap(obj)} ${be} ${past ? PAST[v] : v} by ${low(sub)}.`, `${sub} ${be} ${v3} by ${obj}.`].filter(x => x !== ans), x => x), ans,
      ex:S(`${past ? 'Past' : 'Present'} → ${be} + V3 (${v3})`, `${past ? 'Past' : 'Present'} → ${be} + V3 (${v3})`), data:{v, past, plObj}}; } };
const TAGS = [['He','he'],['She','she'],['They','they'],['You','you'],['We','we'],['It','it'],['Priya','she'],['The boys','they']];
const AUX = {is:["isn't",'is'], are:["aren't",'are'], was:["wasn't",'was'], were:["weren't",'were'], can:["can't",'can'], will:["won't",'will'], has:["hasn't",'has'], have:["haven't",'have']};
const REST = {is:'ready', are:'ready', was:'late', were:'late', can:'swim', will:'come tomorrow', has:'finished the work', have:'finished the work'};
H.questionTag = { title:S('Question tags', 'Question tags'), icon:'❓',
  intro:S('நேர்மறை வாக்கியம் → எதிர்மறை tag: "She is ready, isn’t she?" எதிர்மறை வாக்கியம் → நேர்மறை tag: "They can’t swim, can they?" அதே துணை வினை (is, can, will…), பெயருக்குப் பதில் pronoun.', 'Positive sentence → negative tag: "She is ready, isn’t she?" Negative sentence → positive tag: "They can’t swim, can they?" Use the same helping verb (is, can, will…) and a pronoun.'),
  gen(){ const [sub, pr] = pick(TAGS), pl = /^(They|You|We|The boys)$/.test(sub);
    const auxes = pl ? ['are', 'were', 'can', 'will', 'have'] : ['is', 'was', 'can', 'will', 'has'], aux = pick(auxes), neg = Math.random() < .4;
    const sent = `${sub} ${neg ? AUX[aux][0] : aux} ${REST[aux]}`, ans = `${neg ? AUX[aux][1] : AUX[aux][0]} ${pr}?`;
    const w = [`${neg ? AUX[aux][0] : AUX[aux][1]} ${pr}?`, `${neg ? AUX[aux][1] : AUX[aux][0]} ${sub === pr ? (pr === 'he' ? 'she' : 'it') : sub.toLowerCase()}?`, `${pick(Object.keys(AUX).filter(x => x !== aux))}${neg ? '' : "n't"} ${pr}?`.replace("willn't", "won't").replace("cann't", "can't")];
    return {p:S(`${sent}, ___`, `${sent}, ___`), scene:'', opts: opts(ans, w.filter(x => x !== ans), x => x), ans, ex:S(`${neg ? 'எதிர்மறை → நேர்மறை tag' : 'நேர்மறை → எதிர்மறை tag'}: ${sent}, ${ans}`, `${neg ? 'Negative → positive tag' : 'Positive → negative tag'}: ${sent}, ${ans}`), data:{aux, neg, pr}}; } };

/* ================= SCIENCE ================= */
H.hormones = pairGame({title:S('ஹார்மோன்கள்', 'Hormones'), icon:'🧬',
  intro:S('விலங்கு ஹார்மோன்கள்: இன்சுலின் — கணையம் (இரத்தச் சர்க்கரையைக் குறைக்கும்); தைராக்சின் — தைராய்டு (வளர்சிதை மாற்றம்); அட்ரினலின் — அட்ரீனல் ("சண்டை அல்லது ஓட்டம்"); வளர்ச்சி ஹார்மோன் — பிட்யூட்டரி. தாவர ஹார்மோன்கள்: ஆக்சின் — வளர்ச்சி, ஒளிநாட்டம்; ஜிப்ரலின் — தண்டு நீளுதல்; சைட்டோகைனின் — செல் பிரிதல்; அப்சிசிக் அமிலம் — அழுத்தம், உறக்கநிலை; எத்திலீன் — பழம் பழுத்தல்.', 'Animal hormones: insulin — pancreas (lowers blood sugar); thyroxine — thyroid (metabolism); adrenaline — adrenal ("fight or flight"); growth hormone — pituitary. Plant hormones: auxin — growth, bending to light; gibberellin — stem elongation; cytokinin — cell division; abscisic acid — stress, dormancy; ethylene — fruit ripening.')},
  pairs([['🩸','இன்சுலினைச் சுரப்பது?','Which gland makes insulin?','கணையம்','pancreas'],['🦋','தைராக்சினைச் சுரப்பது?','Which gland makes thyroxine?','தைராய்டு','thyroid'],['😨','அட்ரினலினைச் சுரப்பது?','Which gland makes adrenaline?','அட்ரீனல் சுரப்பி','adrenal gland'],['📏','வளர்ச்சி ஹார்மோனைச் சுரப்பது?','Which gland makes growth hormone?','பிட்யூட்டரி','pituitary']], 'g')
  .concat(pairs([['🍌','பழம் பழுக்க உதவும் தாவர ஹார்மோன்?','Plant hormone that ripens fruit?','எத்திலீன்','ethylene'],['🌱','தண்டு நீளுதலுக்கு உதவும் தாவர ஹார்மோன்?','Plant hormone for stem elongation?','ஜிப்ரலின்','gibberellin'],['☀️','ஒளியை நோக்கி வளைய உதவும் தாவர ஹார்மோன்?','Plant hormone behind bending towards light?','ஆக்சின்','auxin'],['🔬','செல் பிரிதலைத் தூண்டும் தாவர ஹார்மோன்?','Plant hormone that promotes cell division?','சைட்டோகைனின்','cytokinin'],['🍂','அழுத்த (stress) ஹார்மோன் — இலை உதிர்தல், உறக்கநிலை?','Plant "stress hormone" — leaf fall, dormancy?','அப்சிசிக் அமிலம்','abscisic acid']], 'p')));
H.brain = pairGame({title:S('மூளையின் பகுதிகள்', 'Parts of the brain'), icon:'🧠',
  intro:S('பெருமூளை (cerebrum) — சிந்தனை, நினைவு, பேச்சு, தன்னிச்சைச் செயல்கள். சிறுமூளை (cerebellum) — உடல் சமநிலை, இயக்க ஒருங்கிணைப்பு. முகுளம் (medulla) — இதயத்துடிப்பு, சுவாசம் போன்ற தன்னிச்சையற்ற செயல்கள். தண்டுவடம் — மறிவினை (reflex).', 'Cerebrum — thinking, memory, speech, voluntary actions. Cerebellum — balance and coordination. Medulla — involuntary actions like heartbeat and breathing. Spinal cord — reflex actions.')},
  pairs([['💭','சிந்தனை, நினைவு எந்தப் பகுதி?','Thinking and memory are controlled by the…','பெருமூளை','cerebrum'],['🤸','உடல் சமநிலை எந்தப் பகுதி?','Balance is controlled by the…','சிறுமூளை','cerebellum'],['❤️','இதயத்துடிப்பு, சுவாசம் எந்தப் பகுதி?','Heartbeat and breathing are controlled by the…','முகுளம்','medulla'],['🔥','சூடான பாத்திரத்திலிருந்து கையை உடனே இழுப்பது (மறிவினை)?','Pulling your hand from a hot pan (reflex) is handled by the…','தண்டுவடம்','spinal cord']]));
H.phyla = pairGame({title:S('விலங்குலகம் — தொகுதிகள்', 'Animal kingdom — phyla'), icon:'🐙',
  intro:S('துளையுடலிகள் (Porifera) — கடற்பஞ்சு. குழியுடலிகள் (Cnidaria) — ஹைட்ரா, ஜெல்லி மீன். தட்டைப்புழுக்கள் — நாடாப்புழு. உருளைப்புழுக்கள் — அஸ்காரிஸ். வளைதசைப்புழுக்கள் (Annelida) — மண்புழு. கணுக்காலிகள் (Arthropoda) — பூச்சிகள், நண்டு (மிகப் பெரிய தொகுதி!). மெல்லுடலிகள் (Mollusca) — நத்தை, ஆக்டோபஸ். முட்தோலிகள் (Echinodermata) — நட்சத்திர மீன். முதுகுநாணிகள் (Chordata) — மீன் முதல் மனிதன் வரை.', 'Porifera — sponges. Cnidaria — Hydra, jellyfish. Platyhelminthes — tapeworm. Nematoda — Ascaris. Annelida — earthworm. Arthropoda — insects, crabs (the biggest phylum!). Mollusca — snail, octopus. Echinodermata — starfish. Chordata — from fish to humans.')},
  pairs([['🧽','கடற்பஞ்சு எந்தத் தொகுதி?','A sponge belongs to…','துளையுடலிகள் (Porifera)','Porifera'],['🪼','ஜெல்லி மீன் எந்தத் தொகுதி?','A jellyfish belongs to…','குழியுடலிகள் (Cnidaria)','Cnidaria'],['🪱','மண்புழு எந்தத் தொகுதி?','An earthworm belongs to…','வளைதசைப்புழுக்கள் (Annelida)','Annelida'],['🦀','நண்டு எந்தத் தொகுதி?','A crab belongs to…','கணுக்காலிகள் (Arthropoda)','Arthropoda'],
    ['🐙','ஆக்டோபஸ் எந்தத் தொகுதி?','An octopus belongs to…','மெல்லுடலிகள் (Mollusca)','Mollusca'],['⭐','நட்சத்திர மீன் எந்தத் தொகுதி?','A starfish belongs to…','முட்தோலிகள் (Echinodermata)','Echinodermata'],['🐟','மீன் எந்தத் தொகுதி?','A fish belongs to…','முதுகுநாணிகள் (Chordata)','Chordata'],['🎗️','நாடாப்புழு எந்தத் தொகுதி?','A tapeworm belongs to…','தட்டைப்புழுக்கள் (Platyhelminthes)','Platyhelminthes']]));
H.tropism = pairGame({title:S('தாவர இயக்கங்கள் (நாட்டங்கள்)', 'Plant movements (tropisms)'), icon:'🌻',
  intro:S('ஒளிநாட்டம் — ஒளியை நோக்கி (தண்டு). புவிநாட்டம் — புவியீர்ப்பை நோக்கி (வேர்). நீர்நாட்டம் — நீரை நோக்கி (வேர்). தொடுநாட்டம் — தொடுதலுக்கு (பற்றுக்கம்பி சுற்றுதல்).', 'Phototropism — towards light (stem). Geotropism — towards gravity (root). Hydrotropism — towards water (root). Thigmotropism — response to touch (tendrils coiling).')},
  pairs([['☀️','தண்டு ஒளியை நோக்கி வளைவது?','A stem bending towards light?','ஒளிநாட்டம்','phototropism'],['⬇️','வேர் கீழ்நோக்கி வளர்வது?','A root growing downwards (gravity)?','புவிநாட்டம்','geotropism'],['💧','வேர் நீரை நோக்கி வளர்வது?','A root growing towards water?','நீர்நாட்டம்','hydrotropism'],['🌿','பற்றுக்கம்பி குச்சியைச் சுற்றுவது?','A tendril coiling round a stick?','தொடுநாட்டம்','thigmotropism']]));
H.econBio = pairGame({title:S('பொருளாதார உயிரியல்', 'Economic biology'), icon:'🐝',
  intro:S('தேனீ வளர்ப்பு (apiculture) — தேன், மெழுகு. பட்டுப்புழு வளர்ப்பு (sericulture) — பட்டு. மீன் வளர்ப்பு (pisciculture) — மீன். மண்புழு உரம் (vermiculture) — இயற்கை உரம். தோட்டக்கலை (horticulture) — பழம், காய், மலர். கோழி வளர்ப்பு (poultry) — முட்டை, இறைச்சி.', 'Apiculture — honey and wax. Sericulture — silk. Pisciculture — fish. Vermiculture — earthworm compost. Horticulture — fruit, vegetables, flowers. Poultry — eggs and meat.')},
  pairs([['🐝','தேனீ வளர்ப்பு?','Rearing bees is called…','தேனீ வளர்ப்பு (apiculture)','apiculture'],['🐛','பட்டுப்புழு வளர்ப்பு?','Rearing silkworms is called…','பட்டு வளர்ப்பு (sericulture)','sericulture'],['🐟','மீன் வளர்ப்பு?','Rearing fish is called…','மீன் வளர்ப்பு (pisciculture)','pisciculture'],['🪱','மண்புழுவைக் கொண்டு உரம் தயாரித்தல்?','Making compost with earthworms is called…','மண்புழு உரம் (vermiculture)','vermiculture'],['🌺','பழம், காய், மலர் சாகுபடி?','Growing fruit, vegetables and flowers is called…','தோட்டக்கலை (horticulture)','horticulture']]));
H.scientists = pairGame({title:S('கண்டுபிடிப்பாளர்கள்', 'Discoverers'), icon:'🔬',
  intro:S('எட்வர்ட் ஜென்னர் — பெரியம்மைத் தடுப்பூசி (1796). லூயி பாஸ்டர் — வெறிநாய்க்கடித் தடுப்பூசி, பாஸ்டுரைசேஷன். அலெக்சாண்டர் ஃபிளமிங் — பெனிசிலின் (1928). ஜோனஸ் சால்க் — போலியோ தடுப்பூசி. கிரெகர் மெண்டல் — மரபியலின் தந்தை. சார்லஸ் டார்வின் — இயற்கைத் தேர்வு ("உயிரினங்களின் தோற்றம்", 1859). மைக்கேல் ஃபாரடே — மின்காந்தத் தூண்டல். ஹோமி பாபா — இந்திய அணுசக்தித் திட்டத்தின் தந்தை.', 'Edward Jenner — smallpox vaccine (1796). Louis Pasteur — rabies vaccine, pasteurisation. Alexander Fleming — penicillin (1928). Jonas Salk — polio vaccine. Gregor Mendel — father of genetics. Charles Darwin — natural selection ("On the Origin of Species", 1859). Michael Faraday — electromagnetic induction. Homi Bhabha — father of India’s nuclear programme.')},
  pairs([['💉','பெரியம்மைத் தடுப்பூசியைக் கண்டுபிடித்தவர்?','Who developed the smallpox vaccine?','எட்வர்ட் ஜென்னர்','Edward Jenner'],['🐕','வெறிநாய்க்கடித் தடுப்பூசி, பாஸ்டுரைசேஷன்?','Rabies vaccine and pasteurisation?','லூயி பாஸ்டர்','Louis Pasteur'],['🍄','பெனிசிலினைக் கண்டுபிடித்தவர்?','Who discovered penicillin?','அலெக்சாண்டர் ஃபிளமிங்','Alexander Fleming'],['🦵','போலியோ தடுப்பூசியை (ஊசி) உருவாக்கியவர்?','Who developed the injected polio vaccine?','ஜோனஸ் சால்க்','Jonas Salk'],
    ['🌱','மரபியலின் தந்தை?','Father of genetics?','கிரெகர் மெண்டல்','Gregor Mendel'],['🐢','இயற்கைத் தேர்வுக் கொள்கை?','Theory of natural selection?','சார்லஸ் டார்வின்','Charles Darwin'],['🧲','மின்காந்தத் தூண்டலைக் கண்டுபிடித்தவர்?','Who discovered electromagnetic induction?','மைக்கேல் ஃபாரடே','Michael Faraday'],['☢️','இந்திய அணுசக்தித் திட்டத்தின் தந்தை?','Father of India’s nuclear programme?','ஹோமி ஜே. பாபா','Homi J. Bhabha']]));
H.reactions = sortGame({title:S('வேதிவினைகளின் வகைகள்', 'Types of chemical reactions'), icon:'⚗️',
  intro:S('சேர்க்கை: A + B → AB (2Mg + O₂ → 2MgO). சிதைவு: AB → A + B (CaCO₃ → CaO + CO₂). இடப்பெயர்ச்சி: A + BC → AC + B (Zn + CuSO₄ → ZnSO₄ + Cu — வினைத்திறன் அதிகமானது வெளியேற்றும்). இரட்டை இடப்பெயர்ச்சி: AB + CD → AD + CB (AgNO₃ + NaCl → AgCl + NaNO₃).', 'Combination: A + B → AB (2Mg + O₂ → 2MgO). Decomposition: AB → A + B (CaCO₃ → CaO + CO₂). Displacement: A + BC → AC + B (Zn + CuSO₄ → ZnSO₄ + Cu — the more reactive one pushes out the other). Double displacement: AB + CD → AD + CB (AgNO₃ + NaCl → AgCl + NaNO₃).'),
  ask:S('எந்த வகை வினை?', 'Which type of reaction?'), rule:S('இணைதல் → சேர்க்கை • உடைதல் → சிதைவு • ஒன்று மாற்றும் → இடப்பெயர்ச்சி • இரண்டும் மாறும் → இரட்டை இடப்பெயர்ச்சி', 'Joining → combination • breaking → decomposition • one swaps → displacement • both swap → double displacement')},
  [{id:'c', e:'➕', ta:'சேர்க்கை', en:'Combination'}, {id:'d', e:'💥', ta:'சிதைவு', en:'Decomposition'}, {id:'s', e:'🔁', ta:'இடப்பெயர்ச்சி', en:'Displacement'}, {id:'x', e:'🔀', ta:'இரட்டை இடப்பெயர்ச்சி', en:'Double displacement'}],
  items([['','2H₂ + O₂ → 2H₂O','','c'],['','2Mg + O₂ → 2MgO','','c'],['','C + O₂ → CO₂','','c'],['','CaO + H₂O → Ca(OH)₂','','c'],['','CaCO₃ → CaO + CO₂','','d'],['','2H₂O → 2H₂ + O₂','','d'],['','2KClO₃ → 2KCl + 3O₂','','d'],
    ['','Zn + CuSO₄ → ZnSO₄ + Cu','','s'],['','Fe + CuSO₄ → FeSO₄ + Cu','','s'],['','Zn + 2HCl → ZnCl₂ + H₂','','s'],['','AgNO₃ + NaCl → AgCl + NaNO₃','','x'],['','BaCl₂ + Na₂SO₄ → BaSO₄ + 2NaCl','','x'],['','NaOH + HCl → NaCl + H₂O','','x']]), 8);
H.physicsFacts = pairGame({title:S('இயற்பியல் விதிகளும் உண்மைகளும்', 'Laws & facts of physics'), icon:'🧲',
  intro:S('ஃபிளெமிங்கின் இடக்கை விதி — மின்மோட்டார்; வலக்கை விதி — மின்னியற்றி (ஜெனரேட்டர்). ஆயர்ஸ்டெட் — மின்னோட்டம் காந்தப்புலத்தை உருவாக்கும். அணுக்கரு பிளவு — அணு உலைகள்; அணுக்கரு இணைவு — சூரியனின் ஆற்றல். மனிதக் காது 20 Hz முதல் 20,000 Hz வரை கேட்கும்; அதற்கு மேல் மீயொலி (வௌவால், SONAR, ஸ்கேன்). இந்தியாவின் முதல் அணுமின் நிலையம் தாராப்பூர் (1969); தமிழ்நாட்டில் கல்பாக்கம்.', 'Fleming’s left-hand rule — electric motor; right-hand rule — generator. Oersted — a current makes a magnetic field. Nuclear fission — nuclear reactors; nuclear fusion — the Sun’s energy. Human ears hear 20 Hz to 20,000 Hz; above that is ultrasound (bats, SONAR, scans). India’s first nuclear power station was Tarapur (1969); Tamil Nadu has Kalpakkam.')},
  [cq('✋','ஃபிளெமிங்கின் இடக்கை விதி எதற்கு?','Fleming’s left-hand rule applies to the…','மின்மோட்டார்','electric motor',[['மின்னியற்றி','generator'],['மின்மாற்றி','transformer'],['மின்கலம்','battery']]),
   cq('🤚','ஃபிளெமிங்கின் வலக்கை விதி எதற்கு?','Fleming’s right-hand rule applies to the…','மின்னியற்றி','generator',[['மின்மோட்டார்','electric motor'],['மின்விளக்கு','bulb'],['மின்கலம்','battery']]),
   cq('☀️','சூரியனின் ஆற்றலுக்குக் காரணம்?','The Sun’s energy comes from…','அணுக்கரு இணைவு','nuclear fusion',[['அணுக்கரு பிளவு','nuclear fission'],['நிலக்கரி எரிதல்','burning coal'],['வேதிவினை','a chemical reaction']]),
   cq('🏭','அணு உலைகளில் நடப்பது?','Nuclear reactors use…','அணுக்கரு பிளவு','nuclear fission',[['அணுக்கரு இணைவு','nuclear fusion'],['எரிதல்','burning'],['ஒளிச்சேர்க்கை','photosynthesis']]),
   cq('👂','மனிதன் கேட்கக்கூடிய ஒலி அலைவெண்?','Frequencies humans can hear?','20 Hz – 20,000 Hz','20 Hz – 20,000 Hz',[['2 Hz – 2,000 Hz','2 Hz – 2,000 Hz'],['200 Hz – 2,00,000 Hz','200 Hz – 200,000 Hz'],['0 Hz – 20 Hz','0 Hz – 20 Hz']]),
   cq('🦇','வௌவால், SONAR பயன்படுத்துவது?','Bats and SONAR use…','மீயொலி','ultrasound',[['குற்றொலி','infrasound'],['ஒளி','light'],['X-கதிர்','X-rays']]),
   cq('🧭','மின்னோட்டம் காந்தப்புலத்தை உருவாக்கும் என்று கண்டவர்?','Who found that an electric current makes a magnetic field?','ஆயர்ஸ்டெட்','Oersted',[['ஃபாரடே','Faraday'],['நியூட்டன்','Newton'],['ஓம்','Ohm']]),
   cq('⚡','இந்தியாவின் முதல் அணுமின் நிலையம்?','India’s first nuclear power station?','தாராப்பூர் (1969)','Tarapur (1969)',[['கல்பாக்கம்','Kalpakkam'],['கூடங்குளம்','Kudankulam'],['நரோரா','Narora']])]);
H.periodic = pairGame({title:S('தனிம வரிசை அட்டவணை', 'The periodic table'), icon:'🧪',
  intro:S('மெண்டலீஃப் (1869) — அணு நிறையின் அடிப்படையில் அட்டவணை, இன்னும் கண்டுபிடிக்கப்படாத தனிமங்களுக்கு இடம் விட்டார்! மோஸ்லே — நவீன ஆவர்த்தன விதி: அணு எண்ணின் அடிப்படை. நவீன அட்டவணையில் 18 தொகுதிகள் (நெடுவரிசை), 7 வரிசைகள் (கிடைவரிசை). 18-வது தொகுதி — மந்த வாயுக்கள்; 1-வது தொகுதி — கார உலோகங்கள்; 17-வது — ஹாலஜன்கள்.', 'Mendeleev (1869) arranged elements by atomic mass — and left gaps for elements not yet discovered! Moseley — the modern periodic law: arranged by atomic number. The modern table has 18 groups (columns) and 7 periods (rows). Group 18 — noble gases; group 1 — alkali metals; group 17 — halogens.')},
  [cq('📅','தனிம வரிசை அட்டவணையை உருவாக்கியவர் (1869)?','Who made the periodic table in 1869?','மெண்டலீஃப்','Mendeleev',[['மோஸ்லே','Moseley'],['டால்டன்','Dalton'],['ரூதர்ஃபோர்ட்','Rutherford']]),
   cq('🔢','நவீன ஆவர்த்தன விதியின் அடிப்படை?','The modern periodic law is based on…','அணு எண்','atomic number',[['அணு நிறை','atomic mass'],['அடர்த்தி','density'],['நிறம்','colour']]),
   cq('↕️','நவீன அட்டவணையில் தொகுதிகள் எத்தனை?','How many groups in the modern table?','18','18',[['7','7'],['8','8'],['16','16']]),
   cq('↔️','நவீன அட்டவணையில் வரிசைகள் (periods) எத்தனை?','How many periods in the modern table?','7','7',[['18','18'],['8','8'],['9','9']]),
   cq('🎈','18-வது தொகுதி?','Group 18 is the…','மந்த வாயுக்கள்','noble gases',[['கார உலோகங்கள்','alkali metals'],['ஹாலஜன்கள்','halogens'],['கார மண் உலோகங்கள்','alkaline earth metals']]),
   cq('🧂','17-வது தொகுதி (F, Cl, Br, I)?','Group 17 (F, Cl, Br, I) is the…','ஹாலஜன்கள்','halogens',[['மந்த வாயுக்கள்','noble gases'],['கார உலோகங்கள்','alkali metals'],['மாற்றுத் தனிமங்கள்','transition elements']]),
   cq('🔥','1-வது தொகுதி (Li, Na, K)?','Group 1 (Li, Na, K) is the…','கார உலோகங்கள்','alkali metals',[['ஹாலஜன்கள்','halogens'],['மந்த வாயுக்கள்','noble gases'],['கார மண் உலோகங்கள்','alkaline earth metals']])]);
H.functionalGroups = pairGame({title:S('வினைச்செயல் தொகுதிகள்', 'Functional groups'), icon:'🧫',
  intro:S('−OH — ஆல்கஹால் (எத்தனால்). −COOH — கார்பாக்சிலிக் அமிலம் (அசிட்டிக் அமிலம், வினிகர்). −CHO — ஆல்டிஹைடு. >C=O — கீட்டோன் (அசிட்டோன்). C=C இரட்டைப் பிணைப்பு — ஆல்கீன்; C≡C முப்பிணைப்பு — ஆல்கைன்.', '−OH — alcohol (ethanol). −COOH — carboxylic acid (acetic acid, vinegar). −CHO — aldehyde. >C=O — ketone (acetone). C=C double bond — alkene; C≡C triple bond — alkyne.')},
  pairs([['🍶','−OH தொகுதி?','The −OH group means…','ஆல்கஹால்','alcohol'],['🥗','−COOH தொகுதி?','The −COOH group means…','கார்பாக்சிலிக் அமிலம்','carboxylic acid'],['🧴','−CHO தொகுதி?','The −CHO group means…','ஆல்டிஹைடு','aldehyde'],['💅','>C=O (இரு கார்பன்களுக்கு நடுவே)?','>C=O (between two carbons) means…','கீட்டோன்','ketone'],['🔗','C=C இரட்டைப் பிணைப்பு?','A C=C double bond means…','ஆல்கீன்','alkene'],['⛓️','C≡C முப்பிணைப்பு?','A C≡C triple bond means…','ஆல்கைன்','alkyne']]));
H.ioDevices = sortGame({title:S('உள்ளீடு, வெளியீடு, சேமிப்பு', 'Input, output & storage'), icon:'🖥️',
  intro:S('உள்ளீட்டுக் கருவிகள் கணினிக்குத் தகவல் தரும் (விசைப்பலகை, சுட்டி, ஸ்கேனர், மைக்ரோஃபோன், வெப்கேம்). வெளியீட்டுக் கருவிகள் முடிவைக் காட்டும் (திரை, அச்சுப்பொறி, ஒலிபெருக்கி, புரொஜெக்டர்). சேமிப்புக் கருவிகள் தகவலைச் சேமிக்கும் (ஹார்டு டிஸ்க், பென் டிரைவ், SSD, மெமரி கார்டு).', 'Input devices give data to the computer (keyboard, mouse, scanner, microphone, webcam). Output devices show results (monitor, printer, speaker, projector). Storage devices keep data (hard disk, pen drive, SSD, memory card).'),
  ask:S('எந்த வகைக் கருவி?', 'Which kind of device?'), rule:S('தருவது → உள்ளீடு • காட்டுவது → வெளியீடு • வைத்திருப்பது → சேமிப்பு', 'Gives → input • shows → output • keeps → storage')},
  [{id:'i', e:'⌨️', ta:'உள்ளீடு', en:'Input'}, {id:'o', e:'🖨️', ta:'வெளியீடு', en:'Output'}, {id:'s', e:'💾', ta:'சேமிப்பு', en:'Storage'}],
  items([['⌨️','விசைப்பலகை','keyboard','i'],['🖱️','சுட்டி','mouse','i'],['📠','ஸ்கேனர்','scanner','i'],['🎙️','மைக்ரோஃபோன்','microphone','i'],['📷','வெப்கேம்','webcam','i'],['🖥️','திரை','monitor','o'],['🖨️','அச்சுப்பொறி','printer','o'],['🔊','ஒலிபெருக்கி','speaker','o'],['📽️','புரொஜெக்டர்','projector','o'],
    ['💽','ஹார்டு டிஸ்க்','hard disk','s'],['🔌','பென் டிரைவ்','pen drive','s'],['💾','SSD','SSD','s'],['🗂️','மெமரி கார்டு','memory card','s']]), 6);
H.hwSw = sortGame({title:S('வன்பொருள், மென்பொருள்', 'Hardware or software?'), icon:'🧰',
  intro:S('வன்பொருள் (hardware) — தொட முடியும் பாகங்கள் (CPU, RAM, விசைப்பலகை). மென்பொருள் (software) — நிரல்கள், தொட முடியாது (இயக்க முறைமை, உலாவி, விளையாட்டு). இயக்க முறைமை (OS) — Windows, Linux, Android — வன்பொருளையும் பயனரையும் இணைக்கும்.', 'Hardware — parts you can touch (CPU, RAM, keyboard). Software — programs you can’t touch (operating system, browser, games). An operating system (OS) — Windows, Linux, Android — connects the hardware and the user.'),
  ask:S('வன்பொருளா, மென்பொருளா?', 'Hardware or software?'), rule:S('தொட முடிந்தால் → வன்பொருள்', 'If you can touch it → hardware')},
  [{id:'h', e:'🔩', ta:'வன்பொருள்', en:'Hardware'}, {id:'s', e:'💿', ta:'மென்பொருள்', en:'Software'}],
  items([['🧠','CPU (செயலி)','CPU (processor)','h'],['🧮','RAM','RAM','h'],['🖥️','மதர்போர்டு','motherboard','h'],['⌨️','விசைப்பலகை','keyboard','h'],['🔋','பவர் சப்ளை','power supply','h'],
    ['🪟','இயக்க முறைமை (Windows/Linux)','operating system (Windows/Linux)','s'],['🌐','இணைய உலாவி','web browser','s'],['📝','சொல் செயலி','word processor','s'],['🎮','கணினி விளையாட்டு','computer game','s'],['🛡️','வைரஸ் தடுப்பு நிரல்','antivirus program','s']]), 6);

/* ================= SOCIAL SCIENCE ================= */
const years = (arr, grp) => arr.map(([e, qt, qe, y]) => ({e, grp, q:S(qt, qe), a:S(String(y), String(y))}));
H.worldHistory = pairGame({title:S('உலக வரலாறு — ஆண்டுகள்', 'World history — dates'), icon:'🌍',
  intro:S('கொலம்பஸ் அமெரிக்கா சென்றது 1492; வாஸ்கோடகாமா கோழிக்கோடு (கள்ளிக்கோட்டை) வந்தது 1498. அமெரிக்கச் சுதந்திரப் பிரகடனம் 1776; பிரெஞ்சுப் புரட்சி 1789; ரஷ்யப் புரட்சி 1917. முதல் உலகப் போர் 1914–1918; இரண்டாம் உலகப் போர் 1939–1945; ஐக்கிய நாடுகள் சபை 1945.', 'Columbus reached the Americas in 1492; Vasco da Gama reached Calicut (Kozhikode) in 1498. American Declaration of Independence 1776; French Revolution 1789; Russian Revolution 1917. First World War 1914–1918; Second World War 1939–1945; United Nations 1945.')},
  years([['⛵','கொலம்பஸ் அமெரிக்காவை அடைந்த ஆண்டு?','Columbus reached the Americas in…',1492],['🚢','வாஸ்கோடகாமா கோழிக்கோடு வந்த ஆண்டு?','Vasco da Gama reached Calicut in…',1498],['🗽','அமெரிக்கச் சுதந்திரப் பிரகடனம்?','American Declaration of Independence?',1776],['🇫🇷','பிரெஞ்சுப் புரட்சி தொடங்கிய ஆண்டு?','The French Revolution began in…',1789],
    ['☭','ரஷ்யப் புரட்சி?','The Russian Revolution?',1917],['⚔️','முதல் உலகப் போர் தொடங்கிய ஆண்டு?','The First World War began in…',1914],['💣','இரண்டாம் உலகப் போர் தொடங்கிய ஆண்டு?','The Second World War began in…',1939],['🇺🇳','ஐக்கிய நாடுகள் சபை தொடங்கிய ஆண்டு?','The United Nations was founded in…',1945]], 'y')
  .concat([cq('🖨️','அச்சு இயந்திரத்தை (நகரும் எழுத்துகள்) ஐரோப்பாவில் உருவாக்கியவர்?','Who built the movable-type printing press in Europe?','குட்டன்பர்க்','Gutenberg',[['ஜேம்ஸ் வாட்','James Watt'],['கலிலியோ','Galileo'],['நியூட்டன்','Newton']]),
    cq('🏭','தொழிற்புரட்சி முதலில் தொடங்கிய நாடு?','The Industrial Revolution began in…','பிரிட்டன்','Britain',[['பிரான்ஸ்','France'],['அமெரிக்கா','the USA'],['ஜப்பான்','Japan']]),
    cq('🎨','மறுமலர்ச்சி (Renaissance) தொடங்கிய நாடு?','The Renaissance began in…','இத்தாலி','Italy',[['இங்கிலாந்து','England'],['ஸ்பெயின்','Spain'],['கிரீஸ்','Greece']])]));
H.freedomStruggle = pairGame({title:S('இந்திய விடுதலைப் போராட்டம்', 'India’s freedom struggle'), icon:'🇮🇳',
  intro:S('வேலூர்ப் புரட்சி 1806. இந்திய தேசிய காங்கிரஸ் 1885. வங்கப் பிரிவினை 1905. ஜாலியன்வாலா பாக் 1919. ஒத்துழையாமை இயக்கம் 1920. உப்புச் சத்தியாகிரகம் — தண்டி, வேதாரண்யம் 1930. வெள்ளையனே வெளியேறு 1942. விடுதலை 1947. தமிழகம்: வேலு நாச்சியார், வீரபாண்டிய கட்டபொம்மன், வ.உ.சி. (சுதேசி கப்பல் நிறுவனம் 1906), பாரதியார், திருப்பூர் குமரன் (கொடி காத்த குமரன்), இராஜாஜி (வேதாரண்யம்).', 'Vellore Mutiny 1806. Indian National Congress 1885. Partition of Bengal 1905. Jallianwala Bagh 1919. Non-Cooperation Movement 1920. Salt Satyagraha — Dandi and Vedaranyam 1930. Quit India 1942. Independence 1947. Tamil Nadu: Velu Nachiyar, Veerapandiya Kattabomman, V. O. Chidambaram (Swadeshi Steam Navigation Company 1906), Bharathiyar, Tiruppur Kumaran (who guarded the flag), Rajaji (Vedaranyam).')},
  years([['⚔️','வேலூர்ப் புரட்சி?','The Vellore Mutiny?',1806],['🏛️','இந்திய தேசிய காங்கிரஸ் தொடங்கிய ஆண்டு?','The Indian National Congress was founded in…',1885],['✂️','வங்கப் பிரிவினை?','Partition of Bengal?',1905],['😢','ஜாலியன்வாலா பாக் படுகொலை?','Jallianwala Bagh massacre?',1919],['🙅','ஒத்துழையாமை இயக்கம்?','Non-Cooperation Movement?',1920],['🧂','தண்டி / வேதாரண்யம் உப்புச் சத்தியாகிரகம்?','Dandi / Vedaranyam Salt Satyagraha?',1930],['🚪','வெள்ளையனே வெளியேறு இயக்கம்?','Quit India Movement?',1942]], 'y')
  .concat(pairs([['🚢','சுதேசி நீராவிக் கப்பல் நிறுவனத்தைத் தொடங்கியவர்?','Who started the Swadeshi Steam Navigation Company?','வ.உ. சிதம்பரனார்','V. O. Chidambaram'],['🧂','வேதாரண்யம் உப்புச் சத்தியாகிரகத்தை நடத்தியவர்?','Who led the Vedaranyam Salt Satyagraha?','இராஜாஜி','Rajaji'],['🚩','"கொடி காத்த குமரன்"?','"Kodi Kaatha Kumaran" (who guarded the flag)?','திருப்பூர் குமரன்','Tiruppur Kumaran'],['👑','ஆங்கிலேயரை எதிர்த்துப் போரிட்டுச் சிவகங்கையை மீட்ட அரசி?','Queen who fought the British and won back Sivaganga?','வேலு நாச்சியார்','Velu Nachiyar'],['🏰','பாஞ்சாலங்குறிச்சியின் வீரர்?','The hero of Panchalankurichi?','வீரபாண்டிய கட்டபொம்மன்','Veerapandiya Kattabomman']], 'p')));
H.earthLayers = pairGame({title:S('புவியின் அடுக்குகள், வளிமண்டலம்', 'Earth’s layers & atmosphere'), icon:'🌎',
  intro:S('புவியின் உள் அமைப்பு: மேலோடு → கவசம் (மேன்டில்) → கருவம் (கோர்). வளிமண்டல அடுக்குகள்: அடிவளிமண்டலம் (வானிலை நிகழ்வுகள்) → மீள்வளிமண்டலம் (ஓசோன் படலம், விமானங்கள்) → இடைவளிமண்டலம் (எரிகற்கள் எரியும்) → வெப்பவளிமண்டலம் → புறவளிமண்டலம்.', 'Earth’s interior: crust → mantle → core. Layers of the atmosphere: troposphere (weather) → stratosphere (ozone layer, jet planes) → mesosphere (meteors burn up) → thermosphere → exosphere.')},
  pairs([['⛅','மழை, மேகம், வானிலை நிகழும் அடுக்கு?','Where does weather (rain, clouds) happen?','அடிவளிமண்டலம்','troposphere'],['🛡️','ஓசோன் படலம் உள்ள அடுக்கு?','Where is the ozone layer?','மீள்வளிமண்டலம்','stratosphere'],['☄️','எரிகற்கள் எரியும் அடுக்கு?','Where do meteors burn up?','இடைவளிமண்டலம்','mesosphere'],['🛰️','வளிமண்டலத்தின் வெளிப்புற அடுக்கு?','The outermost layer of the atmosphere?','புறவளிமண்டலம்','exosphere']], 'a')
  .concat(pairs([['🥚','புவியின் மிக வெளி அடுக்கு (நாம் வாழும் பகுதி)?','Earth’s outermost layer (where we live)?','மேலோடு','crust'],['🔥','புவியின் மையப் பகுதி?','The centre of the Earth?','கருவம் (கோர்)','core'],['🌋','மேலோட்டுக்கும் கருவத்துக்கும் இடையே?','Between the crust and the core?','கவசம் (மேன்டில்)','mantle']], 'e')));
H.rocks = sortGame({title:S('பாறைகளின் வகைகள்', 'Types of rocks'), icon:'🪨',
  intro:S('தீப்பாறைகள் — உருகிய மாக்மா குளிர்ந்து உருவானவை (கிரானைட், பசால்ட்). படிவுப் பாறைகள் — அடுக்கு அடுக்காகப் படிந்தவை (மணற்கல், சுண்ணாம்புக்கல்). உருமாறிய பாறைகள் — வெப்பம், அழுத்தத்தால் மாறியவை (சுண்ணாம்புக்கல் → பளிங்கு; களிமண் பாறை (ஷேல்) → ஸ்லேட்).', 'Igneous rocks — formed when molten magma cools (granite, basalt). Sedimentary rocks — laid down in layers (sandstone, limestone). Metamorphic rocks — changed by heat and pressure (limestone → marble; shale → slate).'),
  ask:S('எந்த வகைப் பாறை?', 'Which type of rock?'), rule:S('மாக்மா → தீப்பாறை • அடுக்கு → படிவு • மாற்றம் → உருமாறிய', 'Magma → igneous • layers → sedimentary • changed → metamorphic')},
  [{id:'i', e:'🌋', ta:'தீப்பாறை', en:'Igneous'}, {id:'s', e:'🏜️', ta:'படிவுப் பாறை', en:'Sedimentary'}, {id:'m', e:'💎', ta:'உருமாறிய பாறை', en:'Metamorphic'}],
  items([['🪨','கிரானைட்','granite','i'],['⬛','பசால்ட்','basalt','i'],['🟫','மணற்கல்','sandstone','s'],['⬜','சுண்ணாம்புக்கல்','limestone','s'],['🧱','ஷேல்','shale','s'],['🤍','பளிங்கு','marble','m'],['🔲','ஸ்லேட்','slate','m'],['✨','குவார்ட்சைட்','quartzite','m']]), 6);
H.cropSeasons = sortGame({title:S('காரீஃப், ராபி பயிர்கள்', 'Kharif & rabi crops'), icon:'🌾',
  intro:S('காரீஃப் — தென்மேற்குப் பருவமழை தொடங்கும்போது (ஜூன்–ஜூலை) விதைப்பு: நெல், மக்காச்சோளம், பருத்தி, நிலக்கடலை, கம்பு. ராபி — குளிர்காலத் தொடக்கத்தில் (அக்டோபர்–டிசம்பர்) விதைப்பு: கோதுமை, கடுகு, கொண்டைக்கடலை, பார்லி. தமிழ்நாட்டுக்கு அதிக மழை வடகிழக்குப் பருவமழையில் (அக்டோபர்–டிசம்பர்) கிடைக்கிறது.', 'Kharif — sown when the south-west monsoon starts (June–July): rice, maize, cotton, groundnut, bajra. Rabi — sown at the start of winter (October–December): wheat, mustard, gram, barley. Tamil Nadu gets most of its rain from the north-east monsoon (October–December).'),
  ask:S('எந்தப் பருவப் பயிர்?', 'Which season’s crop?'), rule:S('பருவமழைத் தொடக்கம் → காரீஃப் • குளிர்காலம் → ராபி', 'Monsoon start → kharif • winter → rabi')},
  [{id:'k', e:'🌧️', ta:'காரீஃப்', en:'Kharif'}, {id:'r', e:'❄️', ta:'ராபி', en:'Rabi'}],
  items([['🌾','நெல்','rice','k'],['🌽','மக்காச்சோளம்','maize','k'],['☁️','பருத்தி','cotton','k'],['🥜','நிலக்கடலை','groundnut','k'],['🌿','கம்பு','bajra (pearl millet)','k'],['🍞','கோதுமை','wheat','r'],['🌼','கடுகு','mustard','r'],['🫘','கொண்டைக்கடலை','gram (chickpea)','r'],['🍺','பார்லி','barley','r']]), 6);
H.riversFlow = sortGame({title:S('கிழக்கே, மேற்கே பாயும் ஆறுகள்', 'East- or west-flowing rivers'), icon:'🏞️',
  intro:S('தீபகற்ப இந்தியாவின் பெரும்பாலான ஆறுகள் கிழக்கே வங்கக் கடலில் கலக்கின்றன — மகாநதி, கோதாவரி, கிருஷ்ணா, காவிரி (டெல்டாக்களை உருவாக்கும்). நர்மதை, தபதி மேற்கே அரபிக் கடலில் கலக்கின்றன (கழிமுகங்களை உருவாக்கும்).', 'Most rivers of peninsular India flow east into the Bay of Bengal — Mahanadi, Godavari, Krishna, Kaveri (they form deltas). The Narmada and Tapi flow west into the Arabian Sea (they form estuaries).'),
  ask:S('எந்தக் கடலில் கலக்கிறது?', 'Which sea does it reach?'), rule:S('நர்மதை, தபதி → மேற்கு; மற்ற பெரிய தீபகற்ப ஆறுகள் → கிழக்கு', 'Narmada, Tapi → west; the other big peninsular rivers → east')},
  [{id:'e', e:'🌅', ta:'வங்கக் கடல் (கிழக்கு)', en:'Bay of Bengal (east)'}, {id:'w', e:'🌇', ta:'அரபிக் கடல் (மேற்கு)', en:'Arabian Sea (west)'}],
  items([['🌊','மகாநதி','Mahanadi','e'],['🌊','கோதாவரி','Godavari','e'],['🌊','கிருஷ்ணா','Krishna','e'],['🌊','காவிரி','Kaveri','e'],['🌊','வைகை','Vaigai','e'],['🌊','நர்மதை','Narmada','w'],['🌊','தபதி','Tapi','w']]), 6);
H.soils = pairGame({title:S('இந்திய மண் வகைகள்', 'Soils of India'), icon:'🟤',
  intro:S('வண்டல் மண் — மிக வளமானது, கங்கைச் சமவெளி, டெல்டாக்கள். கரிசல் (கருப்பு) மண் — ஈரத்தைத் தக்கவைக்கும், பருத்திக்கு ஏற்றது. செம்மண் — இரும்பு ஆக்சைடு காரணமாகச் சிவப்பு. சரளை (லேட்டரைட்) மண் — அதிக மழையில் கழுவப்பட்டது, தேயிலை, காபி, முந்திரி.', 'Alluvial soil — the most fertile, in the Ganga plains and deltas. Black (regur) soil — holds moisture, ideal for cotton. Red soil — red from iron oxide. Laterite soil — leached by heavy rain, grows tea, coffee, cashew.')},
  pairs([['☁️','பருத்திக்கு ஏற்ற மண்?','Soil best for cotton?','கரிசல் மண்','black soil'],['🌾','மிக வளமான, ஆற்றுச் சமவெளி மண்?','The most fertile soil of river plains?','வண்டல் மண்','alluvial soil'],['🔴','இரும்பு ஆக்சைடால் சிவப்பு நிறம்?','Red because of iron oxide?','செம்மண்','red soil'],['☕','அதிக மழையில் கழுவப்பட்டது — தேயிலை, காபி, முந்திரி?','Leached by heavy rain — tea, coffee, cashew?','சரளை மண்','laterite soil']]));
H.taxes = sortGame({title:S('நேர்முக, மறைமுக வரிகள்', 'Direct & indirect taxes'), icon:'🧾',
  intro:S('நேர்முக வரி — வருமானம் ஈட்டுபவரே நேரடியாகச் செலுத்துவது (வருமான வரி, நிறுவன வரி, சொத்து வரி). மறைமுக வரி — பொருள், சேவையின் விலையில் சேர்ந்து வருவது (GST — 2017 ஜூலை 1 முதல், சுங்க வரி). வரிப்பணமே பள்ளி, மருத்துவமனை, சாலைகளாக மாறுகிறது.', 'Direct tax — paid directly by the person who earns (income tax, corporate tax, property tax). Indirect tax — included in the price of goods and services (GST — from 1 July 2017, customs duty). Tax money becomes schools, hospitals and roads.'),
  ask:S('நேர்முகமா, மறைமுகமா?', 'Direct or indirect?'), rule:S('வருமானம்/சொத்து மீது → நேர்முகம் • விலையில் சேர்ந்தது → மறைமுகம்', 'On income/property → direct • inside the price → indirect')},
  [{id:'d', e:'👤', ta:'நேர்முக வரி', en:'Direct tax'}, {id:'i', e:'🛒', ta:'மறைமுக வரி', en:'Indirect tax'}],
  items([['💼','வருமான வரி','income tax','d'],['🏢','நிறுவன வரி','corporate tax','d'],['🏠','சொத்து வரி','property tax','d'],['🧾','GST','GST','i'],['🛃','சுங்க வரி','customs duty','i']]), 5);
H.intlBodies = pairGame({title:S('உலக அமைப்புகளும் உடன்படிக்கைகளும்', 'World bodies & agreements'), icon:'🌐',
  intro:S('ஐ.நா. சபை 1945 (அக்டோபர் 24). மனித உரிமைகள் பிரகடனம் 1948 டிசம்பர் 10 (மனித உரிமைகள் தினம்). பஞ்சசீலம் 1954 (இந்தியா–சீனா). அணிசேரா இயக்கம் 1961. சார்க் (SAARC) 1985. உலக வர்த்தக அமைப்பு (WTO) 1995. இந்திய ரிசர்வ் வங்கி 1935. இந்தியாவின் தேசிய மனித உரிமைகள் ஆணையம் 1993.', 'The UN 1945 (24 October). Universal Declaration of Human Rights, 10 December 1948 (Human Rights Day). Panchsheel 1954 (India–China). Non-Aligned Movement 1961. SAARC 1985. World Trade Organization 1995. Reserve Bank of India 1935. India’s National Human Rights Commission 1993.')},
  years([['📜','மனித உரிமைகள் உலகப் பிரகடனம்?','Universal Declaration of Human Rights?',1948],['🤝','பஞ்சசீல ஒப்பந்தம்?','The Panchsheel agreement?',1954],['🕊️','அணிசேரா இயக்கம் தொடங்கிய ஆண்டு?','The Non-Aligned Movement began in…',1961],['🌏','சார்க் (SAARC) தொடங்கிய ஆண்டு?','SAARC was founded in…',1985],['📦','உலக வர்த்தக அமைப்பு (WTO)?','World Trade Organization (WTO)?',1995],['🏦','இந்திய ரிசர்வ் வங்கி தொடங்கிய ஆண்டு?','The Reserve Bank of India was set up in…',1935],['⚖️','தேசிய மனித உரிமைகள் ஆணையம்?','National Human Rights Commission of India?',1993],['🧾','GST அறிமுகமான ஆண்டு?','GST was introduced in…',2017]], 'y'));
H.flower = pairGame({title:S('மலர், இனப்பெருக்கம்', 'Flowers & reproduction'), icon:'🌸',
  intro:S('மகரந்தத்தாள் (stamen) — ஆண் பகுதி; மகரந்தப்பை மகரந்தத்தைத் தயாரிக்கும். சூலகம் (pistil) — பெண் பகுதி: சூலகமுடி (stigma), சூலகத்தண்டு (style), சூற்பை (ovary). கருவுறுதலுக்குப் பின் சூல் விதையாகவும், சூற்பை கனியாகவும் மாறும். ஆண், பெண் இனச்செல்கள் இணைந்து உருவாவது கருமுட்டை (zygote).', 'Stamen — the male part; the anther makes pollen. Pistil — the female part: stigma, style and ovary. After fertilisation the ovule becomes the seed and the ovary becomes the fruit. Male and female gametes fuse to form a zygote.')},
  pairs([['🌼','மகரந்தத்தைத் தயாரிப்பது?','Which part makes pollen?','மகரந்தப்பை','anther'],['🎯','மகரந்தத்தைப் பெறும் பகுதி?','Which part receives pollen?','சூலகமுடி','stigma'],['🌰','கருவுறுதலுக்குப் பின் சூல் மாறுவது?','After fertilisation the ovule becomes the…','விதை','seed'],['🍎','கருவுறுதலுக்குப் பின் சூற்பை மாறுவது?','After fertilisation the ovary becomes the…','கனி','fruit'],['🧫','இனச்செல்கள் இணைந்து உருவாவது?','Gametes fuse to form a…','கருமுட்டை (zygote)','zygote']]));
H.evolution = pairGame({title:S('பரிணாமக் கொள்கைகள்', 'Theories of evolution'), icon:'🦒',
  intro:S('லாமார்க் — பெறப்பட்ட பண்புகள் கடத்தப்படுகின்றன என்று கருதினார் (ஒட்டகச்சிவிங்கியின் கழுத்து எடுத்துக்காட்டு — இன்று இது ஏற்கப்படவில்லை). டார்வின் — இயற்கைத் தேர்வு: சூழலுக்கு ஏற்றவை பிழைத்து, சந்ததியைப் பெருக்கும். ஹியூகோ டி விரிஸ் — திடீர் மாற்றக் கொள்கை (mutation).', 'Lamarck — thought acquired characters are passed on (the giraffe’s neck example — not accepted today). Darwin — natural selection: those best suited to their surroundings survive and have more offspring. Hugo de Vries — mutation theory.')},
  pairs([['🦒','பெறப்பட்ட பண்புகளின் மரபுரிமைக் கொள்கை?','Inheritance of acquired characters?','லாமார்க்','Lamarck'],['🐦','இயற்கைத் தேர்வுக் கொள்கை?','Natural selection?','டார்வின்','Darwin'],['🧬','திடீர் மாற்றக் கொள்கை (mutation theory)?','Mutation theory?','ஹியூகோ டி விரிஸ்','Hugo de Vries'],['🌱','மரபியல் விதிகள் (பட்டாணிச் செடி)?','Laws of inheritance (pea plants)?','மெண்டல்','Mendel']]));
H.biotech = pairGame({title:S('உயிரித் தொழில்நுட்பம்', 'Biotechnology'), icon:'🧪',
  intro:S('Bt பருத்தி — Bacillus thuringiensis பாக்டீரியாவின் மரபணு சேர்க்கப்பட்டது, பூச்சிகளை எதிர்க்கும். டாலி — முதல் குளோனிங் பாலூட்டி (செம்மறியாடு, 1996). மனித இன்சுலின் — மரபணு மாற்றிய பாக்டீரியாவைக் கொண்டு தயாரிக்கப்படுகிறது. பசுமைப் புரட்சி — உயர் விளைச்சல் ரகங்கள்.', 'Bt cotton — carries a gene from the bacterium Bacillus thuringiensis and resists pests. Dolly — the first cloned mammal (a sheep, 1996). Human insulin — made using genetically modified bacteria. The Green Revolution — high-yielding varieties.')},
  [cq('☁️','Bt பருத்தியில் சேர்க்கப்பட்ட மரபணு எந்த உயிரியிலிருந்து?','Bt cotton carries a gene from…','Bacillus thuringiensis பாக்டீரியா','the bacterium Bacillus thuringiensis',[['ஈஸ்ட்','yeast'],['பட்டுப்புழு','the silkworm'],['வைரஸ்','a virus']]),
   cq('🐑','முதல் குளோனிங் பாலூட்டி?','The first cloned mammal?','டாலி (செம்மறியாடு)','Dolly (a sheep)',[['லைக்கா (நாய்)','Laika (a dog)'],['ஹாம் (சிம்பன்சி)','Ham (a chimpanzee)'],['ஸ்நப்பி (நாய்)','Snuppy (a dog)']]),
   cq('💉','இன்று மனித இன்சுலின் எவ்வாறு தயாரிக்கப்படுகிறது?','How is human insulin mostly made today?','மரபணு மாற்றிய பாக்டீரியா மூலம்','using genetically modified bacteria',[['பசுவின் பாலிலிருந்து','from cow’s milk'],['தாவர இலைகளிலிருந்து','from plant leaves'],['கடல் நீரிலிருந்து','from sea water']])]);
})(typeof window !== 'undefined' ? window : globalThis);
